### ISSUE TITLE
DXF produced by QGIS with gdal 2.4.0 crashes AutoCAD

### ISSUE THREAD

**Issue by AlisterH** [OSGeo/gdal#1220] opened 2019-01-21 06:24 UTC
Recent versions of QGIS packaged for Windows (e.g. 2.18.27, 2.18.28, 3.4.3) use gdal 2.4.0, and Layer>Save As>AutoCAD DXF produces DXF that crashes AutoCAD.

Older versions (e.g. 2.18.23 and 3.2.3) packaged with older versions of gdal produce larger dxf files (21kb vs 8kb for a minimal file), which don't crash AutoCAD, so I was told to file a ticket here.

DXF produced by ogr2ogr seems to be OK.

Looking at the contents of the dxf it isn't immediately obvious to me exactly what the problem with the dxf is, but I'm no expert.

## Expected behavior and actual behavior.

DXF file should not crash AutoCAD if someone tries to open it there.

## Steps to reproduce the problem.

Install QGIS packaged with gdal 2.4.0, open a shape file and do File>Save As>AutoCAD DXF

## Operating system

Only tested on Windows ("standalone" QGIS 64bit installers, AutoCAD 2017 and 2019).

## GDAL version and provenance

2.4.0, packaged with QGIS

**Comment by rouault** [comment] 2019-01-21 08:47
Seems to be a duplicate of #1213
What is not clear to me in the bug description is that there seems to be different of behaviour between QGIS Layer Save as DXF whereas ogr2ogr output is OK. But the output should be mostly comparable. Could you attach the output in those 2 cases ?

**Comment by AlisterH** [comment] 2019-01-21 10:19
Sorry, that's why it didn't seem like a duplicate of #1213, but testing again I find that ogr2ogr output is not OK, so I don't know what happened there.  
I was sure I tested with the osgeo shell from QGIS 2.18. 27 , but maybe it was actually an older one from an osgeo4w install (that Trend Micro has helpfully broken and prevent me from upgrading or removing!)

**Comment by rouault** [comment] 2019-01-21 13:18
OK, so that's a true duplicate then. Closing as such to keep only #1213 active

**Closed by rouault** 2019-01-21 13:18 UTC
