### ISSUE TITLE
gdal2tiles --version crashes after printing version

### ISSUE THREAD

**Issue by daniel-j-h** [OSGeo/gdal#2096] opened 2019-12-11 18:07 UTC
See below; version 2.4.2 from the ubuntugis ppa.

Expected output is just the version information, no crash.

```
$ gdal2tiles.py --version
GDAL 2.4.2, released 2019/06/28
Traceback (most recent call last):
  File "/usr/bin/gdal2tiles.py", line 2927, in <module>
    main()
  File "/usr/bin/gdal2tiles.py", line 2917, in main
    input_file, output_folder, options = process_args(argv[1:])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Coming from https://github.com/OSGeo/gdal/blob/d7a5cd432c9aa1e0ac6f879e80667fcc16772337/gdal/swig/python/scripts/gdal2tiles.py#L2922

**Comment by kannes** [comment] 2019-12-22 09:39
The cause is one line higher up, in https://github.com/OSGeo/gdal/blob/d7a5cd432c9aa1e0ac6f879e80667fcc16772337/gdal/swig/python/scripts/gdal2tiles.py#L2921 `gdal.GeneralCmdLineProcessor` returns `None` if you pass "`--version`". I have no idea what that function does and how it is supposed to work. There does not seem to be documentation for it.

Other bundled Python scripts https://github.com/OSGeo/gdal/search?q=GeneralCmdLineProcessor&unscoped_q=GeneralCmdLineProcessor check for `None` and abort, but they also do not use `OptionParser`. `gdal2tiles.py` is a totally foreign script, I would suggest simply dropping the version parameter to solve this. :}

**Comment by EvertEt** [comment] 2020-12-23 20:20
Already fixed by https://github.com/OSGeo/gdal/commit/78249811d72c17691e0b588cafd4af434bb89719.

**Comment by imshuv** [comment] 2020-12-26 21:18
Hey, I want to contribute here can someone please help me get started with it??(just a beginner)

**Comment by kannes** [comment] 2020-12-30 20:39
Hi @imshuv, this issue is already fixed, @rouault just needs to close it.

If you want to join development in general and not this particular issue, best check https://github.com/OSGeo/gdal/blob/master/README.md and maybe post on the mailing list to introduce yourself. Thanks!

**Comment by imshuv** [comment] 2020-12-30 20:48
Thanks for replying 
Actually I'm a newbie in this open source environment kindly guide me to become a genuine contributer in this org.
Will be really thankful.

**Closed** 2020-12-30 22:53 UTC
Labels: good first issue
