### ISSUE TITLE
CPLODBCSession::CPLODBCSession() does not initialize 'm_hDBC' to NULL

### ISSUE THREAD

**Issue by fstanchina** [OSGeo/gdal#6256] opened 2022-08-25 10:38 UTC
## Expected behavior and actual behavior.

I expected `session.GetConnection()` to be NULL on a newly instanced CPLODBCSession object.
In my case, the value is 0x0000000100000000.

## Steps to reproduce the problem.

Check `session.GetConnection() == NULL` on a newly instanced CPLODBCSession object.

## Operating system

Windows 10 

## GDAL version and provenance

GDAL 3.5.1-2 from OSGeo4W

**Comment by fstanchina** [comment] 2022-08-25 10:40
Verified by looking at the source code: https://github.com/OSGeo/gdal/blob/master/port/cpl_odbc.cpp

Indeed the constructor doesn't initialize `m_hDBC` nor `m_hEnv`.

**Comment by fstanchina** [comment] 2022-08-25 11:06
Wait, I didn't look at the header. Now I did and I see:
```c++
class CPL_DLL CPLODBCSession {
    ...
    HENV      m_hEnv = nullptr;
    HDBC      m_hDBC = nullptr;
    ...
```

I'm not entirely familiar with the ins and outs of initializers in the header, so I can't see what's going wrong here. If it matters, I'm using Visual Studio 2019.

**Comment by rouault** [comment] 2022-08-27 13:47
I can't see where the code could be wrong here given the inline initialization of m_hEnv and m_hDBC to nullptr. I'd assume an issue in your build environment. Perhaps like looking with a debugger on a optimized build ?

**Comment by chetanpandey1266** [comment] 2022-08-30 19:04
> look at the header.

That's not a header. Its a private member of the class and I find no issue as the initialization has been done here. There might be something else causing the issue.

**Comment by rouault** [comment] 2022-09-02 13:14
closing as likely not a bug

**Closed by rouault** 2022-09-02 13:14 UTC

**Comment by fstanchina** [comment] 2022-09-04 17:24
Sorry for not replying earlier. This problem shows up only in the debug build of our project(s), the release build works fine. I don't understand where the problem is exactly, we're using other prebuilt libraries with no trouble; I also tried tweaking some compiler options related to the debug build, with no success.
