### ISSUE TITLE
change in SimplifyPreserveTopology results

### ISSUE THREAD

**Issue by emlys** [OSGeo/gdal#9584] opened 2024-03-29 23:17 UTC
### What is the bug?

In gdal>=3.6.4, I am getting different results from `SimplifyPreserveTopology` than with gdal<3.6.4. I didn't find an obvious explanation for this in the release notes. I am not sure if the new result is technically right or wrong, but it's not what I would expect.

### Steps to reproduce the issue

```
from osgeo import gdal, ogr
import shapely

shapely_geom = shapely.geometry.Point((1180000, 690000)).buffer(100)
geom = ogr.CreateGeometryFromWkb(shapely_geom.wkb)
print(geom.SimplifyPreserveTopology(125))
```
With gdal 3.6.3 and below, the result is a square (`POLYGON ((1180100 690000,1180000 689900,1179900 690000,1180000 690100,1180100 690000))`). With gdal 3.6.4 and above, the result is a triangle (`POLYGON ((1180000 690100,1180000 689900,1179900 690000,1180000 690100))`). I confirmed that the original shapely geometries are identical, and it is still happening with the latest version 3.8.4.

### Versions and provenance

macOS Ventura 13.2.1, gdal 3.6.4 and above from conda-forge

**Comment by dbaston** [comment] 2024-03-30 00:32
This sounds like it's related to a change in the GEOS library: https://github.com/libgeos/geos/pull/784

You can check your GEOS version with
```
ogr.GetGEOSVersionMajor(), ogr.GetGEOSVersionMinor(), ogr.GetGEOSVersionMicro()
```

**Comment by jratike80** [comment] 2024-03-30 10:19
Test with PostGIS 3.4.1 with GEOS="3.12.1-CAPI-1.18.1" GDAL="GDAL 3.7.1, released 2023/07/06 GDAL_DATA not found" LIBXML="2.9.14" LIBJSON="0.12" LIBPROTOBUF="1.2.1" WAGYU="0.5.0 (Internal)" RASTER

```
select (
	ST_AsText(
	ST_SimplifyPreserveTopology(
	ST_Buffer(
ST_GeomFromText('POINT (1180000 690000)'),100
	),125)))

POLYGON((1180000 690100,1180000 689900,1179900 690000,1180000 690100))
```
The result is a triangle.
In both cases the topology is preserved correctly. The tolerance in simplification is 125 units. In the square result the distance between the leftmost and rightmost vertices is 200 units, and removing on vertex is moving the segment by less than the tolerance. Conclusion: Triangle is expected result. But I do not know what kind of service promise functions like ST_Simplify have. Is it guaranteed that every vertex that can be removed is really removed
 and is it guaranteed that no extra vertices are removed.

<img width="125" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/4d5b2197-bcf0-4f18-b1b0-7a46ad3c2019">

**Comment by rouault** [comment] 2024-03-30 12:05
OGR SimplifyPreserveTopology is a direct mapping to GEOSTopologyPreserveSimplify_r. Any change of behavior here is due to a GEOS upstream change as stated in https://github.com/OSGeo/gdal/issues/9584#issuecomment-2027844902 . Closing as not a GDAL bug (and probably not a bug at all)

**Closed by rouault** 2024-03-30 12:05 UTC

**Comment by emlys** [comment] 2024-04-01 17:37
thanks for the explanation 👍
