### ISSUE TITLE
SHAPEFILE: NaN values should not be allowed for coordinates values (and they make OGR crash)

### ISSUE THREAD

**Issue by agiudiceandrea** [OSGeo/gdal#3542] opened 2021-03-06 17:06 UTC
In the "[ESRI Shapefile Technical Description](https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf)" is stated that:

> Numeric Types - A shapefile stores integer and double-precision numbers. The remainder of this document
> will refer to the following types:
> - Integer: Signed 32-bit integer (4 bytes)
> - Double: Signed 64-bit IEEE double-precision floating point number (8 bytes)
> 
> **Floating point numbers must be numeric values. Positive infinity, negative infinity, and Not-a-Number (NaN) values are not allowed in shapefiles**. Nevertheless, shapefiles support the concept of "no data" values, but they are currently used only for measures. Any floating point number smaller than –10<sup>38</sup> is considered by a shapefile reader to represent a "no data" value.

and

> Point - A point consists of a pair of double-precision coordinates in the order X,Y.
> Point
> {
> Double X // X coordinate
> Double Y // Y coordinate
> }

So, it seems NaN (and infinity) values are not allowed for coordinates according to the shapefile format specification.

Nevertheless it is possible to create a shapefile layer with Not-a-Number (NaN) coordinates using GDAL/OGR.

EDITED: Such shapefile with NaN coordinates makes QGIS and `ogrinfo` with a `-spat` option crash.
EDITED: For such shapefile `ogrinfo --debug on` reports an incorrect number of feature read and an invalid extent in the shape header.

## Steps to reproduce the problem.

EDITED:

Using the following code (in QGIS 3.16.4 with GDAL/OGR 3.1.4 - OSGeo4W):

```
from osgeo import ogr

point1Coord = 7.447819,46.947820
point2Coord = float('nan'),float('nan')

outSHPfn = 'F:/QGIS/nanshapefile.shp'
shpDriver = ogr.GetDriverByName("ESRI Shapefile")
outDataSource = shpDriver.CreateDataSource(outSHPfn)
outLayer = outDataSource.CreateLayer(outSHPfn, geom_type=ogr.wkbPoint )
idField = ogr.FieldDefn('id', ogr.OFSTInt16)
outLayer.CreateField(idField)
featureDefn = outLayer.GetLayerDefn()

point = ogr.Geometry(ogr.wkbPoint)
point.AddPoint(point1Coord[0],point1Coord[1])
outFeature = ogr.Feature(featureDefn)
outFeature.SetGeometry(point)
outFeature.SetField('id', 1)
outLayer.CreateFeature(outFeature)

point = ogr.Geometry(ogr.wkbPoint)
point.AddPoint(point2Coord[0],point2Coord[1])
outFeature = ogr.Feature(featureDefn)
outFeature.SetGeometry(point)
outFeature.SetField('id', 2)
outLayer.CreateFeature(outFeature)

outFeature = None
outDataSource = None
```

the resulting [shapefile](https://github.com/OSGeo/gdal/files/6099809/nanshapefile.zip) contains two points:
1: coords  0x401DCA91105E1C15 ≈  7.447819, 0x404779522A6F3F53 ≈ 46.947820
2: coords 0x7FF8000000000000 = NaN, 0x7FF8000000000000 = NaN

With GDAL/OGR 3.1.4 or 3.2.1
`ogrinfo F:\QGIS\nanshapefile.shp -al --debug on`
outputs
```
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\gdal_ECW_JP2ECW.dll using GDALRegister_ECW_JP2ECW.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\gdal_GEOR.dll using GDALRegister_GEOR.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\gdal_HDF5.dll using GDALRegister_HDF5.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\gdal_MG4Lidar.dll using GDALRegister_MG4Lidar.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\gdal_MrSID.dll using GDALRegister_MrSID.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\ogr_OCI.dll using RegisterOGROCI.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\ogr_SOSI.dll using RegisterOGRSOSI.
GDAL: AutoSkipDriver(ODBC)
Shape: DBF Codepage = LDID/87 for F:\QGIS\nanshapefile.shp
Shape: Treating as encoding 'ISO-8859-1'.
GDAL: GDALOpen(F:\QGIS\nanshapefile.shp, this=00000000034DC2C0) succeeds as ESRI Shapefile.
INFO: Open of `F:\QGIS\nanshapefile.shp'
      using driver `ESRI Shapefile' successful.
OGR: GetLayerCount() = 1


Layer name: nanshapefile
Metadata:
  DBF_DATE_LAST_UPDATE=2021-03-08
Geometry: Point
Feature Count: 2
SHAPE: Invalid extent in shape header
Extent: (7.447819, 46.947820) - (7.447819, 46.947820)
Layer SRS WKT:
(unknown)
id: Real (24.15)
OGRFeature(nanshapefile):0
  id (Real) = 1.000000000000000
  POINT (7.447819 46.94782)

OGRFeature(nanshapefile):1
  id (Real) = 2.000000000000000
  POINT (nan nan)

Shape: 4 features read on layer 'nanshapefile'.
GDAL: GDALClose(F:\QGIS\nanshapefile.shp, this=00000000034DC2C0)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

[notice "SHAPE: Invalid extent in shape header"]
[notice the incorrect "Shape: 4 features read on layer 'nanshapefile'."]

and `ogrinfo F:\QGIS\nanshapefile.shp -al --debug on -spat 7 46 8 47`
outputs
```
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\gdal_ECW_JP2ECW.dll using GDALRegister_ECW_JP2ECW.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\gdal_GEOR.dll using GDALRegister_GEOR.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\gdal_HDF5.dll using GDALRegister_HDF5.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\gdal_MG4Lidar.dll using GDALRegister_MG4Lidar.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\gdal_MrSID.dll using GDALRegister_MrSID.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\ogr_OCI.dll using RegisterOGROCI.
GDAL: Auto register F:\QGIS\OSGEO4~1.4\qgis\bin\gdalplugins\ogr_SOSI.dll using RegisterOGRSOSI.
GDAL: AutoSkipDriver(ODBC)
Shape: DBF Codepage = LDID/87 for F:\QGIS\nanshapefile.shp
Shape: Treating as encoding 'ISO-8859-1'.
GDAL: GDALOpen(F:\QGIS\nanshapefile.shp, this=0000000003F85440) succeeds as ESRI Shapefile.
INFO: Open of `F:\QGIS\nanshapefile.shp'
      using driver `ESRI Shapefile' successful.
OGR: GetLayerCount() = 1


Layer name: nanshapefile
Metadata:
  DBF_DATE_LAST_UPDATE=2021-03-08
Geometry: Point
SHAPE: Invalid extent in shape header
Feature Count: 2
SHAPE: Invalid extent in shape header
Extent: (7.447819, 46.947820) - (7.447819, 46.947820)
Layer SRS WKT:
(unknown)
id: Real (24.15)
SHAPE: Invalid extent in shape header
OGRFeature(nanshapefile):0
  id (Real) = 1.000000000000000
  POINT (7.447819 46.94782)
```
and then crashes.

To resume some tests on Windows 7 64 bit
`ogrinfo F:\QGIS\nanshapefile.shp -al -spat 7 46 8 47`
with
GDAL 3.3.0dev ([gisinternals](https://gisinternals.com/packageinfo.php?file=release-1928-x64-gdal-mapserver.zip) - GEOS 3.9.0-CAPI-1.14.1): crashes
GDAL 3.2.1 ([gisinternals](https://gisinternals.com/packageinfo.php?file=release-1928-x64-gdal-3-2-1-mapserver-7-6-2.zip) - GEOS 3.9.0-CAPI-1.14.1): crashes
GDAL 3.1.4 (OSGeo4W - GEOS 3.8.1-CAPI-1.13.3): crashes
GDAL 3.0.2 (OSGeo4W - GEOS 3.8.0-CAPI-1.13.1): crashes
GDAL 2.4.1 (OSGeo4W - GEOS 3.7.0-CAPI-1.11.0): doesn't crash
GDAL 2.4.0 (OSGeo4W - GEOS 3.7.0-CAPI-1.11.0): doesn't crash
GDAL 2.2.4 (OSGeo4W - GEOS 3.6.1-CAPI-1.10.1): doesn't crash

QGIS [crashes](https://github.com/qgis/QGIS/issues/41739) adding nanshapefile.shp to a map using the above reported GDAL >= 3.0.3 / GEOS >= 3.8.0 versions, while QGIS doesn't crash using GDAL <= 2.4.1 / GEOS <= 3.6.0.

## Operating system

Windows 7 64 bit

## GDAL version and provenance

GDAL 3.1.4 (OSGeo4W) - GDAL 3.2.1 ([gisinternals](https://gisinternals.com/packageinfo.php?file=release-1928-x64-gdal-3-2-1-mapserver-7-6-2.zip))

**Comment by agiudiceandrea** [comment] 2021-03-06 18:41
See also:
https://github.com/qgis/QGIS/issues/41739 "Crash when loading a Shapefile with NaN coordinates"
https://github.com/OSGeo/gdal/issues/1109 "Inconsistent handling of Nan and Infinity with Geojson driver"
https://github.com/OSGeo/gdal/pull/1111 "GeoJSON: no longer write NaN/Infinity values by default (fixes #1109)"

**Comment by jratike80** [comment] 2021-03-08 07:38
I could not make GDAL/OGR to crash with the command `ogrinfo esri_out.shp -al -spat 7 46 8 47` that was provided in the QGIS bug report. The QGIS issue has something to do with GEOS and I believe that -spat option does not need GEOS. But there is also something wrong with the shx because ArcGIS Pro gives warnings
```
WARNING 000442: bad dataset extent at -1 in shapefile_with_nans
 WARNING 000442: could not find spatial index at -1 in shapefile_with_nans
 ```

I attach a shapefile that is rewritten with ArcGIS Pro by opening the NaN shapefile and writing the layer into a new shapefile. If it has no other value it can at least give an example about a valid shx index with a null geometry.
[esri_out.zip](https://github.com/OSGeo/gdal/files/6099617/esri_out.zip)

**Comment by agiudiceandrea** [comment] 2021-03-08 08:33
@jratike80 esri_out.shp doesn't contain NaN coordinates.
It contains two points:
1: coords 0x401DCA91105E1C15 ≈ 7.447819, 0x404779522A6F3F53 ≈ 46.947820
2: coords 0xFFEFFFFFFFFFFFFF = Min. Double ≈ -1.797693E308 , 0xFFEFFFFFFFFFFFFF = Min. Double ≈ -1.797693E308

**Comment by jratike80** [comment] 2021-03-08 09:08
As I supposed, ESRI accepts NaN even it is against the shapefile specification and interprets that they mean NULL, but writes out a compliant shapefile.
I agree that GDAL/GEOS/QGIS should not crash. I cannot reproduce the crash with `ogrinfo esri_out.shp -al -spat 7 46 8 47`  on Windows but obviously it crashes on Linux. There may also be some differences in libraries involved, I did not check.

It is possible to create such NaN shapefile with a program. Is it also possible to get such with ogr2ogr by converting from other formats? I am wondering how important it is to fix something that is connected to NaN shapefiles that should never exist, and that are very seldom in real world?

**Comment by agiudiceandrea** [comment] 2021-03-08 10:34
esri_out.shp doesn't contain NaN coordinates: ogrinfo never crash.
[nanshapefile.shp](https://github.com/OSGeo/gdal/files/6099809/nanshapefile.zip) or [shapefile_with_nans.shp](https://github.com/qgis/QGIS/files/6022996/shapefile_with_nans.zip) contain NaN coordinates: ogrinfo crash

A similar issue with NaN (not about coordinates) for GeoJson is https://github.com/OSGeo/gdal/issues/1109 which was fixed with https://github.com/OSGeo/gdal/pull/1111

To add some other test ad resume previous ones:
on Windows 7 64 bit
`ogrinfo F:\QGIS\nanshapefile.shp nanshapefile -spat 7 46 8 47`
with
GDAL 3.2.1 ([gisinternals](https://gisinternals.com/packageinfo.php?file=release-1928-x64-gdal-3-2-1-mapserver-7-6-2.zip) - GEOS 3.9.0): crashes
GDAL 3.1.4 (OSGeo4W - GEOS 3.8.1-CAPI-1.13.3): crashes
GDAL 3.0.2 (OSGeo4W - GEOS 3.8.0-CAPI-1.13.1): crashes
GDAL 2.4.1 (OSGeo4W - GEOS 3.7.0-CAPI-1.11.0): doesn't crash
GDAL 2.4.0 (OSGeo4W - GEOS 3.7.0-CAPI-1.11.0): doesn't crash
GDAL 2.2.4 (OSGeo4W - GEOS 3.6.1-CAPI-1.10.1): doesn't crash

**Comment by jratike80** [comment] 2021-03-08 10:44
One more to the list:
GDAL 3.3.0dev (gisinternals - GEOS 3.9.0): no crash for me with `ogrinfo shapefile_with_nans.shp -al -spat 7 46 8 47 --debug on`.

**Comment by jratike80** [comment] 2021-03-08 11:23
The right thing to do on the writer side would be to convert all NULL, infinity, and NaN into `-1.7976931348623158e+308`
https://desktop.arcgis.com/en/arcmap/10.3/manage-data/shapefiles/geoprocessing-considerations-for-shapefile-output.htm

**Comment by agiudiceandrea** [comment] 2021-03-08 12:39
@jratike80 ogrinfo (the same gisinternals 3.3.0dev release-1928-x64-gdal-mapserver MSVC 2019 x64 version) crashes on my Windows 7 64 bit system just after reporting:
```
F:\QGIS\release-1928-x64-gdal-mapserver>ogrinfo --version
GDAL 3.3.0dev, released 2021/99/99

F:\QGIS\release-1928-x64-gdal-mapserver>ogrinfo shapefile_with_nans.shp -al -spat 7 46 8 47 --debug on
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_BAG.dll using GDALRegister_BAG.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_ECW_JP2ECW.dll using GDALRegister_ECW_JP2ECW.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_FITS.dll using GDALRegister_FITS.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_GMT.dll using GDALRegister_GMT.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_HDF4.dll using GDALRegister_HDF4.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_HDF4Image.dll using GDALRegister_HDF4Image.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_HDF5.dll using GDALRegister_HDF5.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_HDF5Image.dll using GDALRegister_HDF5Image.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_KEA.dll using GDALRegister_KEA.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_MG4Lidar.dll using GDALRegister_MG4Lidar.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_MrSID.dll using GDALRegister_MrSID.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_netCDF.dll using GDALRegister_netCDF.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\gdal_PDF.dll using GDALRegister_PDF.
GDAL: Auto register F:\QGIS\release-1928-x64-gdal-mapserver\bin\gdal\plugins\ogr_AmigoCloud.dll using RegisterOGRAmigoCloud.
GDAL: AutoSkipDriver(ODBC)
Shape: DBF Codepage = ISO-8859-1 for shapefile_with_nans.shp
Shape: Treating as encoding 'ISO-8859-1'.
GDAL: GDALOpen(shapefile_with_nans.shp, this=000000000294BB60) succeeds as ESRI Shapefile.
INFO: Open of `shapefile_with_nans.shp'
      using driver `ESRI Shapefile' successful.
OGR: GetLayerCount() = 1


Layer name: shapefile_with_nans
Metadata:
  DBF_DATE_LAST_UPDATE=2021-02-22
Geometry: Point
SHAPE: Invalid extent in shape header
Feature Count: 2
SHAPE: Invalid extent in shape header
Extent: (7.447819, 46.947820) - (7.447819, 46.947820)
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
title: String (80.0)
x: Real (24.15)
y: Real (24.15)
SHAPE: Invalid extent in shape header
OGRFeature(shapefile_with_nans):0
  title (String) = Bern, Switzerland
  x (Real) = 7.447819000000000
  y (Real) = 46.947820000000000
  POINT (7.447819 46.94782)
```

**Comment by jratike80** [comment] 2021-03-08 13:15
Ok, I understand, it is crashing and nothing gets printed after that point of report. I just thought that it finished normally.

But try this, it is interesting:

```
ogr2ogr rewritten.shp shapefile_with_nans.shp

C:\data\000\0>ogrinfo rewritten.shp -al  --debug on
...
GDAL: GDALOpen(rewritten.shp, this=00000221056339E0) succeeds as ESRI Shapefile.
INFO: Open of `rewritten.shp'
      using driver `ESRI Shapefile' successful.
OGR: GetLayerCount() = 1


Layer name: rewritten
Metadata:
  DBF_DATE_LAST_UPDATE=2021-03-08
Geometry: Point
Feature Count: 2
SHAPE: Invalid extent in shape header
Extent: (7.447819, 46.947820) - (7.447819, 46.947820)
...
Data axis to CRS axis mapping: 2,1
title: String (80.0)
x: Real (24.15)
y: Real (24.15)
OGRFeature(rewritten):0
  title (String) = Bern, Switzerland
  x (Real) = 7.447819000000000
  y (Real) = 46.947820000000000
  POINT (7.447819 46.94782)

OGRFeature(rewritten):1
  title (String) = NaLocation
  x (Real) = (null)
  y (Real) = (null)
  POINT (nan nan)

Shape: 4 features read on layer 'rewritten'.
GDAL: GDALClose(rewritten.shp, this=00000221056339E0)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

So, by trying to fix the NaN shapefile by making a copy with GDAL created an even more weird shapefile with one NaN geometry, totally 2 features on the layer, but still: `Shape: 4 features read on layer 'rewritten'.`.

**Comment by agiudiceandrea** [comment] 2021-03-08 13:53
`Shape: 4 features read on layer 'rewritten'.` is another weirdness.
Anyway "rewritten" and "shapefile_with_nans" shapefiles are almost identical: *.shp *.shx *.prj are exactly identical and *.dbf only differ by the last updated date, so "rewritten" doesn't seem to me weirder than "shapefile_with_nans" as they contain the same exact geometries.
In fact, also for shapefile_with_nans.shp ogrinfo reports `Shape: 4 features read on layer 'shapefile_with_nans'.`.

**Comment by jratike80** [comment] 2021-03-08 14:11
> In fact, also for shapefile_with_nans.shp ogrinfo reports `Shape: 4 features read on layer 'shapefile_with_nans'.`.

How do you know that? For me the crash happens before those lines get written. And if they are identical why "shapefile_with_nans" yield a crash for me but "rewritted does not"?

Sooner or later we must answer the fundamental question: Is this issue important enough for the GDAL (and QGIS ) projects so it is worth to sacrifice developer time for resolving it.

For me this is a weird and entertaining issue but I am just a GDAL user and hobbyist and I don't count my time.

**Comment by agiudiceandrea** [comment] 2021-03-08 15:11
> How do you know that? For me the crash happens before those lines get written. And if they are identical why "shapefile_with_nans" yield a crash for me but "rewritten" does not"?

You used `ogrinfo rewritten.shp -al  --debug on` (without the `-spat` option).

Without the `-spat` option, ogrinfo doesn't crash but it incorrectly reports "Shape: 4 features read" for rewritten.shp, for shapefile_with_nans and for nanshapefile.shp which contain only two features.
With the `-spat` option, ogrinfo crashes for rewritten.shp, for shapefile_with_nans and for nanshapefile.shp.

> Is this issue important enough for the GDAL (and QGIS ) projects

OGR can create non compliant shapefiles and OGR (or maybe the GEOS library) is not capable of properly handle those shapefile that itself has created.

Those shapefiles make QGIS crash using the above reported GDAL >= 3.0.3 / GEOS >= 3.8.0 versions, while QGIS doesn't crash using GDAL <= 2.4.1 / GEOS <= 3.6.0.

**Comment by jratike80** [comment] 2021-03-08 15:40
Right, I should have been more systematic with testing.

**Comment by jratike80** [comment] 2021-03-08 17:49
I found also something that is probably unrelated:
Convert
`ogr2ogr -f gml nan.gml shapefile_with_nans.shp`

Check the GML
```
 <ogr:geometryProperty><gml:Point srsName="EPSG:4326"><gml:coordinates>nan,nan</gml:coordinates></gml:Point></ogr:geometryProperty>
      <ogr:title>NaLocation</ogr:title>
      <ogr:x xsi:nil="true"/>
      <ogr:y xsi:nil="true"/>
```
ogrinfo
```
OGRFeature(shapefile_with_nans):1
  fid (String) = shapefile_with_nans.1
  title (String) = NaLocation
  x (Real) = (null)
  y (Real) = (null)
  POINT (0 0)
```

The empty feature is read as POINT (0 0) and it seems to be converted as such into for example shapefile.

**Closed** 2021-03-08 22:42 UTC
