### ISSUE TITLE
Python: Mutating some internal state of HTTP

### ISSUE THREAD

**Issue by four43** [OSGeo/gdal#2189] opened 2020-01-23 14:49 UTC
## Expected behavior and actual behavior.

Changing the import order of the `osgeo` library to before `requests` breaks functionality. There is some internal modification being done from the `osgeo` library to some HTTP stack that is breaking `requests`

## Steps to reproduce the problem.

```python
import requests
from osgeo import gdal

print(f"ogr version: {gdal.__version__}, requests version: {requests.__version__}")
requests.get('https://www.weather.gov/gis/Counties')
print("Success!")
```
```bash
$ python ./test.py || echo "Exit code: $?"
ogr version: 3.0.3, requests version: 2.22.0
Success!
```
^ Works as expected
But switching the order of the imports so `requests` is loaded first:
```python
from osgeo import gdal
import requests

print(f"ogr version: {gdal.__version__}, requests version: {requests.__version__}")
requests.get('https://www.weather.gov/gis/Counties')
print("Success!")
```
```bash
$ python ./test.py || echo "Exit code: $?"
ogr version: 3.0.3, requests version: 2.22.0
Exit code: 139
```

This seems like a really bad internal state mutation or cross cut issue.

For some reason in this context python didn't actually puke out the exception. In my application (not just this trimmed down example) requests was mad about a gzip stream issue:
```
requests.exceptions.ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -2 while decompressing data: inconsistent stream state'))
```

## Operating system

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

uname -a
Linux ws 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## GDAL version and provenance

3.0.3 via conda-forge

Thanks all, let me know if I can provide more information.

**Comment by rouault** [comment] 2020-01-23 18:27
I can't reproduce with my development build of GDAL. Perhaps somethig specific to Conda builds of GDAL ? GDAL shouldn't do anything particular regarding network if not using network related functionality, except loading libcurl. So perhaps some bad interaction between libcurl and requests ??

**Comment by four43** [comment] 2020-01-23 20:04
@rouault - Is there anything I can do to help you further diagnose? Should I kick this up to https://github.com/conda-forge/gdal-feedstock ?

Thanks for your response,
-Seth

**Comment by rouault** [comment] 2020-01-23 20:10
That would require in-depth investigation / more familiarity with conda based builds, which which I'm not familiar . So yes reporting this to conda upstream is probably the best road.

**Comment by four43** [comment] 2020-01-27 14:15
^ Downstream report in Conda Forge

**Comment by rouault** [comment] 2020-02-25 20:08
Closing as has been reported to https://github.com/conda-forge/gdal-feedstock

**Closed by rouault** 2020-02-25 20:08 UTC

**Comment by AdrianoKF** [comment] 2020-07-30 06:38
Sorry for resurrecting this closed issue, but I think I have encountered a similar issue with GDAL 3.0.4, albeit not in the Conda version of GDAL, but the Arch package of GDAL, which is directly built from sources.

I have asked about the issue on StackOverflow (https://stackoverflow.com/questions/63161532/python-segmentation-fault-when-using-zipfile-while-gdal-package-loaded). If you'd like, I can create a new issue - or just attribute the error to cosmic radiation, since the workaround below works for me.

#### Workaround
(credits to @gvellut, see [their comment](https://github.com/conda-forge/gdal-feedstock/issues/365#issuecomment-611744253) on the downstream issue report)

Moving the GDAL module import to the very end of the imports list seems to fix the errors / segfaults. Maybe this helps anyone finding this issue report instead of the Conda downstream one. :)
