### ISSUE TITLE
GDAL Polygonize creates invalid geometry

### ISSUE THREAD

**Issue by ungvarizs** [OSGeo/gdal#3653] opened 2021-04-06 18:14 UTC
Hi, 
I may found an inconsistency, which result is an invalid geometry. I used the GDAL Polygonize function through QGIS.  The Result contains invalid geometries like closed stroke line, or the ring touches the stroke. (See the picture below)

## Steps to reproduce the problem.
**Detailed description of my working process in QGIS.**
I have an SRTM model for an hilly area (in geotiff). With the raster calculator I make the following expression srtm@1<200
Result is another geotiff with pixel values 0 (for areas with are higher than 200m) and 1 (for areas which are lower than 200 m). I called the function Polygonize. Result a vector type file format (e.g.Shapefile), with an attribute field, which value are inherited from the raster.
I deleted the 0, and kept the 1. I want further vector geoprocessing (e.g. Clip), but I can not, because this result shapefile may contains several invalid geometries: closed stroke line, or the ring touches the stroke (see on the picture below).

**I could fix the problem using QGIS fix geometry, but I think the vector output of Polygonize have to be geometrically valid, therefore I report this. I tried to report it in the QGIS github page, but the guys told me, this is GDAL problem. Hope it help to the development of software. **

GDAL version: what is in the QGIS 3.14. 
Op Sys Win10. 

Here you can see a picture about the problem, and I also added my files, shapefile contains invalid geometries.
[vas.zip](https://github.com/OSGeo/gdal/files/6266742/vas.zip)

![image](https://user-images.githubusercontent.com/82045669/113758182-da71dc80-9713-11eb-99ca-9df44fa53ffb.png)

**Comment by rouault** [comment] 2021-04-06 18:19
Duplicate of https://github.com/OSGeo/gdal/issues/3319

**Closed by rouault** 2021-04-06 18:19 UTC
