### ISSUE TITLE
ogr2ogr: problem when using SQL-File with comments with leading space

### ISSUE THREAD

**Issue by dpalmetzvbg** [OSGeo/gdal#4250] opened 2021-08-16 12:53 UTC
## Expected behavior and actual behavior.

SQL-Command fails when working with an SQL-File that has comments in it, and one comment has a leading space in the line.
In my case it was very unlucky, becaus this comment was right before an UNION, so there was no error message, but the second SQL-Statement after UNION was not executed, so I did not realize that one third of the rows were missing.

I am using ogr2ogr to get data from Oracle 12 to postgres 9.6

## Steps to reproduce the problem.

1. create a sql-file with a simple statement with mulitple lines like:
```
select e.field1,

-- Testcomment without leading space

e.field2,

 -- Testcomment with leading space leads to error

e.field3

from testtable e
```
2. execute ogr2ogr: ```ogr2ogr -f PostgreSQL PG:"host=<hostname> port=<port> user=<pguser> password=<pgpwd> dbname=<dbname>" -nln ogr2ogr_test OCI:<oracleuser>/<oraclepwd>@<oracledb> -sql @"sql1.sql" -overwrite -a_srs EPSG:31254```

## Operating system

Windows 10, 64 bit

## GDAL version and provenance

gdal 3.0.4 from osgeo4w

**Comment by rouault** [comment] 2021-08-16 13:18
This is a duplicate of #2811, which was fixed in 3.2.0

**Closed by rouault** 2021-08-16 13:18 UTC
