### ISSUE TITLE
`gdaladdo` modifies NoData values when producing overviews for single-band GeoTIFF

### ISSUE THREAD

**Issue by MattF-NSIDC** [OSGeo/gdal#8187] opened 2023-08-08 16:54 UTC
## Expected behavior and actual behavior.

I expected to be able to add overviews to my dataset while preserving NoData values. In data visualization programs, I expect NoData values to show up as transparent at all zoom levels.

Instead, the NoData value in overviews is slightly different from the NoData value in the actual data. In data visualization programs, NoData values are only transparent when displaying original data. When displaying overviews, NoData values are opaque.

![Overview NoData values not being recognized as NoData by QGIS](https://github.com/OSGeo/gdal/assets/18539827/a1b7ff7f-6f1c-44a4-a60b-960454ece4fe)

Data link: http://qgreenland.apps.nsidc.org/layers/geoid/geoid.tif

There is a significant swath of NoData value at the top-left of this raster, so coordinate `(0,0)` is a good reference point.

## Steps to reproduce the problem.

This data already has overviews, so we can reproduce by clearing them first then adding them back:

0. Download data: http://qgreenland.apps.nsidc.org/layers/geoid/geoid.tif
1. `gdaladdo -clean geoid.tif`
2. `gdaladdo geoid.tif 2`
3. Validate in Python REPL. Step [12] shows inequality, and steps [13-15] show metadata seems to be correctly set.

```python
In [1]: from osgeo import gdal

In [2]: gdal.__version__
Out[2]: '3.6.4'

In [3]: ds = gdal.Open('geoid.tif')

In [4]: band = ds.GetRasterBand(1)

In [8]: overview_corner = band.GetOverview(0).ReadAsArray()[0][0]

In [9]: data_corner = band.ReadAsArray()[0][0]

In [10]: overview_corner
Out[10]: 1.701410009187828e+38

In [11]: data_corner
Out[11]: 1.70141e+38

In [12]: overview_corner == data_corner
Out[12]: False

In [13]: band.GetNoDataValue()
Out[13]: 1.70141e+38

In [14]: band.GetOverview(0).GetNoDataValue()
Out[14]: 1.70141e+38

In [15]: band.GetOverview(0).GetNoDataValue() == band.GetNoDataValue()
Out[15]: True
```

## Operating system

Pop!_OS 22 and Ubuntu 20

## GDAL version and provenance

* `3.6.3` from `conda-forge`
* `3.7.1` from `conda-forge`

**Comment by MattF-NSIDC** [comment] 2023-08-08 17:10
Tested latest version on conda-forge and updated above.

**Comment by rouault** [comment] 2023-08-08 17:23
This is related to the data type being Float64, but the overview computation is done on Float32, hence losing accuracy when computing pixel values. This should be fixed

**Comment by jratike80** [comment] 2023-08-08 17:30
Most accurate Float32 presentation from https://binaryconvert.com/ seems to be 1.7014100551605224609375, and Float64  1.70141000000000008895995051716.
I wonder how safe it is for the data producers to use such nodata value instead of exact mask band, but maybe they know what they do.

**Comment by rouault** [comment] 2023-08-08 17:34
> I wonder how safe it is for the data producers to use such nodata value instead of exact mask band, but maybe they know what they do.

the issue is on GDAL side, this is due to 1.70141e+38 being cast as Float32 in processing steps, which causes a loss of precision, before being assigned to the target Float64 overview band:

```
>>> print(struct.unpack('f', struct.pack('f', 1.70141e+38)))
(1.701410009187828e+38,)
```

**Comment by MattF-NSIDC** [comment] 2023-08-08 17:55
Thanks all for looking in to this!

**Comment by rouault** [comment] 2023-08-08 18:04
Assuming that you can live with Float32 precision, you could do:
```
gdal_translate geoid.tif geoid_float32.tif -ot Float32
gdaladdo geoid_float32.tif 
```

**Comment by MattF-NSIDC** [comment] 2023-08-08 18:29
Thanks! We're not sure yet if we'll take that approach. It also worked for us to set the NoData value to `-9999`. I guess this works because the 64- and 32-bit representations are equivalent (`np.float32(-9999) == np.float64(-9999)`). This was more convenient for us to do because we could do it by adding a flag to an existing processing step (`gdalwarp ... -dst_nodata -9999 ...`) in our pipeline instead of adding a new step.

**Closed** 2023-08-23 09:02 UTC
