### ISSUE TITLE
GDALGetOutputDriversForDatasetName: Handle driver name prefixes

### ISSUE THREAD

**Issue by dbaston** [OSGeo/gdal#10263] opened 2024-06-21 17:42 UTC
### Feature description

I would have expected the following to either fail or create a table in the default Postgres database:
```
ogr2ogr PG av_lv95.gpkg resf
```
Instead, it creates a directory called `PG` and a shapefile within that directory. To get the desired behavior I had to do

```
ogr2ogr "PG:" av_lv95.gpkg resf
```
I'm not sure what the best behavior is, but I think the first command I tried should either fail, warn on ambiguity, or magically do what I wanted :)

**Comment by rouault** [comment] 2024-06-21 17:56
> but I think the first command I tried should either fail, warn on ambiguity, or magically do what I wanted :)

I agree that might be surprising, but that's the 'expected' behavior.  "PG" is not the recognized prefix of the PostgreSQL driver. It is "PG:".
If we'd want to change that, then we shouldn't automatically select shapefile when there's no .dbf/.shp extension in the filename, which might be slightly breaking change

**Comment by rouault** [comment] 2024-08-11 16:15
Closing this as won't fix / works as intended

**Closed by rouault** 2024-08-11 16:15 UTC
Labels: enhancement
