### ISSUE TITLE
PostgreSQL driver does not respect case-sensitive new layer name

### ISSUE THREAD

**Issue by jingsam** [OSGeo/gdal#3112] opened 2020-10-27 07:16 UTC
## Expected behavior and actual behavior.

I'm trying to import a geojson into postgresql using:

```
ogr2ogr -f PostgreSQL PG:'host=localhost port=5432 dbname=postgres user=postgres password=password' countries.geojson -nln jingsam.myTable -overwrite-lco LAUNDER=NO
```

It works as I expected: a table with the name of `myTable` created under `jingsam` schema.

Now I re-import same data with `-nln jingsam.mytable`:

```
ogr2ogr -f PostgreSQL PG:'host=localhost port=5432 dbname=postgres user=postgres password=password' countries.geojson -nln jingsam.mytable -overwrite-lco LAUNDER=NO
```

It complains:

```
ERROR 1: Layer jingsam.mytable already exists, CreateLayer failed.
```

It seems that telling a existing layer in pg driver is case-insensitive.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

Mac OS 10.15.5

## GDAL version and provenance

3.1

**Comment by rouault** [comment] 2024-04-18 17:47
I believe this is a duplicate of #9125 that has been fixed. Closing

**Closed by rouault** 2024-04-18 17:47 UTC
