### ISSUE TITLE
gdal_rasterize invert flag does not work

### ISSUE THREAD

**Issue by jontwo** [OSGeo/gdal#3301] opened 2020-12-18 11:11 UTC
## Expected behavior and actual behavior.

When rasterizing with `-i` option, every pixel has the `-burn` value and the input geometries are ignored.

## Steps to reproduce the problem.

Using a shapefile from the GDAL test data:
```
 λ gdal_rasterize -burn 1 -tr 10 -10 -of GTiff ogr\data\shp\testpoly.shp c:\temp\ras_test.tif
0...10...20...30...40...50...60...70...80...90...100 - done.

λ gdal_rasterize -i -burn 1 -tr 10 -10 -of GTiff ogr\data\shp\testpoly.shp c:\temp\ras_test_inv.tif
0...10...20...30...40...50...60...70...80...90...100 - done.

λ gdalinfo c:\temp\ras_test.tif -stats
...
Band 1 Block=60x17 Type=Float64, ColorInterp=Gray
  Minimum=0.000, Maximum=1.000, Mean=0.127, StdDev=0.333
  Metadata:
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=0.12722222222222
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=0.33322174057985
    STATISTICS_VALID_PERCENT=100

λ gdalinfo c:\temp\ras_test_inv.tif  -stats
...
Band 1 Block=60x17 Type=Float64, ColorInterp=Gray
  Minimum=1.000, Maximum=1.000, Mean=1.000, StdDev=0.000
  Metadata:
    STATISTICS_MAXIMUM=1
    STATISTICS_MEAN=1
    STATISTICS_MINIMUM=1
    STATISTICS_STDDEV=0
    STATISTICS_VALID_PERCENT=100

```

## Operating system

Microsoft Windows [Version 10.0.18363.1198]

## GDAL version and provenance

gdal                      3.2.0            py37hc63ff33_0    conda-forge

**Comment by rouault** [comment] 2020-12-18 12:43
Duplicate of https://github.com/OSGeo/gdal/issues/3124. Fix queued for GDAL 3.2.1

**Closed by rouault** 2020-12-18 12:43 UTC
