### ISSUE TITLE
Floating number irregularity in gdal_contour 3.9

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10287] opened 2024-06-24 08:41 UTC
### Feature description

This is a feature request that `gdal_contour` clean up its internal artifacts before they make their way to the e.g., WKT the public sees.

Yes, the following won't make one's map look bad, but are still rather odd.
```
$ cat m.xyz
500 5400 500
2200 5400 2200
500 4600 500
2200 4600 2200
$ gdal_contour -i 200 -q m.xyz n.csv -lco GEOMETRY=AS_WKT
$ cat n.csv
$ WKT,ID
"LINESTRING (600 4200,600 4600,600 5400,600 5800)",0
"LINESTRING (800.0 4200.0,800.0 4600.0,800.0 5400.0,800.0 5800.0)",1
"LINESTRING (1000.0 4200.0,1000.0 4600.0,1000.0 5400.0,1000.0 5800.0)",2
"LINESTRING (1200 4200,1200 4600,1200 5400,1200 5800)",3
"LINESTRING (1400.0 4200.0,1400.0 4600.0,1400.0 5400.0,1400.0 5800.0)",4
"LINESTRING (1600.0 4200.0,1600.0 4600.0,1600.0 5400.0,1600.0 5800.0)",5
"LINESTRING (1800 4200,1800 4600,1800 5400,1800 5800)",6
"LINESTRING (2000 4200,2000 4600,2000 5400,2000 5800)",7
"LINESTRING (2199.999999 4200.0,2199.999999 4600.0,2199.999999 5400.0,2199.999999 5800.0)",8
```

## Observation 1
Alternating groups of lines with ".0" attached, and ones without it.

Yes, we can clean it up with:
```
$ perl -pwle 's/\d+\.\d+/$&+0/ge' n.csv
"LINESTRING (600 4200,600 4600,600 5400,600 5800)",0
"LINESTRING (800 4200,800 4600,800 5400,800 5800)",1
"LINESTRING (1000 4200,1000 4600,1000 5400,1000 5800)",2
"LINESTRING (1200 4200,1200 4600,1200 5400,1200 5800)",3
"LINESTRING (1400 4200,1400 4600,1400 5400,1400 5800)",4
"LINESTRING (1600 4200,1600 4600,1600 5400,1600 5800)",5
"LINESTRING (1800 4200,1800 4600,1800 5400,1800 5800)",6
"LINESTRING (2000 4200,2000 4600,2000 5400,2000 5800)",7
"LINESTRING (2199.999999 4200,2199.999999 4600,2199.999999 5400,2199.999999 5800)",8
```

## Observation 2
Final line slipping.

Why can't it be on the mark? Correct 2200. Incorrect: 2199.999999

To also clean that up we need the stronger
```
$ perl -pwle 's/\d+\.\d+/0 + sprintf "%.5f", $&/ge' n.csv
"LINESTRING (600 4200,600 4600,600 5400,600 5800)",0
"LINESTRING (800 4200,800 4600,800 5400,800 5800)",1
"LINESTRING (1000 4200,1000 4600,1000 5400,1000 5800)",2
"LINESTRING (1200 4200,1200 4600,1200 5400,1200 5800)",3
"LINESTRING (1400 4200,1400 4600,1400 5400,1400 5800)",4
"LINESTRING (1600 4200,1600 4600,1600 5400,1600 5800)",5
"LINESTRING (1800 4200,1800 4600,1800 5400,1800 5800)",6
"LINESTRING (2000 4200,2000 4600,2000 5400,2000 5800)",7
"LINESTRING (2200 4200,2200 4600,2200 5400,2200 5800)",8
```

### Additional context

Maybe these are already cleaned up.  I only run Debian Sid, I.e., 3.9.0.

**Comment by rouault** [comment] 2024-06-24 14:04
closing as a duplicate of #10103

**Closed by rouault** 2024-06-24 14:04 UTC
Labels: enhancement
