### ISSUE TITLE
C# bindings apps broken in CI

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#4792] opened 2021-11-08 14:48 UTC
Since today both AppVeyor and github action workflow Windows are broken, due to a change external to GDAL (something with NuGet ??)
https://github.com/OSGeo/gdal/runs/4139684148?check_suite_focus=true
https://ci.appveyor.com/project/OSGeo/gdal/builds/41445624

The failure occurs with the GDALRead test application:
```
dotnet add GDALRead.csproj reference ..\gdal\gdal_csharp.csproj
Reference `..\gdal\gdal_csharp.csproj` added to the project.
	dotnet add GDALRead.csproj package System.Drawing.Common
  Determining projects to restore...
C:\Program Files\dotnet\sdk\5.0.402\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp2.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy. [D:\a\gdal\gdal\swig\csharp\apps\GDALRead.csproj]
  Writing C:\Users\runneradmin\AppData\Local\Temp\tmp754A.tmp
info : Adding PackageReference for package 'System.Drawing.Common' into project 'GDALRead.csproj'.
info :   GET https://api.nuget.org/v3/registration5-gz-semver2/system.drawing.common/index.json
info :   OK https://api.nuget.org/v3/registration5-gz-semver2/system.drawing.common/index.json 248ms
info : Restoring packages for D:\a\gdal\gdal\swig\csharp\apps\GDALRead.csproj...
info :   GET https://api.nuget.org/v3-flatcontainer/system.drawing.common/index.json
info :   OK https://api.nuget.org/v3-flatcontainer/system.drawing.common/index.json 46ms
info :   GET https://api.nuget.org/v3-flatcontainer/system.drawing.common/6.0.0/system.drawing.common.6.0.0.nupkg
info :   OK https://api.nuget.org/v3-flatcontainer/system.drawing.common/6.0.0/system.drawing.common.6.0.0.nupkg 12ms
info : Installed System.Drawing.Common 6.0.0 from https://api.nuget.org/v3/index.json with content hash NfuoKUiP2nUWwKZN6twGqXioIe1zVD0RIj2t976A+czLHr2nY454RwwXs6JU9Htc6mwqL6Dn/nEL3dpVf2jOhg==.
info : Package 'System.Drawing.Common' is compatible with all the specified frameworks in project 'GDALRead.csproj'.
info : PackageReference for package 'System.Drawing.Common' version '6.0.0' added to file 'D:\a\gdal\gdal\swig\csharp\apps\GDALRead.csproj'.
info : Committing restore...
info : Generating MSBuild file D:\a\gdal\gdal\swig\csharp\apps\obj\GDALRead.csproj.nuget.g.props.
info : Generating MSBuild file D:\a\gdal\gdal\swig\csharp\apps\obj\GDALRead.csproj.nuget.g.targets.
info : Writing assets file to disk. Path: D:\a\gdal\gdal\swig\csharp\apps\obj\project.assets.json
log  : Restored D:\a\gdal\gdal\swig\csharp\apps\GDALRead.csproj (in 706 ms).
	dotnet build -c Release -o "." -r win-x86 GDALRead.csproj
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Users\runneradmin\.nuget\packages\system.drawing.common\6.0.0\buildTransitive\netcoreapp2.0\System.Drawing.Common.targets(4,5): error : System.Drawing.Common doesn't support netcoreapp2.1. Consider updating your TargetFramework to netcoreapp3.1 or later. [D:\a\gdal\gdal\swig\csharp\apps\GDALRead.csproj]

Build FAILED.

C:\Users\runneradmin\.nuget\packages\system.drawing.common\6.0.0\buildTransitive\netcoreapp2.0\System.Drawing.Common.targets(4,5): error : System.Drawing.Common doesn't support netcoreapp2.1. Consider updating your TargetFramework to netcoreapp3.1 or later. [D:\a\gdal\gdal\swig\csharp\apps\GDALRead.csproj]
    0 Warning(s)
    1 Error(s)
```

CC @bjornharrtell @szekerest

**Comment by bjornharrtell** [comment] 2021-11-08 14:55
I recall something similar happened a year ago or something, we should try and find that issue - I don't remember what the solution was that time. netcoreapp2.1 is getting very old now so that has to go at some point but as I have a vague memory that it wasn't deprecation that was the cause/fix last time.

**Comment by bjornharrtell** [comment] 2021-11-08 14:57
I think the issue I was thinking about was https://github.com/OSGeo/gdal/issues/3711. Fixed by https://github.com/OSGeo/gdal/pull/3769 that time but I didn't understand it then and still don't.

**Closed** 2021-11-16 21:51 UTC
Labels: csharp bindings
