### ISSUE TITLE
ogr2ogr fails to import into postgres when 2 keys have same name with different case

### ISSUE THREAD

**Issue by angoca** [OSGeo/gdal#6617] opened 2022-11-04 21:43 UTC
## Expected behavior and actual behavior.

I am downloading all countries' silhouettes from OpenStreetMap via Overpass, I convert the JSON into a geojson with [osmtogeojson](https://github.com/tyrasd/osmtogeojson), and then I use ogr2ogr to import the geometry into Postgres.

When I am processing [Pakistan](https://www.openstreetmap.org/relation/307573) I have seen that name of the country is translated into "ku-Arab" and its admin center Islamabad is translated into "ku-arab". Because the name is the same, with the capital A being the only difference, Postgres does not allow to create of the table: ERROR:  column "name:ku_arab" specified more than once.

I modified the node in OpenStreetMap. And I attached the geojson file to this ticket.

[307573.geojson.txt](https://github.com/OSGeo/gdal/files/9942137/307573.geojson.txt)

## Steps to reproduce the problem.

```
cat << EOF > query
[out:json];
rel(307573);
(._;>;);
out; 
EOF

wget -O 307573.json --post-file=query "https://overpass-api.de/api/interpreter"

osmtogeojson 307573.json > 307573.geojson

ogr2ogr -f "PostgreSQL" PG:"dbname=postgres user=myuser" "307573.geojson" -nln import -overwrite
```

## Operating system

Linux osm-test 5.4.0-1073-raspi #84-Ubuntu SMP PREEMPT Sat Oct 15 11:15:37 UTC 2022 armv7l armv7l armv7l GNU/Linux
Ubuntu 22.04.5 LTS focal

## GDAL version and provenance

GDAL 3.0.4, released 2020/01/28

sudo apt-get install ogr2ogr

**Comment by jratike80** [comment] 2022-11-05 10:14
Have you already tried the layer creation option "LAUNDER" https://gdal.org/drivers/vector/pg.html?

> LAUNDER: This may be “YES” to force new fields created on this layer to have their field names “laundered” into a form more compatible with PostgreSQL. This converts to lower case and converts some special characters like “-” and “#” to “_”. If “NO” exact names are preserved. The default value is “YES”. If enabled the table (layer) name will also be laundered.

**Comment by rouault** [comment] 2022-11-05 10:52
As suggested by @jratike80 , adding -lco LAUNDER=NO would enable to import the data into PostGIS, but with one of the column renamed to 'name:ku-arab2', as GDAL mostly uses case-insensitive comparisons to determine if there are column duplicated names, so not probably what you'd expect. The GeoJSON importer was changed in 03663aa9cc0 to be able to consider field names differing only by case as being different, but in most other parts of GDAL this will cause confusion. 
I don't think we should do something in GDAL about that: we could offer some option to consider that field names only differing by case should be considered the same, so basically adding an option to undo 03663aa9cc0.  But here, the issue is really on the data side. GDAL can't have provisions for all data-originating issues.

**Comment by rouault** [comment] 2022-11-08 11:42
Closing as I don't believe there's any action on GDAL side

**Closed by rouault** 2022-11-08 11:42 UTC
