### ISSUE TITLE
Empty .ods/.xlsx with a first-row-header generates a .dbf with one line and default header

### ISSUE THREAD

**Issue by fpuga** [OSGeo/gdal#1238] opened 2019-01-26 18:05 UTC
## Expected behavior and actual behavior.

Mostly for scripting purposes I expect that:

* if I have a .ods or .xlsx with one row (as a header) and no more rows, 
* FORCE option is used for the header

the dbf created will be empty but use the first row as header. Now, it creates a .dbf with column names like "Field1", "Field2", ... and one row.

I attach an example for the .xlsx case (github does not allow to upload .ods or .dbf files):

input: [working.xlsx](https://github.com/OSGeo/gdal/files/2799319/working.xlsx)

## Steps to reproduce the problem.

1. Create a .xlsx or .ods file with only one row of strings (like the attached working.xlsx
2. Convert it to .dbf 

```
ogr2ogr -f "ESRI Shapefile" bar working.xlsx  -lco ENCODING=UTF-8 --config OGR_XLSX_HEADERS FORCE
```

## Operating system

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

## GDAL version and provenance
```
$ ogr2ogr --version
GDAL 2.2.3, released 2017/11/20

$ apt-cache policy gdal-bin 
gdal-bin:
  Instalados: 2.2.3+dfsg-2
  Candidato:  2.3.2+dfsg-2~bionic0
  Tabla de versión:
     2.3.2+dfsg-2~bionic0 500
        500 http://ppa.launchpad.net/ubuntugis/ubuntugis-unstable/ubuntu bionic/main amd64 Packages
 *** 2.2.3+dfsg-2 500
        500 http://es.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by rouault** [comment] 2019-02-03 15:37
Yes, it could probably work better, but the issue is that if there's just the row with column names, there is no way to guess the column data type... So even improving the code to work in that case would be moderately useful

**Comment by fpuga** [comment] 2019-02-04 17:04
Thanks to review it.

You are right maybe mine is a weird case. In any case i suppose fields can be created as strings as if `--config OGR_XLSX_FIELD_TYPES STRING` was used.

**Comment by rouault** [comment] 2019-03-20 22:21
Closing. Too particular use case

**Closed by rouault** 2019-03-20 22:21 UTC
