### ISSUE TITLE
Compilation fails on OS X in thinplatespline.cpp

### ISSUE THREAD

**Issue by benstadin** [OSGeo/gdal#4859] opened 2021-11-20 03:06 UTC
On OS X, using Xcode 13.1 with clang, compilation fails in thinplatespline.cpp with error "No viable overloaded '='" 

 ```
  GDALMatrix A(_nof_eqs, _nof_eqs);
...
   for( int c = 0; c < _nof_points; c++ )
    {
        x[c] -= x_mean;
        y[c] -= y_mean;
        A(0, c+3) = 1.0; // <-- here and subsequent assignments
        A(1, c+3) = x[c];
        A(2, c+3) = y[c];

        A(c+3, 0) = 1.0;
        A(c+3, 1) = x[c];
        A(c+3, 2) = y[c];
    }
```

**Comment by rouault** [comment] 2021-11-21 16:31
Weird. Can't reproduce that on BigSur 11.6.1 with XCode 13.1 command line utilities installed.
```
$ clang --version
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Can you show the compilation line and full error message, as well as output of ``clang --version`` ?

**Comment by forestgnome** [comment] 2021-11-30 09:39
Also not reproducible here (Monterey 12.0.1) :
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin21.1.0 
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by rouault** [comment] 2021-11-30 10:46
Closing as not reproducible. Please re-open if more details can be provided

**Closed by rouault** 2021-11-30 10:46 UTC
Labels: awaiting_feedback
