### ISSUE TITLE
Netcdf segmentation fault

### ISSUE THREAD

**Issue by rawedler** [OSGeo/gdal#917] opened 2018-09-13 08:04 UTC
Dear all,

I will make a projection like this with the netcdf-file below: 

 gdalwarp -of netCDF -s_srs '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs' -t_srs '+proj=tmerc +lat_0=0 +lon_0=9 +k=1 +x_0=3500000 +y_0=0 +ellps=bessel +datm=potsdam +units=m +no_defs' -te 3280415 5236500 3934415 6102500 -tr 1000 1000 -overwrite -dstnodata -9999 sat_gs_de_20180612.nc sat_gs_de_gauss_20180612.nc.

When I start gdalwarp I receive a segmentation fault. Where's the problem?

[sat_gs_de_20180718.zip](https://github.com/OSGeo/gdal/files/2378228/sat_gs_de_20180718.zip)

**Comment by rouault** [comment] 2018-09-13 08:34
I don't get a segmentation fault, just "ERROR 1: Input file sat_gs_de_20180718.nc has no raster bands." (note that the file you attached is not the one mentionned in your gdalwarp invokation) because you need to open one of the subdatasets listed with gdalinfo

What is your gdal version ?

**Comment by rouault** [comment] 2018-09-19 17:31
@rawedler Can you give feedback regarding my above question ?

**Comment by rawedler** [comment] 2018-09-20 06:41
Thank so much for your fast answer. 

I have GDAL 2.2.3, released 2017/11/20 and I have seen, it exists a higher version. I looked around about raster bands, but I can't find a tutorial. My question are: Can I define the raster bands into the header of the netcdf-file? Probably yes. And which parameter must be set? Exists everywhere a netcdf example file, where I can take a look?

**Comment by rouault** [comment] 2018-09-20 19:17
Closing as I can't reproduce and I don't understand the questions (which are not to be asked here)

**Closed by rouault** 2018-09-20 19:17 UTC
Labels: awaiting_feedback
