### ISSUE TITLE
RasterIO() so slow when read netdata? How to speed_up?

### ISSUE THREAD

**Issue by liang-god** [OSGeo/gdal#1693] opened 2019-07-02 03:31 UTC
I build a thread to read an image(JPG),which size 5700*3860.
when the data in LAN, the IO time takes 10seconds
But when I move it  to my computer, just takes 0.5seconds.
  here is the code:

```
               QTime s_time;
                s_time.restart();
		t_mutex->lock();
		CPLErr rr = p_dataSet->RasterIO(GF_Read, p_param[0], p_param[1], p_param[2], p_param[3],
		 t_data, p_param[4], p_param[5], GDT_Byte, 3, t_band, 3, 3 * p_param[4], 1);
	
                t_mutex->unlock();
		QImage` t_image = QImage(t_data, p_param[4], p_param[5], 3 * p_param[4], QImage::Format_RGB888).convertToFormat(QImage::Format_RGB32);
		delete[] p_param;
		
		free(t_data);
		qDebug() << "thread read finished time:" << s_time.elapsed();

```
here is image:
![0880](https://user-images.githubusercontent.com/29827175/60507027-cb1d5e00-9cf9-11e9-8146-b4fc19175dd9.JPG)
and the p_param would be p_param[6] = {3939    11    301    245    300    244}

By the way, there are 1500 images at same directory, and I started 10 threads to read image,because I have 10 dialogs.

**Comment by rouault** [comment] 2019-07-02 10:09
Please attach the image and give the values of the p_param[] array

**Comment by rouault** [comment] 2019-07-02 11:10
doing
```
strace python -c "from osgeo import gdal; ds = gdal.Open('60507027-cb1d5e00-9cf9-11e9-8146-b4fc19175dd9.JPG'); ds.ReadRaster(3939,11,301,245, buf_xsize=300, buf_ysize=244, buf_pixel_space=3, buf_line_space=900, buf_band_space=1)"
```
I don't see an obvious inefficient read pattern. There are 157 reads of 4096 bytes, ie 643 KB to decode the image. So maybe the issue is that reading those small chunks is inefficient on your network. You could try to set the VSI_CACHE=YES configuration option / environment variable to see if it makes a difference

**Comment by liang-god** [comment] 2019-07-02 11:24
> doing
> strace python -c "from osgeo import gdal; ds = gdal.Open('60507027-cb1d5e00-9cf9-11e9-8146-b4fc19175dd9.JPG'); ds.ReadRaster(3939,11,301,245, buf_xsize=300, buf_ysize=244, buf_pixel_space=3, buf_line_space=900, buf_band_space=1)"
> 
> I don't see an obvious inefficient read pattern. There are 157 reads of 4096 bytes, ie 643 KB to decode the image. So maybe the issue is that reading those small chunks is inefficient on your network. You could try to set the VSI_CACHE=YES configuration option / environment variable to see if it makes a difference

NO,It doesn't work!
here is my output:
![image](https://user-images.githubusercontent.com/29827175/60509189-e9398d00-9cfe-11e9-8d7b-8d5ebe1c5d80.png)

**Comment by rouault** [comment] 2019-07-02 11:48
you should start by trying to isolate things, and just doing one read in a thread. And actually do basic stuff like measure the time for fread() to read ~ 640 KB from the file. If reading it in one single time, or in several ones, makes a difference, etc.

**Comment by rouault** [comment] 2020-04-05 17:40
Closing as not actionable

**Closed by rouault** 2020-04-05 17:40 UTC
