### ISSUE TITLE
Transform the pose between the two coordinate systems

### ISSUE THREAD

**Issue by lxr319** [OSGeo/gdal#8266] opened 2023-08-24 08:56 UTC
Hello, I now have a need to convert the pose in the local ENU coordinate system to the projection coordinate system represented by EPSG: code. However, it is found that gdal does not provide access to the corresponding rotation matrix in transformer. In other words, the transformer in gdal can only transform 3D points, right? Please give me a hint.

**Comment by rouault** [comment] 2023-08-24 09:16
Closing as this is a usage question, and not a bug report.

Hint: you'll likely have to use a PROJ pipeline doing the inverse operation of your PCS EPSG:code and chaining it with the "Convert geographic coordinates to topocentric coordinate" example of https://proj.org/en/9.2/operations/conversions/topocentric.html

**Closed by rouault** 2023-08-24 09:16 UTC
