### ISSUE TITLE
Gdalwarp issue when resampling and/or reprojecting

### ISSUE THREAD

**Issue by oskarlin** [OSGeo/gdal#5155] opened 2022-01-24 13:41 UTC
## Expected behavior and actual behavior.

With version GDAL 3.4.1 something very strange happens when reprojecting or resampling TIFF dem files from Norwegian Kartverket. With version 3.3.2 it all works fine.

## Steps to reproduce the problem.

`gdalwarp -r bilinear -s_srs EPSG:25833 -t_srs EPSG:25832 dtm1_33_116_137.tif dtm1_33_116_137_32_ny3.tif`

## Operating system

MacMini M1 

## GDAL version and provenance

GDAL from homebrew

Attached images are from a hillshade made from the different files just to show more clearly the difference in result.
 
![Skärmavbild 2022-01-24 kl  14 29 22](https://user-images.githubusercontent.com/2736990/150793205-ba790ca9-9881-4ebe-a0ff-a6f71a189183.jpeg)
![Skärmavbild 2022-01-24 kl  14 29 33](https://user-images.githubusercontent.com/2736990/150793229-fa2a40d4-0b0d-4995-937d-fee123892603.jpeg)

**Comment by jratike80** [comment] 2022-01-24 14:58
Where could I get a small sample as test data?

**Comment by oskarlin** [comment] 2022-01-24 15:12
https://hoydedata.no/LaserInnsyn/

Go to Download to the left, choose a small area. National elevation model. DTM1. 

<img width="291" alt="Screenshot 2022-01-24 at 16 11 30" src="https://user-images.githubusercontent.com/2736990/150809487-119c30e4-2bc3-4dcf-965e-ec76a7776e95.png">

**Comment by rouault** [comment] 2022-01-24 16:38
@oskarlin I'm wondering if it is not a duplicate of https://github.com/OSGeo/gdal/issues/4754 . Could you try adding ``-wo USE_OPENCL=NO --overwrite`` and see if it makes a difference ?

**Comment by jratike80** [comment] 2022-01-27 07:43
I had a try with GDAL 3.4.0dev (Windows, GDAL from gisinternals.com)

`gdalwarp -r bilinear -s_srs EPSG:25833 -t_srs EPSG:25832 dtm1_33_117_126.tif dtm1_33_117_126_ny.tif`

No problem here.

<img width="136" alt="image" src="https://user-images.githubusercontent.com/1751612/151313053-61b480f0-86c8-4ed9-9426-916bbb4c5546.png">

**Comment by rouault** [comment] 2022-07-21 20:38
closing due to lack of feedback

**Closed by rouault** 2022-07-21 20:38 UTC
Labels: awaiting_feedback
