### ISSUE TITLE
LNK2001	simbolo esterno "class OGRCoordinateTransformation 

### ISSUE THREAD

**Issue by saras82** [OSGeo/gdal#9134] opened 2024-01-25 09:35 UTC
Good morning,
I've recently been using C++. I would like to use the GDAL library to do EPSG coordinate conversion. I installed the library as indicated in the link via conda:https://gdal.org/download.html#development-source.
But when compiling I get the following error: LNK2001	simbolo esterno "class OGRCoordinateTransformation ...

I'm using Visual Studio and I added the 'additional include directories' in the project properties.
How can I solve it? 
Thanks in advance

**Comment by rouault** [comment] 2024-01-25 11:46
This looks like a "basic" issue with linking your project to external library (likely you need to add GDAL as a dependent library in the linking options, in addition to its include directories) and not a bug in GDAL itself. Please find help on general forum on the internet. Closing

**Closed by rouault** 2024-01-25 11:46 UTC
