### ISSUE TITLE
gdalwarp "mode" resampling (fine to coarse) creates raster with pixel values that are not in the input raster

### ISSUE THREAD

**Issue by rakheshd** [OSGeo/gdal#3956] opened 2021-06-09 12:23 UTC
I am trying to resample a **50 m raster to 250 m** raster using **“mode”** algorithm within gdalwarp.
The output raster is created with values which are not in the input raster. Input data pixel values are very high and the datatype is Int32.
Command used is like below.
gdalwarp -r mode -tr 250 250 inputfile outputfile
Input raster has following unique pixel values
[        0 , 302011022, 302011024, 302041041, 302041042, 302041043, 302041044]
Output raster creates raster with unique values as below.
[        0, 302011008, 302041056]
Note that gdal_translate also has the same issue.
I have made a small subset of the data, which I can forward if you want (not able to attach here)
Thanks in advance. Rakhesh Devadas

**Comment by rouault** [comment] 2021-06-09 12:26
Duplicate of https://github.com/OSGeo/gdal/issues/3714

**Closed by rouault** 2021-06-09 12:26 UTC
