### ISSUE TITLE
ogr and osr transormation return a wrong sequence (x,y as y,x) for gdal 3.x 

### ISSUE THREAD

**Issue by pisutnakmuenwai** [OSGeo/gdal#1986] opened 2019-11-06 09:58 UTC
## Expected behavior and actual behavior.
Project x,y point event point.Transform() or transform.TransformPoint()
from UTM Zone47N and 48N to Geographic WGS84  unexpected return
Expected behavior
2.x is correct 
EPSG:32647   POINT (380985 2132685)
EPSG:4326     POINT (97.8673347690614 19.2844025655666)

actual behavior
3.x is wrong return in x, y 
EPSG:32647    POINT (380985 2132685)
EPSG:4326      POINT (19.2844025655666 97.8673347690614)

## Steps to reproduce the problem.

from osgeo import ogr
from osgeo import osr

epsg4326 = osr.SpatialReference(); epsg4326.ImportFromEPSG(4326)
epsg32647 = osr.SpatialReference(); epsg32647.ImportFromEPSG(32647)
trans = osr.CoordinateTransformation(epsg32647,epsg4326)

point = {'x': 380985.0, 'y': 2132685.0}
geom = ogr.CreateGeometryFromWkt('POINT (%d %d)'%(point['x'],point['y']))

print(geom.ExportToWkt())
geom.Transform(trans)
print(geom.ExportToWkt())

## Operating system

Ubuntu 18, OSX  + Anaconda

## GDAL version and provenance

3.0.1 and 3.0.2 both are proved to be wrong
2.7, 2.4, 2.3 is fine

**Comment by rouault** [comment] 2019-11-06 10:13
Duplicate of https://github.com/OSGeo/gdal/issues/1974 and a few other tickets...

**Closed by rouault** 2019-11-06 10:13 UTC
