### ISSUE TITLE
gdalwarp - ERROR 6: Cannot find coordinate operations

### ISSUE THREAD

**Issue by ktheijs** [OSGeo/gdal#1712] opened 2019-07-10 07:09 UTC
gdalwarp.exe fails on this dataset:

> Driver: GTiff/GeoTIFF
Files: D:\dsm.tif
Size is 10018, 9823
Coordinate System is:
LOCAL_CS["Arbitrary (ft)",
    UNIT["foot",0.3048,
        AUTHORITY["EPSG","9002"]]]
Origin = (10896.948270000001000,10362.745840000001000)
Pixel Size = (0.195040000000000,-0.195040000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (   10896.948,   10362.746)
Lower Left  (   10896.948,    8446.868)
Upper Right (   12850.859,   10362.746)
Lower Right (   12850.859,    8446.868)
Center      (   11873.904,    9404.807)
Band 1 Block=10018x1 Type=Float32, ColorInterp=Gray
  NoData Value=-10000

The command parameters are:

`-dstnodata -99999 -wt Float32 -of VRT -multi -overwrite "D:\dsm.tif" "D:\warpedDsm.vrt"`

The error I get is:

> ERROR 6: Cannot find coordinate operations from \`ENGCRS["Arbitrary (ft)",EDATUM[""],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["foot",0.3048,ID["EPSG",9002]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["foot",0.3048,ID["EPSG",9002]]]]' to \`ENGCRS["Arbitrary (ft)",EDATUM[""],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]'

This used to work fine before GDAL 3.0. Any idea why is doesn't work now?

## Operating system

Windows 10 64-bit

## GDAL version and provenance

Stable release from GisInternals: release-1911-x64-gdal-3-0-0-mapserver-7-4-0

**Comment by rouault** [comment] 2019-07-10 10:18
I can't reproduce this with a Linux build with an image with a LOCAL_CS/ENGCRS. Can you try a development build at http://gisinternals.com/development.php instead of the 3-0-0 builds ? If that doesn't make a difference, please attach the image (if that's too big, you might be able to produce a small one with `gdal_translate -srcwin 0 0 1 1 in.tif small.tif`, but check that the problem is reproducable with the small one)

**Comment by rouault** [comment] 2019-07-16 14:43
@ktheijs ping ?

**Comment by ktheijs** [comment] 2019-12-13 09:14
Okay, sorry for the extremely long delay. I am back on this topic now. 

I did some tests with the gdal 3.0.2. 

I take the following dataset:

> C:\OSGeo4W64>gdalinfo D:\LocalDsm.tif
Driver: GTiff/GeoTIFF
Files: D:\LocalDsm.tif
Size is 10018, 9823
Coordinate System is:
ENGCRS["Arbitrary (ft)",
    EDATUM[""],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["foot",0.3048,
                ID["EPSG",9002]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["foot",0.3048,
                ID["EPSG",9002]]]]
Data axis to CRS axis mapping: 1,2
Origin = (10896.948270000000775,10362.745840000001408)
Pixel Size = (0.195040000000000,-0.195040000000000)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_SOFTWARE=pix4dmapper
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (   10896.948,   10362.746)
Lower Left  (   10896.948,    8446.868)
Upper Right (   12850.859,   10362.746)
Lower Right (   12850.859,    8446.868)
Center      (   11873.904,    9404.807)
Band 1 Block=10018x1 Type=Float32, ColorInterp=Gray
  NoData Value=-10000

I do this operation:

>   -dstnodata -99999 -wt Float32 -of VRT -multi -overwrite "D:\LocalDsm.tif" "D:\LocalWarpedDsm.vrt"

And then I get this error:

> ERROR 6: Cannot find coordinate operations from `ENGCRS["Arbitrary (ft)",EDATUM[""],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["foot",0.3048,ID["EPSG",9002]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["foot",0.3048,ID["EPSG",9002]]]]' to `ENGCRS["Arbitrary (ft)",EDATUM[""],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]'

So for some reason it tries to transform from foot to meter.

Also, when I do the translate operation as you said to make it smaller:

> C:\OSGeo4W64>gdal_translate -srcwin 0 0 250 250 D:\LocalDsm.tif D:\LocalSmallerDsm.tif
Input file size is 10018, 9823
ERROR 1: PROJ: proj_get_ellipsoid: CRS has no geodetic CRS
ERROR 1: PROJ: proj_get_ellipsoid: Object is not a CRS or GeodeticReferenceFrame
ERROR 1: PROJ: proj_get_ellipsoid: CRS has no geodetic CRS
ERROR 1: PROJ: proj_get_ellipsoid: Object is not a CRS or GeodeticReferenceFrame
0...10...20...30...40...50...60...70...80...90...100 - done.

The resulting file is this:

> C:\OSGeo4W64>gdalinfo D:\LocalSmallerDsm.tif
Driver: GTiff/GeoTIFF
Files: D:\LocalSmallerDsm.tif
Size is 250, 250
Coordinate System is:
ENGCRS["Arbitrary (ft)",
    EDATUM[""],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
Origin = (10896.948270000000775,10362.745840000001408)
Pixel Size = (0.195040000000000,-0.195040000000000)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_SOFTWARE=pix4dmapper
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (   10896.948,   10362.746)
Lower Left  (   10896.948,   10313.986)
Upper Right (   10945.708,   10362.746)
Lower Right (   10945.708,   10313.986)
Center      (   10921.328,   10338.366)
Band 1 Block=250x8 Type=Float32, ColorInterp=Gray
  NoData Value=-10000

So it also transforms it to meter. Any idea why it does this?

**Comment by rouault** [comment] 2019-12-13 10:08
> please attach the image (if that's too big, you might be able to produce a small one with gdal_translate -srcwin 0 0 1 1 in.tif small.tif, but check that the problem is reproducable with the small one)

**Comment by ktheijs** [comment] 2019-12-13 10:23
That is what I was trying to do, but when I translate it, the unit of the ENGCRS is changed to meter. When I do the same warp operation on this smaller tif, it works fine. I assume because it then just warps it from meter to meter so it doesn't need any coordinate operations. If you want I can send you the original file. (Through wetransfer or something like that.)

**Comment by ktheijs** [comment] 2019-12-13 12:25
I've been testing a bit more and I see that the unit is quickly changed from foot to meter. If I do the following:

> Dataset dataset = Gdal.Open(sourceFileFullName, Access.GA_Update);
    string originalWkt = dataset.GetProjection();
    dataset.SetProjection(originalWkt);
    dataset.Dispose();

This is already enough to change the unit. Note that the originalWkt that I get from dataset.GetProjection() is 'LOCAL_CS["Arbitrary (ft)"]'.

I assume that the this issue and the one with warping have the same underlying cause.

**Comment by rouault** [comment] 2020-04-05 16:21
There has been a fixed done lately regarding LOCAL_CS/ENGCRS and units. Closing assuming it fixes this issue

**Closed by rouault** 2020-04-05 16:21 UTC
Labels: awaiting_feedback

**Comment by arvkonstantin** [comment] 2022-06-28 13:16
Hello, i have the same issue
`ERROR 6: Cannot find coordinate operations from `ENGCRS["unnamed",EDATUM[""],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]' to `EPSG:3857'`
tested with:
GDAL 3.6.0dev-125fafc0ea22262a8c80d86d6b81a3683ee857a5, released 2022/06/25
GDAL 3.3.2, released 2021/09/01
GDAL 3.2.2, released 2021/03/05

**Comment by rouault** [comment] 2022-06-28 13:20
> Hello, i have the same issue
> `ERROR 6: Cannot find coordinate operations from `ENGCRS["unnamed",EDATUM[""],CS[Cartesian,2],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]' to `EPSG:3857'`

that's a different issue. There's no way you can expect reprojection from a LOCAL_CS/ENGCRS to a projected CRS such as EPSG:3857 to work, since the LOCAL_CRS/ENGCRS is a too loosely defined object.
