### ISSUE TITLE
Cmake issues "Unexpected value for SIZEOF_XXXXX" (cross compile/ubuntu -> android)

### ISSUE THREAD

**Issue by vautieri2** [OSGeo/gdal#5406] opened 2022-03-03 17:26 UTC
I have a hunch cmake isn't setting these variables.  If you go into cpl_port.h, you can set these values to what they should be to get around the issue.  Code area is below the error messages I have here.  Again, this is on your main/master/trunk whatever you want to call it.

cpl_port.h:74:2: warning: "Unexpected value for SIZEOF_INT" [-W#warnings]
#warning "Unexpected value for SIZEOF_INT"
 
cpl_port.h:78:2: warning: "Unexpected value for SIZEOF_UNSIGNED_LONG" [-W#warnings]
#warning "Unexpected value for SIZEOF_UNSIGNED_LONG"

cpl_port.h:82:2: warning: "Unexpected value for SIZEOF_VOIDP" [-W#warnings]

as a work around, instead of erroring out, one can manually set them.. till we figure out how to fix.

/* ==================================================================== */
/*      A few sanity checks, mainly to detect problems that sometimes   */
/*      arise with bad configured cross-compilation.                    */
/* ==================================================================== */

#if !defined(SIZEOF_INT) || SIZEOF_INT != 4
#warning "Unexpected value for SIZEOF_INT"
#endif

#if !defined(SIZEOF_UNSIGNED_LONG) || (SIZEOF_UNSIGNED_LONG != 4 && SIZEOF_UNSIGNED_LONG != 8)
#warning "Unexpected value for SIZEOF_UNSIGNED_LONG"
#endif

#if !defined(SIZEOF_VOIDP) || (SIZEOF_VOIDP != 4 && SIZEOF_VOIDP != 8)
#warning "Unexpected value for SIZEOF_VOIDP"
#endif

**Comment by rouault** [comment] 2022-03-08 11:22
I can't reproduce this. I suspect something isn't clean in your build tree, perhaps a mix of autoconf vs CMake builds ?
I'd suggest you retry on a clean configuration after https://github.com/OSGeo/gdal/pull/5426 has been merged.
Or provide a reproducable way (like a Docker based script like done for the new Android cmake-based cross compilation continuous integration setup of https://github.com/rouault/gdal/blob/fix_5403/.github/workflows/android_cmake/start.sh )

**Closed by rouault** 2022-03-08 11:22 UTC
