### ISSUE TITLE
NetCDF CF1.0 coordinates are sometimes not read by gdalinfo (and raster not projected correctly)

### ISSUE THREAD

**Issue by raphidoc** [OSGeo/gdal#10135] opened 2024-06-05 16:11 UTC
### What is the bug?

When creating a NetCDF raster with python, the projected (UTM 19N) coordinates written following the [CF-1.0 conventions](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.0/build/cf-conventions.html) (compatible with the [NetCDF GDAL driver](https://gdal.org/drivers/raster/netcdf.html#georeference)) are sometimes not read/recognized by gdalinfo and therefore not properly projected in QGIS.

The issue seems to be related to the coordinate values themselves. For some values, gdalinfo correctly reads them and projects them in QGIS, while for other values, gdalinfo doesn't recognize them as coordinate variables and there are not projected correctly in QGIS.

### Steps to reproduce the issue

For those values of width and height, gdalinfo correctly read the coordinates

```
width= 8026
height= 7340
```

`gdalinfo` return:

```
Corner Coordinates:
Upper Left  (  541107.000, 5438536.750) ( 68d26'12.76"W, 49d 5'53.90"N)
Lower Left  (  541107.000, 5427526.250) ( 68d26'16.78"W, 48d59'57.35"N)
Upper Right (  553146.000, 5438536.750) ( 68d16'19.08"W, 49d 5'50.58"N)
Lower Right (  553146.000, 5427526.250) ( 68d16'24.29"W, 48d59'54.05"N)
Center      (  547126.500, 5433031.500) ( 68d21'18.23"W, 49d 2'54.08"N)
```

But those values triggered the issue, GDAL doesn't read the coordinates:

```
# width= 7920
# height= 7135
```

For which `gdalinfo` return:

```
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 7135.0)
Upper Right ( 7920.0,    0.0)
Lower Right ( 7920.0, 7135.0)
Center      ( 3960.0, 3567.5)
```

Reproductible example code with and without the issue:

```
import netCDF4
import numpy as np
import pyproj
import rasterio

fpath = '/D/Data/TEST/test_netcdf_cf.nc'
ds = netCDF4.Dataset(fpath, "w", format="NETCDF4")

# Coordinates read by gdalinfo
width= 8026
height= 7340

# Coordinates not read by gdalinfo
width= 7920
height= 7135

# Create an affine transformation with origin over manicouagan peninsula
GT0 = 541107.0# x coordinate of the upper-left corner of the upper-left pixel
GT1 = 1.5 # w-e pixel resolution / pixel width.
GT2 = 0 # row rotation (typically zero).
GT3 = 5438536.5 # y-coordinate of the upper-left corner of the upper-left pixel.
GT4 = 0 # column rotation (typically zero).
GT5 = 1.5 # n-s pixel resolution / pixel height (negative value for a north-up image).

# Setting the pixel size to 1 fix the issue
transform = rasterio.transform.from_origin(west=GT0, north=GT3, xsize=GT1, ysize=GT5)

# using those origin coordinate also fix the bug...
# What's happening here ? somme issue with GDAL who expect a regular grid ?
#transform = rasterio.transform.from_origin(west=541107.25, north=5438536.25, xsize=1.5, ysize=1.5)

x = rasterio.transform.xy(transform, cols=list(range(0, width, 1)), rows=0)[0]
y = rasterio.transform.xy(transform, cols=0, rows=list(range(0, height, 1)))[1]

ds.createDimension('y', height)
ds.createDimension('x', width)
y_var = ds.createVariable('y', 'f4', ('y',))
x_var = ds.createVariable('x', 'f4', ('x',))

y_var[:] = y
x_var[:] = x

# Create the CF grid_mapping
crs = pyproj.CRS.from_epsg(32619)
cf_grid_mapping = crs.to_cf()

proj_var = ds.createVariable('grid_mapping', np.int32, ())

# Add spatial_ref and GeoTransform from GDAL doc
# proj_var.spatial_ref = cf_grid_mapping['crs_wkt']
# proj_var.GeoTransform = f"{GT0} {GT1} {GT2} {GT3} {GT4} {GT5}"

proj_var.crs_wtk = cf_grid_mapping['crs_wkt']
proj_var.semi_major_axis = cf_grid_mapping['semi_major_axis']
proj_var.semi_minor_axis = cf_grid_mapping['semi_minor_axis']
proj_var.inverse_flattening = cf_grid_mapping['inverse_flattening']
proj_var.reference_ellipsoid_name = cf_grid_mapping['reference_ellipsoid_name']
proj_var.longitude_of_prime_meridian = cf_grid_mapping['longitude_of_prime_meridian']
proj_var.prime_meridian_name = cf_grid_mapping['prime_meridian_name']
proj_var.geographic_crs_name = cf_grid_mapping['geographic_crs_name']
proj_var.horizontal_datum_name = cf_grid_mapping['horizontal_datum_name']
proj_var.projected_crs_name = cf_grid_mapping['projected_crs_name']
proj_var.grid_mapping_name = cf_grid_mapping['grid_mapping_name']
proj_var.latitude_of_projection_origin = cf_grid_mapping['latitude_of_projection_origin']
proj_var.longitude_of_central_meridian = cf_grid_mapping['longitude_of_central_meridian']
proj_var.false_easting = cf_grid_mapping['false_easting']
proj_var.false_northing = cf_grid_mapping['false_northing']
proj_var.scale_factor_at_central_meridian = cf_grid_mapping['scale_factor_at_central_meridian']

y_var.units = 'm'
y_var.standard_name = 'projection_y_coordinate'
y_var.long_name = 'y coordinate of projection'
y_var.axis = 'Y'

x_var.units = 'm'
x_var.standard_name = 'projection_x_coordinate'
y_var.long_name = 'x coordinate of projection'
x_var.axis = 'X'

# create band dimension
ds.createDimension('band', 3)
band_var = ds.createVariable('band', 'f4', ('band',), significant_digits=2)

band_var[:] = [350.23, 460.90, 680.7]

band_var.units = 'nm'
band_var.standard_name = 'sensor_band_central_radiation_wavelength'
band_var.axis = 'B'

# Create data variable
Rrs_var = ds.createVariable(
    'Rrs',
    'i4',
    ('band', 'y', 'x',),
    fill_value=21474836,
    compression='zlib',
    complevel=1)

Rrs_var.units = 'sr-1'
Rrs_var.standard_name = 'Rrs'
Rrs_var.long_name = 'Remote sensing reflectance'

Rrs_var.grid_mapping = 'grid_mapping'

RrsData = np.random.random(size=(3, height, width))

print(ds.variables['Rrs'].shape)

ds.variables['Rrs'][0:3, 0:height, 0:width] = RrsData

ds.close()
```

### Versions and provenance

Operating system: Pop!_OS 22.04 LTS
GDAL version: 3.4.1
I'm not sure, but my GDAL version was likely installed with QGIS.

### EDIT

Adding the `spatial_ref` and `GeoTransform` attributes to the grid_mapping variable (see: https://gdal.org/drivers/raster/netcdf.html#georeference) "fixed" the issue. However, there is still this erratic behavior. Should Following the CF1 Convention be enough for GDAL to read the coordinates ?

**Comment by rouault** [comment] 2024-06-05 22:48
It would be helpful if you could also attach the dataset generated by the above script (I assume it will compress well as a zip)

**Comment by raphidoc** [comment] 2024-06-06 12:40
Yes sure. The above script generates two datasets, one which coordinates are properly read by `gdalinfo` one for which there are not. 
The datasets are available here: 
[datasets_bug_coordinates.zip](https://github.com/user-attachments/files/15620697/datasets_bug_coordinates.zip)

**Comment by rouault** [comment] 2024-06-06 16:00
@raphidoc 
if you run with gdalinfo with ``--config CPL_DEBUG ON`` you'll see

GDAL_netCDF: xdim: 7920 dfSpacingBegin: 1.500000 dfSpacingMiddle: 1.500000 dfSpacingLast: 1.500000
GDAL_netCDF: ydim: 7135 dfSpacingBegin: -2.000000 dfSpacingMiddle: -1.000000 dfSpacingLast: -1.000000
GDAL_netCDF: Latitude/Y is not equally spaced (with a 0.05% tolerance). You may set the GDAL_NETCDF_IGNORE_EQUALLY_SPACED_XY_CHECK configuration option to YES to ignore this check

so the y variable isn't regularly spaced. This is confirmed by looking at the value with ncdump: " y = 5438536, 5438534, 5438533, 5438531," ...  The reason is that float hasn't sufficient accuracy to represent faithfully integer values with such a magnitude.
You should use float64 data type instead.

Closing as not a GDAL bug

**Closed by rouault** 2024-06-06 16:00 UTC

**Comment by raphidoc** [comment] 2024-06-06 16:36
Thank you very much, I didn´t knew about `--config CPL_DEBUG ON`!
