### ISSUE TITLE
ChunkAndWarpImage  

### ISSUE THREAD

**Issue by tthh7** [OSGeo/gdal#8205] opened 2023-08-10 09:47 UTC
Here's the situation: I'm using the ChunkAndWarpImage method to resample a raster, and this function utilizes ComputeSourceWindow to calculate a window within the original raster. However, I am already aware of the extent of the valid area within the raster. Therefore, I would like to avoid fetching the entire raster. Nevertheless, when I provide the parameters 0, 0, nDstXsize, nDstYsize to ComputeSourceWindow, it still fetches data from the original raster's (0, 0) position. So, I decided to add an offset from the valid area to the calculated nSrcXoff and nSrcYoff. However, this adjustment results in a portion of data missing after the reprojection and resampling. I would like to inquire about how to modify ComputeSourceWindow to meet this requirement ？

**Comment by rouault** [comment] 2023-08-10 09:51
Closing as duplicate of #8203. Sorry we can't provide support for such custom requests where you modify the code base

**Closed by rouault** 2023-08-10 09:51 UTC
