### ISSUE TITLE
gdal2tiles.py multiprocessor option not working for overview tiles

### ISSUE THREAD

**Issue by Herjar** [OSGeo/gdal#1188] opened 2019-01-09 08:23 UTC
I try to run the command like this: 
`gdal2tiles.py -p raster -r lanczos -z 2-7 --processes=6 -w none example.png outputpath`

It seems to run on all 6 cores when generating the base tiles, but only runs on one core when generating overview tiles.

I am currently using gdal2tiles-multiprocess.py from here: https://github.com/commenthol/gdal2tiles-leaflet

That version uses all cores for base and overview tiles and is much faster. However, I noticed sometimes a tile is not generated when using multiple processors. 

So I wanted to move to the official version, but it is just much slower for me. I tried on RHEL and Ubuntu with the same issue on both. Is it working for anyone else on overview tiles?

**Comment by hugomostar** [comment] 2019-11-08 13:54
same here

**Comment by kordian-kowalski** [comment] 2020-02-25 11:48
+1, For huge datasets (tens of GBs) this is a significant bottleneck and requires workarounds, a single decent multithreaded implementation would be very handy

**Comment by JackCen** [comment] 2020-07-11 00:02
+1 is there any plan to resolve this? I have seen there used to be very old patches (years ago) to improve that, but seems that the change is not introduced in the latest version.

**Comment by alacst** [comment] 2020-07-30 13:25
+1, same here

**Comment by karpatidaniel** [comment] 2020-07-30 13:31
+1 here with the following command used
`gdal2tiles.py --xyz -z 9-20 --processes=6 -e -r lanczos -n -w none ~/output8bit.vrt ~/tiles_upscaled_lanczos/`
Ubuntu 20.04
GDAL 3.1.0, released 2020/05/03

**Comment by MikitaBelikau** [comment] 2021-05-02 09:42
same for me for EC2 instance with Ubuntu and GDAL 3.2

Tried to use gdal2tilesp.py as an alternative, but it failed after hours of execution

**Comment by undefinedSolutions** [comment] 2022-01-30 21:06
If you only need the Tiles and not the "Web viewer options" this could be a better solution for you:
```
time gdal2tiles.py -p mercator -z  0 --processes=24 ./Ortho.tif ./TMS-S1 ; \
time gdal2tiles.py -p mercator -z  1 --processes=24 ./Ortho.tif ./TMS-S1 ; \
...
time gdal2tiles.py -p mercator -z 22 --processes=24 ./Ortho.tif ./TMS-S1 ; \
time gdal2tiles.py -p mercator -z 23 --processes=24 ./Ortho.tif ./TMS-S1
```

If I run -z 0-23 it takes 10:23 minutes, but if I run every zoomLevel after another with `; \` I only need 6:36 minutes on my two Intel Xeon X5680.
But when I use my Notebook with i7-8550U CPU @ 1.80GHz (with `--processes=8`) it takes much longer:
-z 0-23 takes 18:19 minutes and my approach takes 18:36 minutes

Thus, it depends very much on the threads of the CPU, the more, the more likely it is that my approach could be worthwhile.

**Comment by rouault** [comment] 2022-01-30 21:17
This is a duplicate of https://github.com/OSGeo/gdal/issues/4895 that was fixed per PR #5052

**Closed by rouault** 2022-01-30 21:17 UTC
Labels: enhancement

**Comment by Finn-Neo** [comment] 2023-09-07 10:02
I noticed that 3.5.0 version fixes the problem.But I found that the problem still exists: It runs on one core when generating overview tiles. 
I tested it on two gdal versions: 3.5.0&3.7.1.  With pictures of different sizes(78718*32438, 44164*33522), CPUs with different model(i512400f, i710700k).
And I repeated a dozen times, the results are the same.
My code:
```
zoom = [19, 21]
nb_processes = os.cpu_count()
gdal2tiles.generate_tiles(
    input_image,
    output_folder,
    nb_processes=nb_processes,
    zoom=zoom, )
```
Am I not using it correctly? Or is someone having the same problem as me? Looking forward to replying.

**Comment by jratike80** [comment] 2023-09-07 10:26
Do you use the newest script https://github.com/rouault/gdal/blob/master/swig/python/gdal-utils/osgeo_utils/gdal2tiles.py?

**Comment by Finn-Neo** [comment] 2023-09-07 15:29
thanks very much! 
According to the suggestion you provided, I tried to run "python gdal2tiles.py  --..." in cmd.
the result shows that, other things being equal, processing 44164×33522 size image: 257s->130s. processing 78718×32438 size image: 1583s->356s.（No replication experiments have been done, but the data are sufficient to prove）
Thank you for your efforts!!!

In addition,I found that the gdal2tiles.py not similar to the previous gdal2tiles.py, it has not generate_tiles () method, in my work, I need to integrate this function into my code to automatically handle uploaded images, which is:
```
input_image = ...
output_folder = ...
zoom = [19, 21]
nb_processes = os.cpu_count()
gdal2tiles.generate_tiles(
    input_image,
    output_folder,
    nb_processes=nb_processes,
    zoom=zoom, )
```
I found a compromise：
```
import subprocess

cmd = [
    'python',
    '......\\Lib\\site-packages\\osgeo_utils\\gdal2tiles.py',
    '--processes', '12',
    '44331.tif',
    '......\\44331'
]

try:
    subprocess.run(cmd, check=True)
    print("Command executed successfully.")
except subprocess.CalledProcessError as e:
    print("Error executing command:", e)
```
Am I going in the right direction? Is there any other better way？
