### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by BotellaA** [OSGeo/gdal#664] opened 2018-06-01 11:38 UTC
I would like to know if you are planing to support CMake? 
It will be a great feature and will ease a lot integration of GDAL as a third party module.

Thank you for your answer

**Comment by rouault** [comment] 2018-06-01 11:50
Closing as a duplicate of https://trac.osgeo.org/gdal/ticket/7080
Long answer: see above link
Short answer: if GDAL was to be created now, cmake would be the least-worst choice probably, but at this point of its history, the effort/benefit ratio appears to be (too) huge to a number of stake holders

**Closed by rouault** 2018-06-01 11:50 UTC

**Comment by RichardLangFromNZ** [comment] 2018-06-18 00:09
I'm successfully building the GDAL library from a cmake super-project, including cross-compilation for an ARM embedded linux target, using the cmake ExternalProject_Add() command.  If you would like a copy of my script for reference let me know at r_e_lang@hotmail.com
