### ISSUE TITLE
Document how to add arbitrary headers to HTTP(S) WMS/WMTS requests

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#2527] opened 2020-05-13 23:43 UTC
On frmt_wmts.html we see
```
<Referer>http://example.foo/</Referer>
    HTTP Referer string. Some servers might require it (optional).
```
Indeed they might need any amount of arbitrary HTTP(S) headers added,
e.g., cookies. So do allow/mention how to do that, like wget -H|--header.
Same problem with frmt_wms.html also.

Or there mention "It is not possible to add arbitrary headers other than Referer... at this time."

**Comment by rouault** [comment] 2020-05-14 11:50
Duplicate of https://github.com/OSGeo/gdal/issues/2052

**Closed by rouault** 2020-05-14 11:50 UTC
