### ISSUE TITLE
Issue with Mysql import

### ISSUE THREAD

**Issue by JpatOsaure** [OSGeo/gdal#899] opened 2018-09-06 08:39 UTC
Hello,
I have installed the last version of MySQL (V8)
The geometry function without "ST_" don't work anymore

I bypass the probleme by creating a function call GeometryFromText that call ST_GeometryFromText

Thanks a lot for all you do !
Regards

## Expected behavior and actual behavior.
I was doing this 
ogr2ogr -f "MySQL" MYSQL:"dbName,host=localhost,user=root,port=3306" -nln "tableName" -a_srs "EPSG:4326" shpName.shp -lco ENGINE=MyISAM

Error : function GeometryFromText doesn't exists

## GDAL version and provenance
GDAL package with QGis 3.2.2

**Comment by rouault** [comment] 2018-09-06 08:42
This is a duplicate of #782. Will be finxed in GDAL 2.3.2

**Closed by rouault** 2018-09-06 08:42 UTC
Labels: duplicate

**Comment by JpatOsaure** [comment] 2018-09-06 08:52
Thanks a lot Evan
Sorry for the duplicate
Jean-Philippe
