### ISSUE TITLE
.Net Core and .Net Standard is not compatible

### ISSUE THREAD

**Issue by MouthOfMadness** [OSGeo/gdal#1435] opened 2019-04-09 16:55 UTC
## Expected behavior and actual behavior.

I'm trying to use the Nuspec package GDAL.NET or GDAL.NET.Core in my .Net Core Web Api projects and I'm getting incompatibility errors.

Expected behavior, GDAL.NET.Core should be compatible with .Net Core or .Net Standard projects.

Actual behavior, GDAL.NET.Core imcompatible because of .NetFramework version v4.6.1

## Steps to reproduce the problem.

Create either a .Net Core (2.2) or a .Net Standard (2.) web API; include either GDAL.NET.Core or GDAL.NET (I've tried all 4 permutations).

Notice the compatibility error in the attached images.
![standard](https://user-images.githubusercontent.com/29233402/55819228-eb080180-5abd-11e9-862c-1ee51bb9bfa5.JPG)

![core](https://user-images.githubusercontent.com/29233402/55819264-083cd000-5abe-11e9-98d6-017498fb7ef4.JPG)

## Operating system

Windows 10

## GDAL version and provenance

Both versions are 2.3.1

**Comment by rouault** [comment] 2019-04-09 17:49
Seems to be a duplicate of #1368, right ?

**Comment by MouthOfMadness** [comment] 2019-04-09 18:23
Yes, it’s very close.

If you convert to .Net Standard, both .Net Core and .Net Framework could reference it.

**Comment by MouthOfMadness** [comment] 2019-04-09 18:26
If you added some dependencies, it would prohibit installing on incompatible project types.

Example:

[cid:image001.png@01D4EED7.C24BE4C0]

**Comment by rouault** [comment] 2019-04-09 18:41
CC @szekerest

**Comment by szekerest** [comment] 2019-04-09 20:29
@MouthOfMadness The referred nuget doesn't support .Net core or .Net standard. You might want to use this one https://www.nuget.org/packages/Gdal.Core/2.3.0-beta-023 until the GDAL build set-up doesn't support that officially, which is under development (within the scope of #1368)

**Comment by MouthOfMadness** [comment] 2019-04-09 22:08
I took a different direction by downloading the C++ source and successfully building it.

However, when I use ogr2ogr, translating a geojson file to kml seems to work, but converting the kml file to back to geojson (the reverse operation).  I’ve tested the converted KML file in google earth successfully.

Ogr2ogr spits out the following error <snipped for brevity>:

D:\1bin\apps>ogr2ogr -f "GeoJSON" jim2.geojson john.kml
FAILURE:
Unable to open datasource `john.kml' with the following drivers.
  -> `PCIDSK'
  -> `PDF'
  -> `DB2ODBC'
  -> `ESRI Shapefile'
  -> `MapInfo File'
  -> `UK .NTF'
  -> `OGR_SDTS'
  -> `S57'
  -> `DGN'
  -> `OGR_VRT'
  -> `REC'
  -> `Memory'
  -> `BNA'
  -> `CSV'
  -> `GML'
  -> `GPX'
  -> `KML'
  -> `GeoJSON'
  -> `GeoJSONSeq'
  -> `ESRIJSON'

**Comment by MouthOfMadness** [comment] 2019-04-10 16:28
Using the nuget package, I get a p/invoke error:

When I trace through the inner exceptions, it comes down to this error:

Unable to load DLL 'ogr_wrap' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)




[cid:image002.png@01D4EF90.78DDADF0]

[cid:image001.png@01D4EF90.0E541EB0]

**Comment by bertt** [comment] 2019-11-18 11:37
see  https://github.com/bertt/GdalOnNetCoreSample for a working sample .NET Core and GDAL on Linux/Windows

**Comment by runette** [comment] 2022-01-19 10:38
@rouault @szekerest - given the conversation in #1368 and that the legacy build scripts do now support NETStandard2.1 and NETCore AND given the work on the CMAKE scri[pts in #5046 and that the CMAKE scripts support NET5 and lower :

I propose that this issue should be closed and any further conversation should be addressed to the CMAKE build scripts (#5046) as the solution going forward.

**Comment by rouault** [comment] 2022-01-19 10:43
> I propose that this issue should be closed and any further conversation should be addressed to the CMAKE build scripts (#5046) as the solution going forward.

fully agreed.

**Closed by rouault** 2022-01-19 10:43 UTC
Labels: csharp bindings
