### ISSUE TITLE
PGDump: warning about layer creation options ignored (existing layer)

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#755] opened 2018-07-14 02:29 UTC
## Expected behavior and actual behavior.
Since a blank PGDump file is written, OGR can't even know if a layer is existing already. Also, the default setting overwrites existing tables by removing it first.

After aprox. 70%, this warning appears:
```
Warning 1: Layer creation options ignored since an existing layer is
         being appended to.
```

The problem does NOT appear if `-lco SRID=25832` isn't specified. The dataset is definitely in EPSG:25832.

## Steps to reproduce the problem.
```
ogr2ogr -progress --config PG_USE_COPY YES -f PGDump import.sql nyfile.gpkg -select "myid, somevars" -lco SRID=25832 -nln newlayername
```

## Operating system
Windows 7 64-bit, Windows 10 64 bit, Debian Linux 9 64 bit

## GDAL version and provenance
GDAL 2.3.1, released 2018/06/22

**Comment by rouault** [comment] 2018-07-14 09:03
I can't reproduce
```
$ ogr2ogr -progress --config PG_USE_COPY YES -f PGDump import.sql poly.gpkg -select "eas_id" -lco SRID=25832 -nln newlayername
0...10...20...30...40...50...60...70...80...90...100 - done.
```

**Comment by rouault** [comment] 2018-07-30 15:12
Wondering if it is specific to your input dataset as I can't reproduce. Could you attach yours ?

**Comment by tobwen** [comment] 2018-08-01 19:42
Oh sorry, I'll do as soon as possible. Having some trouble right now.

**Comment by swiss-knight** [comment] 2020-04-02 23:01
I encountered some same error when trying to dump an ESRI Shapefile into a PostGIS database:    

`ogr2ogr -lco OVERWRITE=yes -f "PostgreSQL" PG:"host=localhost user=username dbname=my_database" -a_srs EPSG:4326 "${basedir}/my_shapefile_lin.shp" -nln data_schema.vector_lines -nlt PROMOTE_TO_MULTI`    

And actually, data are being append to the database table, they are not getting updated as I would expect. (In addition, I have the constraint that I want to keep some views linked to this table alive).

**Comment by rouault** [comment] 2020-04-03 08:27
> I encountered some same error

No. Your issue is related to the PostgreSQL driver, wheras this ticket is about PGDump. Closing that one anyway as it is stalled.

@swiss-knight  Not completely sure about what you want to do, but https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/samples/ogrupdate.py could potentially be helpful

**Closed by rouault** 2020-04-03 08:27 UTC
Labels: awaiting_feedback
