### ISSUE TITLE
GetPoints on Polygon Geometry causing: Python error: none_dealloc: deallocating None: bug likely caused by a refcount error in a C extension Python runtime state: initialized

### ISSUE THREAD

**Issue by makingglitches** [OSGeo/gdal#8945] opened 2023-12-09 17:14 UTC
## Expected behavior and actual behavior.

I would expect that when you call the GetPoints() method of a the ogr.Geometry class, and it was either empty or contained a subclass of "Linearring" that it would either throw you an empty collection or the contained classes point data, as when someone works with a type "Polygon" they are expecting the polygon data if they call getpoints. multipolygon you might simply expect a collection of collections.

Instead what is happening in the python lib bindings, is its causing a low level c error and causing Python to bomb with no ability to catch an exception even. Yes yes careful coding blah blah, the behavior still kind of does not make sense logically.

## Steps to reproduce the problem.

```
polygon:ogr.Geometry  = feature.GetGeometryRef()
linearring:ogr.Geometry = polygon.GetGeometryRef(0)

# this is what throws the error
nonexistent_points = polygon.GetPoints()

# this is what works
encapsulate_classes_points = linearring.GetPoints()
```

## Operating system

Fedora 38

## GDAL version and provenance

3.6.4

**Comment by rouault** [comment] 2023-12-09 18:00
I couldn't reproduce the "Python error: none_dealloc: deallocating None: bug likely caused by a refcount error in a C extension " error on my system, but I spotted something wrong in the code that likely explains it, and this should be fixed per https://github.com/OSGeo/gdal/pull/8946

As per returning "nice" geometry types, this isn't really in the philosophy of the bindings which stick to the OGR C API that has a single Geometry class. Python GetPoints() directly maps to C OGR_G_GetPoints(): https://gdal.org/doxygen/ogr__api_8h.html#a6c22d91b27d7a42c225a7dfde28f09c4
Several possiblities:
- use the Geometry.ExportToJson() method which returns a GeoJSON dict
- use Shapely (https://shapely.readthedocs.io/en/stable/geometry.html),  after exporting OGR geometry to WKB with the ExportToWkb() method and import them in shapely with https://shapely.readthedocs.io/en/stable/reference/shapely.from_wkb.html#shapely.from_wkb
- use Fiona which has a also a GeoJSON-like representation of geometries: https://fiona.readthedocs.io/en/stable/manual.html#feature-geometry

**Closed** 2023-12-09 22:47 UTC

**Comment by makingglitches** [comment] 2023-12-20 00:51
Danke
