### ISSUE TITLE
ComputeStatistics hangs for .sid files

### ISSUE THREAD

**Issue by gktval** [OSGeo/gdal#7098] opened 2023-01-19 13:52 UTC
ComputingStatistics for .sid files hangs, even after 10 minutes of processing.

The code is in c#. So this is using the c# bindings.
```
public void ComputeStatistics(string fileName)
{
    Dataset DS = GDAL.Open(fileName, Access.GA_Update);
    int RCount = DS.RasterCount;

    for (int X = 1; X <= DS.RasterCount; X++)
    {
        Band band = DS.GetRasterBand(X);
        float MinVal, MaxVal, MeanVal, StdDevVal;

        // Get the Min and Max Values
        band.ComputeStatistics(false, ref MinVal, ref MaxVal, ref MeanVal, ref StdDevVal, null, null);
    }
}
```

## Operating system

Windows 11 64 bit

## GDAL version and provenance

Gdal 3.5.2 with c# bindings

**Comment by rouault** [comment] 2023-01-19 13:59
Can you also reproduce with "gdalinfo -stats your.sid" ?
What is the size in megabytes of the .sid file, and its dimensions in pixels ?

**Comment by gktval** [comment] 2023-01-19 16:14
I tested with the QGIS Gdal. "gdalinfo -stats your.sid"
With gdal version 3.0.4 it computes statistics right away.
With gdal version 3.6.1 it says that the sid is not supported. 
So I am not sure... 

The sid file is 500Mb. 

In my c# bindings, using gdal 2.4.4, it computes the statistics right away.
In gdal c# binding 3.5.2 in did finally run, but it took 15 minutes for a single band.

**Comment by rouault** [comment] 2023-01-19 16:23
> With gdal version 3.6.1 it says that the sid is not supported.

you should use the same version (3.5.2) as the one with the gdal c# bindings as MrSID support is optional and your 3.6.1 build likely lacks it

> In gdal c# binding 3.5.2 in did finally run, but it took 15 minutes for a single band.

We'd need to have access to the .sid file to investigate

**Comment by gktval** [comment] 2023-01-19 16:57
With gdal 3.5.2 binaries in QGIS, I am unsure how to add support for sid files. I tried adding the plugins folder and also the gdal-MRSid.dll, but it says it is still unsupported. I apologize for not being able to test it. Below is a link to the sid file

https://www.dropbox.com/s/7z7m6zzs5afld8t/Norman%20NAIP%202017-Big.zip?dl=0

**Comment by rouault** [comment] 2023-01-19 21:50
I've tried with GDAL 2.4.4 and computing exact statistics is slow too. Which is totally expected given the size of the file.
You should probably change the first argument of ComputeStatistics() to true to get approximate statistics

**Comment by gktval** [comment] 2023-01-19 23:51
Thanks for testing. I had previously always had the approximation set to 'false' because it was on a user button to manually compute them. I have change approximate to true since then. I was finally able to get "gdalinfo -stats your.sid" to work after a changing environmental variables and a few restarts of the computer. It does run quite slowly when I do that. 

I double checked and compiled my older version of the software with 2.4.4. it does indeed run with approximate set to false. It computes statistics very quickly. So maybe it was a bug that it was actually doing it differently in that c# binding.

**Comment by rouault** [comment] 2023-01-19 23:55
I'm not sure why you are seeing this. But I don't think we can do much, since I cannot reproduce the issue. Hence closing

**Closed by rouault** 2023-01-19 23:55 UTC
