### ISSUE TITLE
Poppler 20.08 brokes build phase for bad octal convertion

### ISSUE THREAD

**Issue by iadegesso** [OSGeo/gdal#2829] opened 2020-08-04 15:26 UTC
Hi,
in my Gentoo I just upgraded to Poppler 20.08 and now I cannot build any version of gdal since **POPPLER_MINOR_VERSION** is automatically converted from decimal to octal giving me the following error while building _pdfdataset.cpp_:

```
<command-line>: error: invalid digit "8" in octal constant
<command-line>: error: invalid digit "8" in octal constant
<command-line>: error: invalid digit "8" in octal constant
pdfio.h:47:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
   47 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 58
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfio.h:54:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
   54 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 69
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfio.h:56:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
   56 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 71
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfio.h:85:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
   85 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 83
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:133:37: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
  133 | #if !(POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 58)
      |                                     ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:209:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
  209 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 82
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:273:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
  273 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 82
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:2460:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 2460 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 58
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:2766:37: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 2766 | #if !(POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 85)
      |                                     ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:2771:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 2771 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 71
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:3634:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 3634 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 69
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:3646:36: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 3646 | #if (POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 72)
      |                                    ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:3676:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 3676 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 69
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:4263:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 4263 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 58
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:4298:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 4298 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 85
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:4309:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 4309 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 83
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:4334:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 4334 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 58
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:5031:36: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 5031 | #if (POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 72)
      |                                    ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:5051:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 5051 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 58
      |                                   ^~~~~~~~~~~~~~~~~~~~~
<command-line>: error: invalid digit "8" in octal constant
pdfdataset.cpp:5058:37: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
 5058 | #if !(POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 58)
```

Iade

**Comment by rouault** [comment] 2020-08-04 16:17
Duplicate of #2823 fixed yesterday

**Closed by rouault** 2020-08-04 16:17 UTC
