### ISSUE TITLE
Python releases should include the required binaries as an extra

### ISSUE THREAD

**Issue by felix-ht** [OSGeo/gdal#6162] opened 2022-08-05 11:48 UTC
Installing gdal for python is quite the pain. The reason for this is that only the version that has its binaries installed by some other means can be used.
As pip is not aware of this special dependency the normal flow of how to install packages does not apply to gdal. This is a big pain for new users and a significant one for experienced users (that want to use a specific version of gdal).

My suggestion is that one can install non python gdal (binaries) as an [extra](https://peps.python.org/pep-0508/#extras).

With this one could just do `pip install gdal[binaries]`

This as a couple of advantages:
- without the extra everything stays the same
- for all futures versions supporting this, installing the newest gdal version  (for python) on any system will be trivial
- super easy pip install

To enable this the gdal binaries/source code would have to be added to pypi in a new package

**Comment by rouault** [comment] 2022-08-05 16:06
Providing binaries for GDAL through pip is a tough topic. Already discussed in https://github.com/OSGeo/gdal/issues/3060, and thus closing this issue as a duplicate of it.  My own take is that Conda is better equipped than the pip ecosystem for GDAL

**Closed by rouault** 2022-08-05 16:06 UTC
