### ISSUE TITLE
Gdalwarp + GPKG: Garbled tiles outside data area

### ISSUE THREAD

**Issue by matsamentet** [OSGeo/gdal#2325] opened 2020-03-19 07:30 UTC
## Expected behavior and actual behavior.

I'm attempting to create a single GeoPackage from a small number of GeoTIFFs using Gdalwarp. In the resulting file, there are apparently garbled copies of tiles spread around outside the data area (but sometimes also on top of actual data).

The TIFFs I used can be downloaded at https://files.teleplan.no/sharing/YmRf68k81

![N1000_grabled_tiles](https://user-images.githubusercontent.com/22658674/77040990-54c0a900-69b9-11ea-97d4-eb2babfb0d5c.PNG)

## Steps to reproduce the problem.

`gdalwarp -of GPKG -srcnodata "255 255 252" -wo SKIP_NOSOURCE=NO -multi -co TILE_FORMAT=PNG8 -dstalpha \*.tif N1000.gpkg`

## Operating system

Windows 10 build 17134

## GDAL version and provenance

3.0.4 from GISInternals, x64 MSVC2015

**Comment by rouault** [comment] 2020-03-19 14:38
Can you delete the target file (or use "-overwrite") and add "--debug on" (2 dash signs) to your gdalwarp command line and report the value that is displayed on the line starting with "GDAL: GDAL_CACHEMAX ="

**Comment by matsamentet** [comment] 2020-03-19 15:10
That line is
`GDAL: GDAL_CACHEMAX = 1631 MB`

I used --config CPL_LOG as well, incase there is something useful there.
[log.log](https://github.com/OSGeo/gdal/files/4355271/log.log)

**Comment by rouault** [comment] 2020-03-25 17:09
https://files.teleplan.no/sharing/YmRf68k81 doesn't respond for me

**Comment by matsamentet** [comment] 2020-03-26 14:13
I had my IT department open the server to clients from France (I assume you work from there), so it should work now.

**Comment by rouault** [comment] 2020-03-26 17:26
I can reproduce the issue. It is known (at least to me because I'm the culprit for having written it :-)) that the write side of the GPKG driver is rather fragile, particularly in situations of repeated writes of the same tile, as done in your scenario. Not sure I'll investigate more to be honest. It might also be due to specifically using TILE_FORMAT=PNG8 / paletted output, but it might be a more general issue with complex interaction between GDAL generic block cache mechanism and specific caches of the GPKG driver.

The workaround I can give is to wrap first to GeoTIFF RGB, and then translate to GPKG;
```
gdalwarp  -srcnodata "255 255 252" -wo SKIP_NOSOURCE=NO -multi   -dstalpha N1000/*.tif tmp.tif -overwrite -co tiled=yes -co compress=deflate
gdal_translate tmp.tif out.gpkg  -co TILE_FORMAT=PNG8
```
The output is just fine.

You may also try to remove -wo SKIP_NOSOURCE=NO. It shouldn't be necessary (and could possibly help for direct wrapping to GPKG)

**Comment by matsamentet** [comment] 2020-05-06 08:06
Sorry for the late reply to this. 
I should have mentioned that the command used in the original post works perfectly in GDAL 2.4.4.

**Comment by rouault** [comment] 2020-05-06 13:19
@matsamentet The information that 2.4.4 worked was important and enabled me to find the regression. I've now pushed a fix

**Closed by rouault** 2020-05-06 13:19 UTC
