### ISSUE TITLE
Bug with GDAL and the Krovak map projection (could be PROJ4).

### ISSUE THREAD

**Issue by arenol** [OSGeo/gdal#1336] opened 2019-03-02 20:24 UTC
## Description
I'm making a map of Norway using the Krovak map projection, a projection suitable for Banana-shaped countries like Czechoslovakia and Norway.  I have some shape files projected using ArcGIS, and now I need to update the map, and I'm trying to use GDAL and QGIS to do the job (have GDAL 2.3).

Running **gdalsrsinfo** on a .prj-file from the old data in the target projection, reveals the following output:

> PROJ.4 : +proj=krovak +lat_0=55 +lon_0=38 +alpha=0 +k=1 +x_0=15200000 +y_0=-14700000 +datum=WGS84 +units=m +no_defs 
 OGC WKT :
 PROJCS["NorwegianKrovak",
    GEOGCS["GCS_WGS_1984",
        DATUM["WGS_1984",
            SPHEROID["WGS_84",6378137.0,298.257223563]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.0174532925199433]],
    PROJECTION["Krovak"],
    PARAMETER["False_Easting",15200000.0],
    PARAMETER["False_Northing",-14700000.0],
    PARAMETER["Pseudo_Standard_Parallel_1",74.0],
    PARAMETER["Scale_Factor",1.0],
    PARAMETER["Azimuth",0.0],
    PARAMETER["Longitude_Of_Center",38.0],
    PARAMETER["Latitude_Of_Center",55.0],
    PARAMETER["X_Scale",-1.0],
    PARAMETER["Y_Scale",1.0],
    PARAMETER["XY_Plane_Rotation",115.0],
    UNIT["Meter",1.0]]

However, using the PROJ-string above to project the updated data using QGIS or **ogr2ogr**, results in a map that is mirrored and rotated and also have other distortions.  So something is definitely wrong.

See result here: https://www.dropbox.com/s/hog9scl4uqj9qf3/krovak_problem.png?dl=0

## Steps to reproduce the problem.

You need sample files to reproduce this. Will provide this upon request.

## Operating system

MacOS Mojave 10.14.1

## GDAL version and provenance
2.3 (http://www.kyngchaos.com)

**Comment by rouault** [comment] 2019-03-10 09:56
The mapping done from the ESRI WKT to the PROJ string is probably wrong. You may need to override it by adding a +axis=swu string to it. But the issue is more fundamental than this. Currently PROJ only supports pseudo_standard_parallel_1 == 78.5 and azimuth == 30.28813972222222 which are hardcoded values for the Czechoslovakia Krovak. Could you file an issue in https://github.com/OSGeo/proj.4/ about that ?

**Comment by rouault** [comment] 2024-04-18 17:57
closing as a PROJ issue, not a GDAL one. https://github.com/OSGeo/PROJ/issues/3907 might be related to that

**Closed by rouault** 2024-04-18 17:57 UTC
