### ISSUE TITLE
DIMAP based drivers miss some useful geometric values

### ISSUE THREAD

**Issue by remicres** [OSGeo/gdal#6343] opened 2022-09-12 10:51 UTC
## Expected behavior and actual behavior.

I believe that the Spot and Pleiades metadata drivers miss some useful properties (like sun and viewing angles).
`gdalinfo` should be able to display these MDs, and a DIMAP product converted into, say a geotiff, should expose these MDs.

## Steps to reproduce the problem.

`gdalinfo /path/to/dimap/PROD_.../VOL_.../IMG_.../DIM_SPOT6_..._1.XML` does not show the following metadata properties:
| Name | Path |
| ---- | ---- |
| Azimuth angle | Geometric_Data.Use_Area.Located_Geometric_Values.Acquisition_Angles.AZIMUTH_ANGLE |
| Viewing angle | Geometric_Data.Use_Area.Located_Geometric_Values.Acquisition_Angles.VIEWING_ANGLE |
| Viewing angle across track | Geometric_Data.Use_Area.Located_Geometric_Values.Acquisition_Angles.VIEWING_ANGLE_ACROSS_TRACK |
| Viewing angle along track | Geometric_Data.Use_Area.Located_Geometric_Values.Acquisition_Angles.VIEWING_ANGLE_ALONG_TRACK |
| Indicence angle | Geometric_Data.Use_Area.Located_Geometric_Values.Acquisition_Angles.INCIDENCE_ANGLE |
| Indicence angle across track | Geometric_Data.Use_Area.Located_Geometric_Values.Acquisition_Angles.INCIDENCE_ANGLE_ACROSS_TRACK |
| Indicence angle along track | Geometric_Data.Use_Area.Located_Geometric_Values.Acquisition_Angles.INCIDENCE_ANGLE_ALONG_TRACK |
| Sun azimuth | Geometric_Data.Use_Area.Located_Geometric_Values.Solar_Incidences.SUN_AZIMUTH |
| Sun elevation | Geometric_Data.Use_Area.Located_Geometric_Values.Solar_Incidences.SUN_ELEVATION |

There are several occurrences of the geometric data, but maybe adding the values for the central ground point could be useful for many users/developers?

## Operating system

Ubuntu 20.04

## GDAL version and provenance

GDAL 3.4.2, released 2022/03/08 compiled from sources

**Comment by rouault** [comment] 2022-09-14 09:03
I believe this is a duplicate of #6047 that has been fixed in GDAL 3.5.2
Now, you get things like:
```
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Acquisition_Angles.AZIMUTH_ANGLE=267.669893351
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Acquisition_Angles.INCIDENCE_ANGLE=27.016047445
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Acquisition_Angles.INCIDENCE_ANGLE_ACROSS_TRACK=-27.0015829985
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Acquisition_Angles.INCIDENCE_ANGLE_ALONG_TRACK=2.15845653667
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Acquisition_Angles.VIEWING_ANGLE=24.1441307649
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Acquisition_Angles.VIEWING_ANGLE_ACROSS_TRACK=23.1246560499
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Acquisition_Angles.VIEWING_ANGLE_ALONG_TRACK=-7.75518264031
  Geometric_Data.Use_Area.Located_Geometric_Values_1.COL=1
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Ground_Sample_Distance.GSD_ACROSS_TRACK=10.249109517
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Ground_Sample_Distance.GSD_ALONG_TRACK=10.0664753577
  Geometric_Data.Use_Area.Located_Geometric_Values_1.LOCATION_TYPE=TopLeft
  Geometric_Data.Use_Area.Located_Geometric_Values_1.ROW=1
  Geometric_Data.Use_Area.Located_Geometric_Values_1.SATELLITE_ALTITUDE=702128.924492
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Solar_Incidences.SUN_AZIMUTH=160.831368686
  Geometric_Data.Use_Area.Located_Geometric_Values_1.Solar_Incidences.SUN_ELEVATION=31.8037546126
  Geometric_Data.Use_Area.Located_Geometric_Values_1.TIME=2015-11-22T11:01:12.826000Z
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Acquisition_Angles.AZIMUTH_ANGLE=268.076181717
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Acquisition_Angles.INCIDENCE_ANGLE=29.7422565546
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Acquisition_Angles.INCIDENCE_ANGLE_ACROSS_TRACK=-29.729975506
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Acquisition_Angles.INCIDENCE_ANGLE_ALONG_TRACK=1.54692719873
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Acquisition_Angles.VIEWING_ANGLE=26.527765994
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Acquisition_Angles.VIEWING_ANGLE_ACROSS_TRACK=25.4587966098
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Acquisition_Angles.VIEWING_ANGLE_ALONG_TRACK=-8.5613582944
  Geometric_Data.Use_Area.Located_Geometric_Values_2.COL=4827
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Ground_Sample_Distance.GSD_ACROSS_TRACK=10.8707597794
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Ground_Sample_Distance.GSD_ALONG_TRACK=10.0997761488
  Geometric_Data.Use_Area.Located_Geometric_Values_2.LOCATION_TYPE=TopCenter
  Geometric_Data.Use_Area.Located_Geometric_Values_2.ROW=1
  Geometric_Data.Use_Area.Located_Geometric_Values_2.SATELLITE_ALTITUDE=702129.048663
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Solar_Incidences.SUN_AZIMUTH=161.286333979
  Geometric_Data.Use_Area.Located_Geometric_Values_2.Solar_Incidences.SUN_ELEVATION=31.9105754472
  Geometric_Data.Use_Area.Located_Geometric_Values_2.TIME=2015-11-22T11:01:12.815000Z
```

**Comment by rouault** [comment] 2022-09-14 09:09
ah, actually my above comment was when reading the .TIF files directly, not through the DIMAP driver

**Comment by tbonfort** [comment] 2022-09-14 09:10
@rouault do these surface up to the dataset metadatas? I could not see them anywhere

**Comment by rouault** [comment] 2022-09-14 09:15
> do these surface up to the dataset metadatas? I could not see them anywhere

e.g
```
$ gdalinfo  ~/gdal/data/spot7/IMG_SPOT7_MS_001_A/IMG_SPOT7_MS_201511221101122_SEN_1_R1C1.TIF -mdd IMD | grep Geometric_Data.Use_Area.Located_Geometric_Values_1.Acquisition_Angles.AZIMUTH_ANGLE
```

**Closed** 2022-09-14 12:03 UTC
Labels: enhancement
