### ISSUE TITLE
Image dithering when transforming vector PDF to TIFF in GDAL 3.9.1

### ISSUE THREAD

**Issue by cxcandid** [OSGeo/gdal#10595] opened 2024-08-13 14:30 UTC
### What is the bug?

When  I load a vector PDF in QGIS 3.38.1 (Windows 10 - GDAL 3.9.1), the resulting image looks like it has been dithered. The same happens when I use `gdal_translate` to convert the PDF.
![GDAL_3 9 1](https://github.com/user-attachments/assets/69c6ff81-1e00-4d05-a466-ff3bb9bb0a5a)

With QGIS 3.30.1 (GDAL 3.6.4) there seems to be no image dithering.
![GDAL_3 6 4](https://github.com/user-attachments/assets/f13da8df-10c5-40e7-b260-202341dd00b1)

Is there any setting to disable this kind of dithering, or do I face a bug here?

The original PDF for testing purposes: 
[test.pdf](https://github.com/user-attachments/files/16601023/test.pdf)

### Steps to reproduce the issue

Drag & Drop PDF in QGIS 3.38.1

### Versions and provenance

Windows 10, GDAL 3.9.1

**Comment by rouault** [comment] 2024-08-13 21:15
I don't reproduce image dithering on Linux with gdal_translate, using either Poppler 22.02 or 24.04

**Comment by agiudiceandrea** [comment] 2024-08-17 06:10
I can confirm the issue using GDAL/OGR 3.9.1 on Windows 10 from OSGeo4W.
`gdal_translate test.pdf test.tif` outputs:
![image](https://github.com/user-attachments/assets/bda4d60b-8e57-4a37-81eb-b176a572a210)
(test,tif in [test.zip](https://github.com/user-attachments/files/16643649/test.zip))
(test_3.9.1.tif in [test_3.9.1.tif.zip](https://github.com/user-attachments/files/16643690/test_3.9.1.tif.zip))

while using GDAL/OGR 3.8.4 on the same system it outputs:
![image](https://github.com/user-attachments/assets/9513e774-754e-437c-be48-e8311bc69f81)
(test_3.8.4.tif in [test_3.8.4.tif.zip](https://github.com/user-attachments/files/16643679/test_3.8.4.tif.zip))

**Comment by rouault** [comment] 2024-08-17 06:41
@agiudiceandrea Do you have a Windows conda-forge environment at hand ? It would be interesting to try the "libgdal-pdf" package and check

**Comment by agiudiceandrea** [comment] 2024-08-17 07:50
> Do you have a Windows conda-forge environment at hand ?

@rouault, not for now. Anyway I've also checked GDAL/OGR 3.8.5 from OSGeo4W and it also shows the same issue.
I guess the issue may be due to some libraries / building options change between GDAL/OGR 3.8.4 and 3.8.5 in OSGeo4W: https://lists.osgeo.org/pipermail/qgis-developer/2024-April/066691.html

**Comment by agiudiceandrea** [comment] 2024-08-17 08:31
@rouault, the issue doesn't occur using gdal 3.9.1 with libgdal-pdf from conda-forge on Windows 10.

**Comment by agiudiceandrea** [comment] 2024-08-17 11:13
The issue is reproducible just using the poppler tool `pdftoppm -tiff test.pdf test`: it occurs using poppler 24.04.0 (shipped by OSGeo4W since GDAL/OGR 3.8.5) while it doesn't occur using poppler 23.07.0 (shipped by OSGeo4W until GDAL/OGR 3.8.4).
So it definitely looks like not a GDAL issue.

**Comment by rouault** [comment] 2024-08-17 19:30
@jef-n  I suspect the root cause of this issue is the latest update in Poppler in OSGeo4W, and particularly disabling LCMS support

Closing as not a GDAL issue

**Closed as completed by rouault** 2024-08-17 19:30 UTC

**Comment by jef-n** [comment] 2024-08-18 20:02
@rouault Rebuilding with lcms2 doesn't seem to change anything.  Any other clues?

**Comment by rouault** [comment] 2024-08-18 20:27
> @rouault Rebuilding with lcms2 doesn't seem to change anything. Any other clues?

@jef-n Not really. I've looked at the poppler recipe in Conda-Forge (https://github.com/conda-forge/poppler-feedstock/tree/main/recipe), but nothing strikes me at immediately relevant . The Conda Forge recipe has a number of Windows specific patches, but they seem related to compile-time issues. I also note it has the fontconfig dependency, but the rendering issue observed doesn't seem to be font specific.

**Comment by agiudiceandrea** [comment] 2024-08-19 07:37
> particularly disabling LCMS support

Not sure this could be the root cause: it looks like both 23.07.0 and 24.04.0 from OSGeo4W were built without LCMS support, since the `pdftoppm -h` output doesn't list the "-default*profile" options.

https://gitlab.freedesktop.org/poppler/poppler/-/blob/master/utils/pdftoppm.cc#L172-177

I've tested various pdftoppm options, and it looks like there's something not working well when both the "-aaVector yes" and the "-gray" options are specified (which are by default).

When "-mono" is specified, both pdftoppm 23.07.0 and 24.04.0 from OSGeo4W behave the same and output an identical image with "-aaVector yes" and another identical image with "-aaVector no", while when "-gray" is specified then they output an identical image with "-aaVector no" but they output different images  with "-aaVector yes".
Maybe there is something not working well with the gray color space?

**Comment by agiudiceandrea** [comment] 2024-08-22 22:16
@jef-n, if it is not possible to fix the OSGeo4W poppler 24.04.0 build, or in the meantime that it will be fixed, I propose to downgrade the OSGeo4W poppler package to the previous version and rebuild gdal and other dependent packages in order to avoid the reported issue.

**Comment by jef-n** [comment] 2024-09-05 16:29
see also https://trac.osgeo.org/osgeo4w/ticket/850

**Comment by cxcandid** [comment] 2024-10-28 15:43
@jef-n, is there any workaround that we can carry out as users? ...maybe downloading OSGeo4W GDAL 3.8.4 and replacing the files in the QGIS installation? We rely on QGIS for Windows and it is very annoying that every PDF now comes with a dither.

**Comment by agiudiceandrea** [comment] 2025-02-18 13:27
@cxcandid, it looks like the issue is now fixed with the poppler packages version 25.0.2-1:

![test_pop2502](https://github.com/user-attachments/assets/41efed1b-4a5a-4fc9-a407-e0e771e250c9)

**Comment by cxcandid** [comment] 2025-02-18 13:33
@agiudiceandrea that's very good news, thank you! ...hope it will find it's way into QGIS for Windows.

**Comment by agiudiceandrea** [comment] 2025-02-18 13:39
@cxcandid, the new package is already available using the OSGeo4W network installer and it will also be available in the upcoming QGIS LTR 3.40.4 and QGIS 3.42.0 stand-alone installers.

**Comment by cxcandid** [comment] 2025-02-22 13:40
@agiudiceandrea,I have just tested OSGeo4W QGIS 3.42.0 and can confirm that the problem has finally been solved. Thanks for your commitment!
