### ISSUE TITLE
Option to set source file type

### ISSUE THREAD

**Issue by rgwozdz** [OSGeo/gdal#3469] opened 2021-02-22 15:34 UTC
## Expected behavior and actual behavior.

Is there a reason that `ogrInfo` and `org2ogr` have no option for setting the source file's type?  It seems like a useful option, and I have a specific use case.

I have a ndJSON data files that can't be identified by the GeoJSONseq driver.  It hasn't something to do with the length of features, as well as the number of features. If I reduce the number of features sufficiently, or manually move `"type":"Feature"` to the beginning of a feature's string, the driver correctly identifies the file and does the expected processing.  Otherwise I  get the `Unable to open datasource...` error.

Having the ability to set the input source type would seem like an easy way to avoid this limitation. Is there a reason it hasn't yet been added?

## Steps to reproduce the problem.
[test.txt](https://github.com/OSGeo/gdal/files/6023056/test.txt)
With the attached ndjson file do:

```
>  orginfo test.txt
```

Should fail to open.

If you remove one line from the file or or manually move `"type":"Feature"` to the beginning of a feature's string and repeat the `orginfo` command, it should work.

## Operating system
Mac 10.15

## GDAL version and provenance
3.2.1

**Comment by jratike80** [comment] 2021-02-22 15:43
It seems that you are asking a question and we would like to see questions on the gdal-dev mailing list.

Is this problem the same that you reported in https://github.com/OSGeo/gdal/issues/3280? Didn't the fix remove the problem?

**Comment by rgwozdz** [comment] 2021-02-22 15:49
@jratike80 - the fix did work for the dataset originally posted. But it seems we have run into something similar but not quite the same.

Apologies for posting the question here, I should reframe as an enhancement request.

**Comment by jratike80** [comment] 2021-02-22 16:01
I made a test with GDAL 3.3.0dev, released 2021/99/99 from yesterday and it behaves like you describe. After deleting the last line ogrinfo does work.

I do not quite understand what use there would be for setting the source file's type. Obviously the GeoJSON driver at the moment cannot handle that sort of input. It would not help to tell "Hey GDAL, this is really GeoJSON, please do something for it". GDAL is rathet good at analysing the data sources. For example with your test data, once one row removed and renamed

```
ogrinfo test.foo
INFO: Open of `test.foo'
      using driver `GeoJSONSeq' successful.
1: test
```

**Comment by rgwozdz** [comment] 2021-02-22 16:18
At least in this case, it seems like GDAL is having some difficulty identifying a valid GeoJSON sequence file.  It's unclear why any one extra line in a ~150 line ndJSON file would cause it to fail to identify the file type.  The GeoJSON is valid, it just doesn't appear to like the length of the file or features.

It is true that I am making the assumption that only problem here is that the driver can't identify the file using its current routines - and also assuming that it could otherwise do the work that needs to be done if it could skip the file identification step.  It seems like a fair assumption since manually moving "type":"Feature" to the beginning of a feature's string or reducing the number of features sufficiently allows GDAL to operate on the file properly.

I'm prepared to do a PR for setting source type if you think the concept of this option would be approved.

**Comment by jratike80** [comment] 2021-02-22 16:22
You could rather have a look the at the GeoJSON driver. If adding one more line into ndJSON line makes it to fail there is obviously some limit that is exceeded. You can find it, and carefully consider why such limit exists. Would something fail badly if input had one million more lines? The limit may be there for a reason, or then not.

**Comment by jratike80** [comment] 2021-02-22 16:56
But generally something like `-if` in gdalinfo https://gdal.org/programs/gdalinfo.html could be useful. There are already some driver specific hints, for example `OAPIF:` and `GMLAS:`.

**Comment by drspacemanphd** [comment] 2021-05-27 12:00
Hi, just wanted to bump this as I am running into a similar issue.

**Comment by rouault** [comment] 2021-05-27 12:07
> Hi, just wanted to bump this as I am running into a similar issue.

Please be very specific and attach a reproducer test case. Specifying the input driver should be a last resort solution.

**Comment by drspacemanphd** [comment] 2021-05-27 12:34
> Please be very specific and attach a reproducer test case. Specifying the input driver should be a last resort solution.

Hi, I can provide test cases, but it's virtually the exact same issue as here: https://github.com/OSGeo/gdal/issues/3280. I see that commits referencing the issue have been made. Is there a release plan for a fix?

**Comment by rouault** [comment] 2021-05-27 12:37
> I see that commits referencing the issue have been made. Is there a release plan for a fix?

any release starting with 3.2.2 already contain the fix.

**Comment by drspacemanphd** [comment] 2021-05-27 13:04
> any release starting with 3.2.2 already contain the fix.

Ok thanks. Just clarifying as it looks like the commit was included in release 3.2.1, which is what I am using. I'll try upgrading the versions and report on the linked story with details to reproduce.

**Comment by rouault** [comment] 2021-05-27 13:07
> Just clarifying as it looks like the commit was included in release 3.2.1

ah, sorry, you're right. It is indeed in 3.2.1. So you might hit something else.

**Comment by drspacemanphd** [comment] 2021-05-27 13:59
Hi, thanks for taking a look at this, unfortunately I am running into the same behavior, even when I update gdal 3.3.0.

### Steps To Reproduce

#### Installations and Versions
- gdal 3.3.0 (installed via Homebrew 3.1.9)
- 2019 15-inch Macbook Pro, with MacOS Mojave Version 10.14.6

#### Test Cases
[input.txt](https://github.com/OSGeo/gdal/files/6554481/input.txt)
Notice that there are only 517 records but >400 property fields for each record.

#### Steps 
- Run `ogrinfo input.txt`. The command fails with the message: `Unable to open datasource 'input.txt' with the following drivers...`
- In the input.txt file, move the `field` property of the first record only before the properties field. This can be done manually or doing something like the Node.js script below:
```
const fs = require('fs');

fs.readFile('./input.txt', { encoding: 'utf-8' }, (_err, data) => {
    const entries = data.split('\n').filter(d => typeof d === 'string' && d.length > 0)
    const parsed = JSON.parse(entries[0])
    console.log(Object.keys(parsed.properties).length)
    entries[0] = JSON.stringify({
        type: parsed.type,
        ...parsed
    })
    fs.writeFile('./output.txt', entries.join('\n'), { encoding: 'utf-8' }, (err) => console.log(err));
});
```
- Run the `ogrinfo` command again. Notice the command no longer errors out, but instead correctly uses the `GeoJSONSeq` driver

**Comment by jratike80** [comment] 2023-10-21 14:12
If I read right the title of this issue did not very well describe the real problem, but anyway with GDAL 3.8 dev I can force the use of geojsonseq driver with

`ogrinfo geojsonseq:date.json --debug on`

Closing the ticket.

**Closed by jratike80** 2023-10-21 14:12 UTC
