### ISSUE TITLE
Artefacts in JP2KAK output

### ISSUE THREAD

**Issue by Ozplanman** [OSGeo/gdal#3163] opened 2020-11-10 04:57 UTC
My apologies if this bug report is in the wrong place.  

## Expected behavior and actual behavior.

I am running the following line in a bash script:

gdal_translate -of JP2KAK ${2}.vrt ${2}.jp2

to convert a virtual mosaic created with gdalbuildvrt to a JP2 file of the same name. The command produces the output with the artefact shown in the attached image.  The source tiles for the mosaic are approximately 140 TIFs of approx 300MB each.

The output JP2 is approximately 10GB using the default QUALITY=20 setting.  I have also tried using different QUALITY=n settings with the same result.  The above behaviour is seen in ArcMap 10.4 and Erdas Imagine 2016 in Windows 10.  _I have just found that a lossless version of the image opens without issues in QGIS 3 on sles15 but not on Windows platform apps.  Will edit this submission when I have more information._

Creating a GTiff from the same virtual mosaic works fine with no artefact.  Converting that TIF, instead of the virtual mosaic, to a JP2, produces the same artefact.  All lossey outputs on files this size using the JP2KAK driver appear to have the same artefact in the same place.  Testing the driver on a smaller input TIF file worked ok.  Seems related to dataset size and compression.

## Steps to reproduce the problem.

Have replicated the issue with different, similarly sized,  datasets.  

## Operating system

sles15 

## GDAL version and provenance
Version  Kakadu 7.10.7   Gdal 2.4.0 Rel. 2018/12/14.
I am informed that newer versions of gdal are available but my organisation has not yet been able to migrate to one.

Thanks for any suggestions.
![gdal_translate_artefact](https://user-images.githubusercontent.com/74215073/98608022-7bfc2a00-233e-11eb-8975-df9b60fe8825.png)

**Comment by jratike80** [comment] 2020-11-10 07:57
What is the size of the vrt in pixels? Are the source images 8-bit RGB images or what? Have you tried to compress the tiff version with kdu_compress? It is not easy to make a proper comparison with kdu_compress because you should give all the same parameters than GDAL is using, but you can make a quick test by selecting a parameter set that is reasonable for large geospatial image. I guess that the "usage" examples of kdu_compress have some good examples.

**Comment by Ozplanman** [comment] 2020-11-12 03:37
Hi, @jratike80 thanks for the reply.  The vrt pixel count is rasterXSize="110005" rasterYSize="130005".  I think the source is 12 bit BGRN and there are about 140 uncompressed TIF tiles.  Total area is approx. 2500 km2.  Haven't tried kdu_compress but as a test a single input file worked fine as noted.

**Comment by piyushrpt** [comment] 2020-11-12 05:15
Could it be possible that you have a band of nodata values in the individual tiffs along that line (possibly reprojected tiles) and using lossy compression is causing it to bleed? This would also impact the GTiff mosaic which will have the nodata values and its conversion.

**Comment by Ozplanman** [comment] 2020-11-12 06:33
Thanks for the reply, no, the artefact exists in other similar datasets in the same place, it may move laterally with different compression (quality switch).

**Comment by rouault** [comment] 2020-11-12 10:54
> Haven't tried kdu_compress but as a test a single input file worked fine as noted.

would be really interesting that you tried kdu_compress on the .tif file generated by "gdal_translate your.vrt your.tif". That said the JP2KAK driver and kdu_compress don't use the same Kakadu API (or not in the same way), so that wouldn't exclude an issue with Kakadu itself. And my feeling is that the bug is in Kakdu as you mention that changing the quality switch moves the artefact, but the code in the JP2KAK driver behaves exactly the same whatever the quality setting is (it just passes it as an option to Kakadu API)

**Comment by jratike80** [comment] 2020-11-12 14:23
You can also try to play with the Kakadu options. Does using creation option `-co BLOCKYSIZE=20000` change anything? or `-co Corder=RPCL`? Or, together with smaller than default blocksize, `-co FLUSH=FALSE`.
The current Kakadu version is 8.0.6 so if the issue happens to be in the 7.10 version of the Kakadu SDK it probably won't be fixed.

**Comment by Ozplanman** [comment] 2020-11-13 02:38
thanks everyone.  I will try to check some different options though I am trying not to degrade the image.  Am struggling to understand why the artefact doesn't appear when running QGIS in the sles15 environment or on single files of the same type, or why it does appear when run in Windows apps and why it extends beyond the image area into the image border.

**Comment by rouault** [comment] 2022-01-17 20:00
Closing as it is most likely an issue in Kakadu itself and there's no sufficient details to reproduce.

**Closed by rouault** 2022-01-17 20:00 UTC
