### ISSUE TITLE
Gdal warp silently failing to reproject tif to 3857

### ISSUE THREAD

**Issue by BerndSchrooten** [OSGeo/gdal#3273] opened 2020-12-09 14:19 UTC
### Actual behavior:

gdalwarp is unable to reproject a GeoTIFF to EPSG 3857 but continues anyway. 

```
gdalwarp -t_srs EPSG:3857 input.tif input_3857.tif
```

gdalwarp logs:
```
Using band 4 of source image as alpha.
ERROR 1: PROJ: proj_create_operations: Inconsistent chaining of CRS in operations
ERROR 6: Cannot find coordinate operations from `BOUNDCRS[SOURCECRS[PROJCRS["NTF (Paris) / Lambert Sud France",BASEGEOGCRS["NTF (Paris)",DATUM["Nouvelle Triangulation Francaise (Paris)",ELLIPSOID["Clarke 1880 (IGN)",6378249.2,293.466021293627,LENGTHUNIT["metre",1]]],PRIMEM["Paris",2.5969213,ANGLEUNIT["grad",0.0157079632679489]],ID["EPSG",4807]],CONVERSION["unnamed",METHOD["Lambert Conic Conformal (1SP)",ID["EPSG",9801]],PARAMETER["Latitude of natural origin",54.4444444444445,ANGLEUNIT["grad",0.0157079632679489],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",0,ANGLEUNIT["grad",0.0157079632679489],ID["EPSG",8802]],PARAMETER["Scale factor at natural origin",0.999877499,SCALEUNIT["unity",1],ID["EPSG",8805]],PARAMETER["False easting",600000,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",200000,LENGTHUNIT["metre",1],ID["EPSG",8807]]],CS[Cartesian,2],AXIS["easting",east,ORDER[1],LENGTHUNIT["metre",1]],AXIS["northing",north,ORDER[2],LENGTHUNIT["metre",1]],ID["EPSG",27563]]],TARGETCRS[GEOGCRS["WGS 84",DATUM["World Geodetic System 1984",ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],CS[ellipsoidal,2],AXIS["latitude",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433]],AXIS["longitude",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]]],ABRIDGEDTRANSFORMATION["Transformation from NTF (Paris) to WGS84",METHOD["Position Vector transformation (geog2D domain)",ID["EPSG",9606]],PARAMETER["X-axis translation",-168,ID["EPSG",8605]],PARAMETER["Y-axis translation",-60,ID["EPSG",8606]],PARAMETER["Z-axis translation",320,ID["EPSG",8607]],PARAMETER["X-axis rotation",0,ID["EPSG",8608]],PARAMETER["Y-axis rotation",0,ID["EPSG",8609]],PARAMETER["Z-axis rotation",0,ID["EPSG",8610]],PARAMETER["Scale difference",1,ID["EPSG",8611]]]]' to `BOUNDCRS[SOURCECRS[GEOGCRS["NTF (Paris)",DATUM["Nouvelle Triangulation Francaise (Paris)",ELLIPSOID["Clarke 1880 (IGN)",6378249.2,293.466021293627,LENGTHUNIT["metre",1]],ID["EPSG",6807]],PRIMEM["Paris",2.5969213,ANGLEUNIT["grad",0.0157079632679489,ID["EPSG",9105]]],CS[ellipsoidal,2],AXIS["geodetic latitude (Lat)",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],AXIS["geodetic longitude (Lon)",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]]]],TARGETCRS[GEOGCRS["WGS 84",DATUM["World Geodetic System 1984",ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],CS[ellipsoidal,2],AXIS["latitude",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433]],AXIS["longitude",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]]],ABRIDGEDTRANSFORMATION["Transformation from NTF (Paris) to WGS84",METHOD["Position Vector transformation (geog2D domain)",ID["EPSG",9606]],PARAMETER["X-axis translation",-168,ID["EPSG",8605]],PARAMETER["Y-axis translation",-60,ID["EPSG",8606]],PARAMETER["Z-axis translation",320,ID["EPSG",8607]],PARAMETER["X-axis rotation",0,ID["EPSG",8608]],PARAMETER["Y-axis rotation",0,ID["EPSG",8609]],PARAMETER["Z-axis rotation",0,ID["EPSG",8610]],PARAMETER["Scale difference",1,ID["EPSG",8611]]]]'
Creating output file that is 40842P x 66998L.
Processing ortho.tif [1/1] : 0
```

As a workaround we can pass the original file through gdal_translate as follows. Warping will run without a problem on this output file as it modifies the CRS.

```
gdal_translate -co COMPRESS=LZW -co BIGTIFF=YES input.tif translate_input.tif
```

gdalinfo of input.tif:
```
Driver: GTiff/GeoTIFF
Files: input.tif
Size is 29826, 41565
Coordinate System is:
BOUNDCRS[
    SOURCECRS[
        PROJCRS["NTF (Paris) / Lambert Sud France",
            BASEGEOGCRS["NTF (Paris)",
                DATUM["Nouvelle Triangulation Francaise (Paris)",
                    ELLIPSOID["Clarke 1880 (IGN)",6378249.2,293.466021293627,
                        LENGTHUNIT["metre",1]]],
                PRIMEM["Paris",2.5969213,
                    ANGLEUNIT["grad",0.0157079632679489]],
                ID["EPSG",4807]],
            CONVERSION["unnamed",
                METHOD["Lambert Conic Conformal (1SP)",
                    ID["EPSG",9801]],
                PARAMETER["Latitude of natural origin",54.4444444444445,
                    ANGLEUNIT["grad",0.0157079632679489],
                    ID["EPSG",8801]],
                PARAMETER["Longitude of natural origin",0,
                    ANGLEUNIT["grad",0.0157079632679489],
                    ID["EPSG",8802]],
                PARAMETER["Scale factor at natural origin",0.999877499,
                    SCALEUNIT["unity",1],
                    ID["EPSG",8805]],
                PARAMETER["False easting",600000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8806]],
                PARAMETER["False northing",200000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8807]]],
            CS[Cartesian,2],
                AXIS["easting",east,
                    ORDER[1],
                    LENGTHUNIT["metre",1]],
                AXIS["northing",north,
                    ORDER[2],
                    LENGTHUNIT["metre",1]],
            ID["EPSG",27563]]],
    TARGETCRS[
        GEOGCRS["WGS 84",
            DATUM["World Geodetic System 1984",
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            CS[ellipsoidal,2],
                AXIS["latitude",north,
                    ORDER[1],
                    ANGLEUNIT["degree",0.0174532925199433]],
                AXIS["longitude",east,
                    ORDER[2],
                    ANGLEUNIT["degree",0.0174532925199433]],
            ID["EPSG",4326]]],
    ABRIDGEDTRANSFORMATION["Transformation from NTF (Paris) to WGS84",
        METHOD["Position Vector transformation (geog2D domain)",
            ID["EPSG",9606]],
        PARAMETER["X-axis translation",-168,
            ID["EPSG",8605]],
        PARAMETER["Y-axis translation",-60,
            ID["EPSG",8606]],
        PARAMETER["Z-axis translation",320,
            ID["EPSG",8607]],
        PARAMETER["X-axis rotation",0,
            ID["EPSG",8608]],
        PARAMETER["Y-axis rotation",0,
            ID["EPSG",8609]],
        PARAMETER["Z-axis rotation",0,
            ID["EPSG",8610]],
        PARAMETER["Scale difference",1,
            ID["EPSG",8611]]]]
Data axis to CRS axis mapping: 1,2
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Band 1 Block=29826x32 Type=Float32, ColorInterp=Gray
  NoData Value=-32767
  Unit Type: metre
```
gdalinfo of translate_input file:
```
Driver: GTiff/GeoTIFF
Files: translate_input.tif
Size is 29826, 41565
Coordinate System is:
PROJCRS["NTF (Paris) / Lambert Sud France",
    BASEGEOGCRS["NTF (Paris)",
        DATUM["Nouvelle Triangulation Francaise (Paris)",
            ELLIPSOID["Clarke 1880 (IGN)",6378249.2,293.466021293627,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Paris",2.5969213,
            ANGLEUNIT["grad",0.0157079632679489]],
        ID["EPSG",4807]],
    CONVERSION["unnamed",
        METHOD["Lambert Conic Conformal (1SP)",
            ID["EPSG",9801]],
        PARAMETER["Latitude of natural origin",49,
            ANGLEUNIT["grad",0.0157079632679489],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["grad",0.0157079632679489],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.999877499,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",600000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",200000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    ID["EPSG",27563]]
Data axis to CRS axis mapping: 1,2
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Band 1 Block=29826x1 Type=Float32, ColorInterp=Gray
  NoData Value=-32767
  Unit Type: metre
```

### Expected behavior: 

This issue is two-fold:
- Why is gdal warp failing silently on the reprojection? We believe warping should error because of this.
- Why does passing the tif with this specific WKT through gdal_translate solve the issue? Obviously, it changes the WKT, but shouldn't it be equivalent? Can gdal_warp maybe use a similar approach to handling CRSs?

## Steps to reproduce the problem.
Force gdal warp on any tif to use the original crs. `./bad_wkt` is a file containing the original CRS as WKT.
```
gdalwarp -t_srs EPSG:3857 input.tif input_3857.tif
OR
gdalwarp -t_srs EPSG:3857 -s_srs ./bad_wkt random.tif random_3857.tif
```

Overriding the CRS first using gdal_translate makes warping run without a problem. This results in the same CRS from the translated input tif.

```
gdal_translate -a_srs ./bad_wkt input.tif input_good.tif
gdalwarp -t_srs EPSG:3857 input_good.tif input_3857.tif
```

## Operating system

Ubuntu 16.04 64 bit, macOS

## GDAL version and provenance

Tested on GDAL 3.1.2, 3.1.4 and 3.2 (conda)

**Comment by rouault** [comment] 2020-12-09 14:41
I've tried to reproduce the error, but things work properly for me with GDAL and PROJ master. I believe you might have hit a PROJ bug that has been fixed in a later version than the one you use.

The presence of the BOUNDCRS is due to older GDAL versions writing in the GeoTIFF keys the "GeogTOWGS84GeoKey (Double,3): -168             -60              320" information (can be seen with libgeotiff ``listgeo`` utilility) that no longer bring any information in recent PROJ that can handle datum shift in a smarter way. Recent GDAL versions normally strip this information on reading a GeoTIFF file, unless you set the OSR_STRIP_TOWGS84 configuration option to NO (GDAL 3.2 in particular, so I believe your gdalinfo output that shows a BOUNDCRS has been generated with an older version), and on writing they won't write it either.

**Comment by BerndSchrooten** [comment] 2020-12-09 15:13
Thanks for your swift reply @rouault. However, we are also experiencing the issue in the latest osgeo/gdal docker image using gdal 3.3.0dev and Proj8.

gdalinfo output also shows a BOUNDCRS here. What you're saying does explain why gdal_translate outputs a different CRS.

**Comment by rouault** [comment] 2020-12-09 16:18
>  we are also experiencing the issue in the latest osgeo/gdal docker image using gdal 3.3.0dev and Proj8. The gdalinfo output also shows a BOUNDCRS here.

Hum, OK. Can you provide me with a link to the dataset (the smallest the better) ? Possibly in a private way at <even.rouault at spatialys.com>

> What you're saying does explain why gdal_translate outputs a different CRS.

The GeoTIFF driver, in writing and in recent GDAL versions, strips off BOUND_CRS / TOWGS84 when it detects that the ToWGS84 information is the "default" one, because BoundCRS confuses a number of GDAL users like QGIS.

**Closed** 2020-12-14 20:42 UTC

**Comment by EvertEt** [comment] 2020-12-22 20:53
Many thanks for the quick fix on this issue! Much appreciated
