### ISSUE TITLE
OGR2OGR Sqlserver geography type

### ISSUE THREAD

**Issue by svha1977** [OSGeo/gdal#3968] opened 2021-06-11 10:57 UTC
SQLSERVER version info 
        Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64) 
	Oct 28 2016 18:17:30 
	Copyright (c) Microsoft Corporation
	Express Edition (64-bit) on Windows 10 Enterprise 6.3 <X64> (Build 18363: ) (Hypervisor)

ogr2ogr --version
GDAL 3.0.3, released 2020/01/08

Test Data
[TestData.zip](https://github.com/OSGeo/gdal/files/6637714/TestData.zip)

OGR2OGR import
ogr2ogr -f "MSSQLSpatial" "MSSQL:server=(LocalDb)\MSSQLLocalDB;database=DHI-Femo;trusted_connection=yes;" "C:\George\TestData.gpkg" -progress -lco GEOM_TYPE=GEOGRAPHY

Then Run

SELECT [Geom].STSrid AS Srid
	  ,[Geom].STIsValid() AS IsValid
	  ,[Geom].STAsText() As WKT
	  ,[Geom].STNumGeometries() As NumGeom
	  ,[Geom].EnvelopeAngle() AS EnvelopeAngle
  FROM TestData

All considered valid. But different things are off like envelope angle (other things like ReorientObject is also not tight)
![image](https://user-images.githubusercontent.com/79256602/121675109-40cc0000-cab3-11eb-9c15-c515f1696aad.png)

Then try
  UPDATE TestData SET Geom = Geom.MakeValid();

Then try
 SELECT [Geom].STSrid AS Srid
	  ,[Geom].STIsValid() AS Valid
	  ,[Geom].STAsText() As WKT
	  ,[Geom].STNumGeometries() As NumGeom
	  ,[Geom].EnvelopeAngle() AS EnvelopeAngle
  FROM TestData

![image](https://user-images.githubusercontent.com/79256602/121675192-61945580-cab3-11eb-834e-4e827592f98b.png)

Then let SQLServer create the geoms from WKT 

UPDATE TestData SET Geom = geography::STGeomFromText([Geom].STAsText(), 4326);  

SELECT [Geom].STSrid AS Srid
	  ,[Geom].STIsValid() AS Valid
  FROM TestData

Now two are invalid
![image](https://user-images.githubusercontent.com/79256602/121675381-9c968900-cab3-11eb-93bf-b95fd25067ab.png)

 UPDATE TestData SET Geom = Geom.MakeValid(); 

    SELECT [Geom].STSrid AS Srid
	  ,[Geom].STIsValid() AS Valid
  FROM TestData

Now envelope angle is totally different
![image](https://user-images.githubusercontent.com/79256602/121675449-b59f3a00-cab3-11eb-949b-7f98b39a001d.png)

In which case the above 90 degrees can e.g. be reoriented since some libs requiere this 

If creating the same geometries from the WKT in the GeoPackage not the binary import makes SQL server label the geometries as invalid not valid. E.g.

select geography::STGeomFromText('MULTIPOLYGON (((11.421152155220954 54.631344167231482, 11.421158071540113 54.631348619639589, 11.421166069903174 54.631351793489877, 11.421175367374175 54.631353378103448, 11.421185053850857 54.63135321836711, 11.421194181152199 54.631351329917017, 11.421201855833433 54.631347897608023, 11.421207326643001 54.631343257418813, 11.421210058060403 54.631337863563715, 11.421209782716492 54.631332244031064, 11.421206527565042 54.631326948899812, 11.420708244320878 54.630797360203267, 11.420702328132084 54.6307929077715, 11.420694329915264 54.630789733888825, 11.420685032591161 54.630788149236693, 11.420675346245607 54.630788308931685, 11.420666219044405 54.630790197341774, 11.420658544420684 54.630793629616505, 11.420653073619798 54.630798269781188, 11.420650342162313 54.630803663624526, 11.420650617423336 54.630809283159721, 11.420653872459598 54.630814578307486, 11.421152155220954 54.631344167231482)), ((11.421859068537893 54.630252712949932, 11.4218648482411 54.630257225279237, 11.42187274852737 54.630260480581761, 11.421881996061218 54.630262160205412, 11.421891685628607 54.630262099736782, 11.42190086874597 54.630260305094971, 11.421908646504853 54.630256951952241, 11.421914257563703 54.63025236853791, 11.421917152673396 54.6302470035088, 11.421917048441422 54.630241382031556, 11.421913955071933 54.630236054375509, 11.421867824465014 54.630184896796649, 11.421862044771983 54.630180384467316, 11.421854144502271 54.630177129163911, 11.421844896988915 54.630175449537894, 11.42183520744195 54.630175510002587, 11.421826024340547 54.630177304639261, 11.421818246589712 54.630180657776634, 11.421812635529564 54.630185241186581, 11.421809740410177 54.63019060621334, 11.421809844627006 54.63019622769086, 11.42181293797978 54.630201555349764, 11.421859068537893 54.630252712949932)))', 4326).STIsValid();
  select geography::STGeomFromText('MULTIPOLYGON (((11.421152155220954 54.631344167231482, 11.421158071540113 54.631348619639589, 11.421166069903174 54.631351793489877, 11.421175367374175 54.631353378103448, 11.421185053850857 54.63135321836711, 11.421194181152199 54.631351329917017, 11.421201855833433 54.631347897608023, 11.421207326643001 54.631343257418813, 11.421210058060403 54.631337863563715, 11.421209782716492 54.631332244031064, 11.421206527565042 54.631326948899812, 11.420708244320878 54.630797360203267, 11.420702328132084 54.6307929077715, 11.420694329915264 54.630789733888825, 11.420685032591161 54.630788149236693, 11.420675346245607 54.630788308931685, 11.420666219044405 54.630790197341774, 11.420658544420684 54.630793629616505, 11.420653073619798 54.630798269781188, 11.420650342162313 54.630803663624526, 11.420650617423336 54.630809283159721, 11.420653872459598 54.630814578307486, 11.421152155220954 54.631344167231482)), ((11.421859068537893 54.630252712949932, 11.4218648482411 54.630257225279237, 11.42187274852737 54.630260480581761, 11.421881996061218 54.630262160205412, 11.421891685628607 54.630262099736782, 11.42190086874597 54.630260305094971, 11.421908646504853 54.630256951952241, 11.421914257563703 54.63025236853791, 11.421917152673396 54.6302470035088, 11.421917048441422 54.630241382031556, 11.421913955071933 54.630236054375509, 11.421867824465014 54.630184896796649, 11.421862044771983 54.630180384467316, 11.421854144502271 54.630177129163911, 11.421844896988915 54.630175449537894, 11.42183520744195 54.630175510002587, 11.421826024340547 54.630177304639261, 11.421818246589712 54.630180657776634, 11.421812635529564 54.630185241186581, 11.421809740410177 54.63019060621334, 11.421809844627006 54.63019622769086, 11.42181293797978 54.630201555349764, 11.421859068537893 54.630252712949932)))', 4326).ReorientObject().STAsText();

So it seems some binary stuff on OGR2OGR import might be a bit off, but not more than most things work - just not all things lige reorient.

e.g. look at the original import - raw imported data and 
SELECT [Geom].STSrid AS Srid
	  ,[Geom].STIsValid() AS IsValid
	  ,[Geom].STAsText() As WKT
	  ,[Geom].STNumGeometries() As NumGeom
	  ,[Geom].EnvelopeAngle() AS EnvelopeAngle
	  ,[Geom].ReorientObject().STAsText() AS Reorientated
  FROM TestData

![image](https://user-images.githubusercontent.com/79256602/121676020-6c031f00-cab4-11eb-8d2b-8dabaddb2b6b.png)

Basicly making the reoriented polygons become EMPTY geometry collctions most likely due to SQL Server treating them as valid even if they from WKT creation is not.

Could be a bug in SQL server of course but most likely a spec mismatch?

**Comment by elpaso** [comment] 2023-05-26 13:33
Maybe this issue has the same root cause of https://github.com/OSGeo/gdal/issues/1128 (fixed by https://github.com/OSGeo/gdal/pull/7826). 

I would recommend to close and re-open if the problem persists after https://github.com/OSGeo/gdal/pull/7826) is merged.

**Closed** 2023-05-26 13:44 UTC
