### ISSUE TITLE
GetProjection hangs with Python 3.7 multiprocessing pool

### ISSUE THREAD

**Issue by emlys** [OSGeo/gdal#3069] opened 2020-10-15 19:43 UTC
## Expected behavior and actual behavior.

I expect that using Python threading and multiprocessing libraries with GDAL `Dataset` functions should work when each thread/process is accessing a different filepath.

Trying to open a directory with `gdal.OpenEx` in a thread of the main process, while a subprocess is calling one of `GetProjection`, `GetProjectionRef`, or `GetSpatialRef` on an unrelated dataset, causes the program to hang. `gdal.OpenEx(directory)` returns `None` as expected, but somehow interferes with other processes.

`GetRootGroup` fails with a traceback:
<details><summary>Traceback</summary>

> multiprocessing.pool.RemoteTraceback: 
> """
> Traceback (most recent call last):
>   File "/opt/miniconda3/envs/bug3.7-3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
>     result = (True, func(*args, **kwds))
>   File "src/natcap/invest/reproduce_bug2.py", line 1738, in func_b
>     rootgroup = raster.GetRootGroup()
>   File "/opt/miniconda3/envs/bug3.7-3/lib/python3.7/site-packages/osgeo/gdal.py", line 2045, in <lambda>
>     __getattr__ = lambda self, name: _swig_getattr(self, Dataset, name)
>   File "/opt/miniconda3/envs/bug3.7-3/lib/python3.7/site-packages/osgeo/gdal.py", line 74, in _swig_getattr
>     return _swig_getattr_nondynamic(self, class_type, name, 0)
>   File "/opt/miniconda3/envs/bug3.7-3/lib/python3.7/site-packages/osgeo/gdal.py", line 69, in _swig_getattr_nondynamic
>     return object.__getattr__(self, name)
> AttributeError: type object 'object' has no attribute '__getattr__'
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "src/natcap/invest/reproduce_bug2.py", line 1768, in <module>
>     execute(path_a=path1, path_b=raster1)
>   File "src/natcap/invest/reproduce_bug2.py", line 1753, in execute
>     result = worker_pool.apply(func=func_b, args=(path_b,))
>   File "/opt/miniconda3/envs/bug3.7-3/lib/python3.7/multiprocessing/pool.py", line 261, in apply
>     return self.apply_async(func, args, kwds).get()
>   File "/opt/miniconda3/envs/bug3.7-3/lib/python3.7/multiprocessing/pool.py", line 657, in get
>     raise self._value
> AttributeError: type object 'object' has no attribute '__getattr__'
</details>

## Steps to reproduce the problem.

Minimal example (observed on python 3.7.9, does not happen with 3.8.0):
```
import threading
import multiprocessing.pool
from osgeo import gdal


def func_a(path):
    dataset = gdal.OpenEx(path)
    print('func_a dataset:', dataset)

def func_b(path):
    dataset = gdal.OpenEx(path)
    print('func_b dataset:', dataset)
    
    # hangs on dataset.GetProjection
    projection_wkt = dataset.GetProjection()
    print('got func_b datset projection')

def execute(path_a, path_b):

    thread = threading.Thread(target=func_a, args=(path_a,))
    thread.start()

    with multiprocessing.pool.Pool(1) as worker_pool:
        result = worker_pool.apply(func=func_b, args=(path_b,))


if __name__ == '__main__':
    # path to a directory, it doesn't matter if path_b is located under path_a or not
    path_a = '~/Documents/'
    # path to an arbitrary raster
    path_b = '~/Downloads/raster.tif'
    execute(path_a, path_b)
```

Expected output:
```
func_b dataset: <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7fc4d003df00> >
func_a dataset: None
got func_b datset projection
```

Actual output:
```
func_b dataset: <osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7fc4d003df00> >
func_a dataset: None
<hangs forever>
```

This problem only happens when there is both a `threading.Thread` and a `multiprocessing.pool.Pool` involved. The problem does not happen if you use a `multiprocessing.Process` in place of the `Pool(1)`.

## Operating system

macOS Catalina 10.15.6

## GDAL version and provenance

3.0.4 from conda-forge

**Comment by rouault** [comment] 2020-10-15 20:14
This has probably been fixed in 3.1.3 per

commit 095bc422fcccfd66ca3597c5c6faa1368235f6b5
Author: Even Rouault <even.rouault@spatialys.com>
Date:   Wed Feb 5 23:16:14 2020 +0100

    Fix PROJ usage accross fork() calls (fixes #2221)

**Comment by rouault** [comment] 2020-10-16 15:52
Actually I can reproduce your issue, but I don't think there's an easy resolution, apart from the workaround you've identified. Fundamentally using mutli-threaded aware libraries like GDAL, PROJ or sqlite3 that use mutexes, and using fork() without exec() is bound to cause dead locks (here it seems that it stalls in a mutex in sqlite3 as use by PROJ) because mutex structures are only thread-aware and not process-aware. Or you'd have to build those libraries without thread-support.

**Comment by rouault** [comment] 2020-10-16 18:54
Actually the issue must be met only when fork'()ing while a thread (other than the one fork()'ing) is active. Exactly your scenario. So something to avoid.

Closing as 'can't fix'

**Closed by rouault** 2020-10-16 18:54 UTC

**Comment by sgillies** [comment] 2020-10-16 19:56
@emlys see the "Changed in version 3.8" note under https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods, this could explain the difference in behavior you noticed between 3.7.9 and 3.8.0.
