### ISSUE TITLE
ogr returns different resultsets in case of datetime queries for different formats

### ISSUE THREAD

**Issue by rduivenvoorde** [OSGeo/gdal#3423] opened 2021-02-01 14:03 UTC
See also my 'downstream' issue: https://github.com/qgis/QGIS/issues/41074

I retested against GDAL 3.3.0dev-d7a1fea1c8, released 2021/01/15 so probably still the same

OGR apparently treats the DateTime queries differently, and that is the reason that QGIS returns different result sets for different data formats....

To test/see:  [testdata.zip](https://github.com/qgis/QGIS/files/5904281/testdata.zip). 
That zip contains both a gpkg and a flatgeobuf of the same data with one DateTime column.
Unzip in a dir and check the output of the 'query' that is done by QGIS (well in my version....):

```
ogrinfo -sql "select * from smallcloudpoints where (Time > '2019-09-01T06:00:00Z') and (Time < '2019-09-01T08:00:00Z') " smallcloudpoints.fgb
```

this rightfully returns ONLY the 7:00 features...

Now the same for the gpkg:

```
ogrinfo -sql "select * from smallcloudpoints where (Time > '2019-09-01T06:00:00Z') and (Time < '2019-09-01T08:00:00Z') " smallcloudpoints.gpkg
```

THAT returns both 7:00 AND 8:00 features ????

Note that '2019-09-01T06:00:00Z' or '2019-09-01T06:00:00.000Z' is the right format to write a datatime in gpkg: see http://www.geopackage.org/spec/#r5

BUT... to make it worse: now remove the Z from the datetime:

```
ogrinfo -sql "select * from smallcloudpoints where (Time > '2019-09-01T06:00:00') and (Time < '2019-09-01T08:00:00') " smallcloudpoints.gpkg
```

it returns the right (7:00 only) features....

Not sure if this is something that can/should be fixed here in OGR, or is the result of the 'sql' handling in OGR, can we should try to 'fix' this in QGIS?

**Comment by jratike80** [comment] 2021-02-02 08:26
How did you create the geopackage? I believe that the problem is not in the query but in the data that seems to have times stored without Z, this way

`2019-09-02T02:00:00`

I looked the data with DB Browser for SQLite.

**Comment by rduivenvoorde** [comment] 2021-02-02 14:23
@jratike80 see https://github.com/qgis/QGIS/issues/41074 

The crux is that sqlite is not DateTime Aware, so the sql queries actually become 'string comparisons'.

BUT as a geopackage/gdal apparently does NOT enforce formatting rules, you can put anything in a field defined as 'DATETIME' giving rise to really undefined behaviour.

2019-09-02T02:00:00
2019-09-02T02:00:00.0
2019-09-02T02:00:00.000
2019-09-02T02:00:00Z
2019-09-02T02:00:00.000Z

is all ok, but give different results... 

I think geopackage really has some work to do to make it usable with Temporal data...

**Comment by jratike80** [comment] 2021-02-02 15:09
The GeoPackage standard tries to make is as explicit as it can be with SQLite. 

> ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ with T separator character and Z suffix for coordinated universal time (UTC) encoded in either UTF-8 or UTF-16. See TEXT. Stored as SQLite TEXT.

Standard also defines that in some metadata tables the default value is given with
`select strftime('%Y-%m-%dT%H:%M:%fZ','now')`
and that prints strings like `2021-02-02T14:47:38.035Z`

It is true that you can store whatever you want into the DATETIME field and SQLite does not prevent you. However, if the field does not contain a zulu time string then it is just wrong. Because of this two questions to @rouault 

1) Are both `2019-09-02T02:00:00Z` and `2019-09-02T02:00:00.000Z` correct according to the standard?
2) Validate_gpkg.py script does not validate the DATETIME columns in the user tables like "smallcloudpoints" in he attached geopackage. Should it?

I would say that there is work to be done with the applications that use Temporal data that is stored into GeoPackage. That is not a unique requirement. If you convert your test geopackage into GML you will see strings like `<ogr:Time>2019-09-01T09:00:00</ogr:Time>`. Also in this case the software that is consuming time data must know that it is reading an ISO string and also know how to deal with it by parsing the tokens etc.

In other GIS concepts you will find that GeoPackage is more constrained and thus easier than for example the time dimension support in WMS. See a list of time string formats that MapServer supports from https://mapserver.gis.umn.edu/id/ogc/wms_time.html.

**Comment by rouault** [comment] 2021-02-02 16:47
> 1. Are both `2019-09-02T02:00:00Z` and `2019-09-02T02:00:00.000Z` correct according to the standard?

Reviewing the writing code of the OGR GPKG driver, it will produce YYYY-MM-DDTHH:MM:SSZ if the millisecond part is 0. This might not be fully conformant with the GPKG spec itself if one interprets it in a strict way.

> 2. Validate_gpkg.py script does not validate the DATETIME columns in the user tables like "smallcloudpoints" in he attached geopackage. Should it?

The script as far as I remember doesn't validate column content (maybe just some aspect of the geometries). Strictly speaking there are few GPKG "requirements" about that (I bet if you submit such GPKG with no millisecond, the OGC CITE validator will accept them), but it could make sense to have broader validation

**Comment by rduivenvoorde** [comment] 2021-02-03 09:51
@both is there a reason to NOT be very strict with respect to the geopackage spec, and or while opening/writing gpkg with GDAL?

If we keep finding it OK to define DATETIME in different ways, we will never be able to keep using the 'string comparison' that we use now. Then time based comparisons will always be ambiguous.

To me it looks like IF we are really strict in writing/reading the DateTime string format in sqlite: so always be YYYY-MM-DDTHH:MM:SS.SSSZ  (and I would not mind if the gpkg set's a constraint on that too), then the string comparison would 'just work'? Or am I wrong in this?

Not sure what OGR should do though when applications like QGIS come up with 'local times', that is without any timezone indication.... Either find out the local timezone and write it to Zulutime?

Another option would be to write datetime as milliseconds since epoch? But that will probably too much for the spec to change?

I had a look at: https://github.com/opengeospatial/geopackage/issues but I'm not sure I'm allowed to do such proposals:
- put a strict contraint on DATETIME defined columns about the format
- use milliseconds since epoch (UTC) as data for DATETIME

I also would not mind if OGR (and thus QGIS) would be more strict, and for example when data is not YYYY-MM-DDTHH:MM:SS.SSSZ formated in a DATETIME column, then show it as a STRING column..

At this moment gpkg's with DATETIME columns are in my opinion not to be used in for example the Temporal Controller of QGIS.

**Comment by rouault** [comment] 2021-02-03 10:32
> is there a reason to NOT be very strict with respect to the geopackage spec, and or while opening/writing gpkg with GDAL?

On writing, no, was an oversight addressed by https://github.com/OSGeo/gdal/pull/3430
On reading, the general principle of most readers is to be tolerant as much as it is reasonable to be.

> Not sure what OGR should do though when applications like QGIS come up with 'local times', that is without any timezone indication.... Either find out the local timezone and write it to Zulutime?

See the DATETIME_FORMAT creation option documented at https://gdal.org/drivers/vector/gpkg.html

> Another option would be to write datetime as milliseconds since epoch? But that will probably too much for the spec to change?

That would be a breaking change, so yes you'd likely have to provide strong justification to the GeoPackage SWG.

> I also would not mind if OGR (and thus QGIS) would be more strict, and for example when data is not YYYY-MM-DDTHH:MM:SS.SSSZ formated in a DATETIME column, then show it as a STRING column..

I don't feel this is the right thing to do (readers should be lax), and furthermore it would have performance implications since you'd have to scan the table content at file opening to determine if the content is strictly compliant or not. So imagine a 10 GB geopackage file...

**Comment by jratike80** [comment] 2021-02-03 10:40
Some opinions:
- I would say that GDAL should write times always as `2019-09-02T02:00:00.000Z`.
- I am not sure about forcing constraints into user tables. At least it should be discussed here https://github.com/opengeospatial/geopackage first. You can create an issue and start discussion. The possible drawback is that users and other software do not have a uniform way for handling times. What if user has times with microsecond precision? Users who are keen on shapefile date format yyyy-mm-dd might be willing to be flexible with the standard and save them as such into data field. That feels too flexible for me, though.
- It is better not to fiddle much with the timezones. If the time is local time just add Z. Most users would certainly consider that it is an error if GDAL would automatically change not only hours but also dates around the midnight. It may even be that most users actually want to store local datetime values as-is into GeoPackage and Z is just something that must be there.
- I can't say much about the temporal controller of QGIS. I am using OGR generated GeoPackages and datetimes for storing the time dimension for Mapserver and WMS-T and it works well.

**Comment by jratike80** [comment] 2021-02-03 10:52
Now I have something to say about the QGIS temporal controller. Perhaps it should use the SQLite time functions instead of making plain string comparisons. https://sqlite.org/lang_datefunc.html

```
select strftime
('%Y-%m-%dT%H:%M:%fZ',
'2019-09-01T06:00:00')

2019-09-01T06:00:00.000Z
```

**Comment by rduivenvoorde** [comment] 2021-02-03 10:52
Thanks @rouault for this fix!

@jratike80 
> I would say that GDAL should write times always as 2019-09-02T02:00:00.000Z.

+1

you mean nanosecond precision? .001 is already microsecond. I'm also keen to know how postgres is handling this. For what I know they store mssinceepoch and the client libs then convert and show the Timezones, that is why I am proposing the epoch as stored data.

Thinking about gpkg-using applications now (like QGIS) which uses (my real world work example): we use Geoserver-created geopackages, to be shown in QGIS with temporal controller.
No way I can find out before sending the filter query which kind of format is in the geopackage (and besides, as we use the filter query for all data formats, you do not want to make assumptions about those.

As always: IF the standard is not very very clear about formats, things get messy between different applications... And handling timezones are HELL, I agree, so I'm OK to keep them out of the gpkg spec :-)

I'll have a look at the timezone handling of mapserver. My issues are in corner cases like: showing 1 hourly data in steps of 1 hour... and then the limits are an issue.

**Comment by jratike80** [comment] 2021-02-03 11:03
Isn't 1/1000 part called "milli"? What I was thinking was timestamps like `timeStamp: "2021-02-02T11:28:43.116966Z"` that faced just yesterday. The precision in this case does not reflect real world phenomena but some hard scientists may use GeoPackage as well.

I stay with Finnish local time and I do not care about the daylight savings. I do not know how Mapserver deals with timezones but I have not had problems with ISO time strings. However, our environment is controlled and I may not see the whole image.

**Comment by rduivenvoorde** [comment] 2021-02-03 11:27
> Perhaps it should use the SQLite time functions instead of making plain string comparisons. 

I thought that would only work if you know on beforehand the exact format (aka ONLY when the exact spec format could be used), but I tested, and the datetime function is very forgiving...

BUT (note my .010 second part) it looks like the franctional seconds are always lost:

```
select STRFTIME('%Y-%m-%d %H:%M:%S.%fZ', datetime("2019-09-01 08:00:00.010Z") )
2019-09-01 08:00:00.00.000Z
```

These 'queries' coming from the Time Controller, are being used for ALL data formats, not sure if it always is allowed to use sqlite functions?

> Isn't 1/1000 part called "milli"? 

Ah yes, sorry my mistake..

**Comment by jratike80** [comment] 2021-02-03 11:43
It was the first time I have ever used SQLite strftime.

It seems that string comparisons are actually the way to go if the fractional seconds have more than 3 digits
https://stackoverflow.com/questions/35850729/sqlite-and-fractional-seconds-comparison-in-datetime 

Up till 3 digits is seems to work and this gives "false"

`SELECT strftime('%Y-%m-%d %H:%M:%f', '2013-10-07 08:23:19.111') = strftime('%Y-%m-%d %H:%M:%f', '2013-10-07 08:23:19.112')`

Have you also tested Time Controller with XML/GML data that can in a standard compliant way (I mean GML standard) contain different variants of ISO time strings? WFS may not be an option for Time Controller.

**Comment by rduivenvoorde** [comment] 2021-02-03 11:49
Yep, and that is what GDAL is doing, but that only works if there is just ONE datetime string format. 
That is why I propose to be very strict in the format (and even put constraints on it...).

**Comment by jratike80** [comment] 2021-02-03 12:04
I wonder what your test is testing. SQLite documents that datetime drops the fractional part of seconds and is actually just an alias for strftime with the following parameters: 

`datetime(...) |   | strftime('%Y-%m-%d %H:%M:%S', ...)
`

**Closed** 2021-02-04 16:25 UTC
