### ISSUE TITLE
pixel values inconsistencies when downsampling a large jp2 input file into a tif output file 

### ISSUE THREAD

**Issue by zachariebd2** [OSGeo/gdal#6274] opened 2022-08-30 14:33 UTC
## Expected behavior and actual behavior.

I am using gdal to downsample a Sentinel-2 L1C band jp2 file (10980 x 10980 pixels) and to change it's format from jp2 to tif.

I am using three methods :
A) one gdalwarp command for downsampling (average) a Sentinel-2 L1C band jp2 file and converting the format from a jp2 file to a tif file
B) a first gdalwarp command for converting the format followed by a second gdalwarp command for downsampling
C) a first gdalwarp command for downsampling followed by a second gdalwarp command for converting the format

The problem is the same with gdal_translate

I expected the three methods to give output images with the exact same pixel values.

Instead methods A, B and C each give different results

From the sentinel-2 file T31TCH_20190126T105321_B02.jp2 with a minimum value of 1 and a maximum value of 28000:

Method A produce a raster with a minimum value of 0 (which doesn't seems possible with an averaging from 10m to 20m) and a maximum of 24329.
Method B produce a raster with a minimum value of 759 (more in line with an expected result) and a maximum of 18119.
Method C produce a raster with a minimum of 0 and a maximum of 24313.

## Steps to reproduce the problem.

The Sentinel-2 file can be found here: https://zenodo.org/record/7032203#.Yw4OrNXP1H4

commands used for each method:

A) gdalwarp -r average -tr 20 20 T31TCH_20190126T105321_B02.jp2 10m_to_20m_jp2_to_tif.tif

B) gdalwarp T31TCH_20190126T105321_B02.jp2 10m_jp2_to_tif.tif
     gdalwarp -r average -tr 20 20 10m_jp2_to_tif.tif 10m_to_20m_jp2_to_tif.tif
   
C) gdalwarp -r average -tr 20 20 T31TCH_20190126T105321_B02.jp2 10m_to_20m_jp2.jp2      
     gdalwarp  10m_to_20m_jp2.jp2 10m_to_20m_jp2_to_tif.tif
   

## Operating system

RedHat 7 64 bits

## GDAL version and provenance

tried with gdal 2.3.0 and with gdal 3.3.1  from conda-forge-remote

**Comment by tbonfort** [comment] 2022-08-30 14:41
Downsampling from a jp2 directly will get pixel values from the downsampled jp2 wavelets whose values are *not* the average of the higher resolution pixels, but "some" value which may be close to the average value, or could be completely outside the range of the higher res values. TLDR: consider downsampled jp2 data to be for illustrative purposes only (even that case is not always possible, as the downsampled values may become the "nodata" value)

**Comment by jratike80** [comment] 2022-08-30 14:46
Try this gdalwarp https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-ovr

> To specify which overview level of source files must be used. The default choice, AUTO, will select the overview level whose resolution is the closest to the target resolution. Specify an integer value (0-based, i.e. 0=1st overview level) to select a particular level. Specify AUTO-n where n is an integer greater or equal to 1, to select an overview level below the AUTO one. Or specify NONE to force the base resolution to be used (can be useful if overviews have been generated with a low quality resampling method, and the warping is done using a higher quality resampling method).

**Comment by rouault** [comment] 2022-08-31 14:19
duplicate of https://github.com/OSGeo/gdal/issues/1484
documentation enhancement submitted in https://github.com/OSGeo/gdal/pull/6286

**Closed** 2022-08-31 17:44 UTC

**Comment by zachariebd2** [comment] 2022-09-01 10:59
Thank you @jratike80 and @tbonfort this has helped me. The option -ovr NONE has solved my problem.
