### ISSUE TITLE
GDAL produces empty output from OSM file

### ISSUE THREAD

**Issue by mobigroup** [OSGeo/gdal#1785] opened 2019-08-16 18:00 UTC
## Expected behavior and actual behavior.

That's works without option OGR_INTERLEAVED_READING for small OSM files but for large files this error generating: 
"ERROR 1: Too many features have accumulated in points layer. Use OGR_INTERLEAVED_READING=YES mode"
With this option the processing works only for "points" layer. For layers "lines", etc. it produces empty output.

Upd. See the list of 5 available layers by this link:
https://gdal.org/drivers/vector/osm.html

## Steps to reproduce the problem.

```
wget -c http://download.geofabrik.de/europe/germany-latest.osm.pbf
ogr2ogr -f SQLite lines.sqlite germany-latest.osm.pbf \
    --config OGR_INTERLEAVED_READING YES \
    -dialect sqlite -sql "select * from lines"
sqlite3 germany-latest.osm.pbf-lines.sqlite '.tables'
geometry_columns  spatial_ref_sys 
```
As we can see there is no the output table.

## Operating system

MacOS Mojave 10.14.6 (18G87)

## GDAL version and provenance

GDAL 2.4.2, released 2019/06/28

**Comment by rouault** [comment] 2019-08-17 08:09
I have tried with a few .osm.pbf files I have around including an old france-latest.osm.pbf and can't reproduce any issue. So perhaps something with this germany-latest.pbf

**Comment by mobigroup** [comment] 2019-08-17 10:59
Ah, thanks, that's works with other large dumps! Could you advice how to trace similar errors? "-skipfailures" doesn't help at this case.

**Comment by rouault** [comment] 2019-08-17 12:55
I can't reproduce this with germany-latest.osm.pbf either. Note that with recent versions of GDAL (2.4 is sufficient), --config OGR_INTERLEAVED_READING YES  is not needed with ogr2ogr.
Is there no error message spit out by ogr2ogr ? You can perhaps try adding `--debug on` to see if something interesting shows up

**Comment by mobigroup** [comment] 2019-08-20 05:33
Without "--config OGR_INTERLEAVED_READING YES" sometimes I see this warning even for recent GDAL versions:
"ERROR 1: Too many features have accumulated in points layer. Use OGR_INTERLEAVED_READING=YES mode". 

There are no errors for the redownloaded germany-latest.osm.pbf Before it was stopped on log line

OSM: Ways processed : ...

without other information.

**Comment by rouault** [comment] 2019-08-20 11:45
> There are no errors for the redownloaded germany-latest.osm.pbf

That is: the conversion succeeds ?

**Comment by mobigroup** [comment] 2019-08-21 18:05
Yes, that's ok now.

**Comment by rouault** [comment] 2019-08-21 18:09
OK. Closing then

**Closed by rouault** 2019-08-21 18:09 UTC
Labels: awaiting_feedback

**Comment by Robinlovelace** [comment] 2019-10-10 10:47
Follow-up question: we are seeing a warning message asking use to use INTERLEAVED_READING but it seems that is not supported in GDAL 2.4.1. See here: https://github.com/ITSLeeds/geofabric/issues/12#issuecomment-540512123

Heads-up @rouault and many thanks for creating this fast and flexible open source geographic data reading library.
