### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005) with gdal.RasterizeLayer

### ISSUE THREAD

**Issue by mwalvarenga** [OSGeo/gdal#2869] opened 2020-08-19 13:32 UTC
Hi! I am quite new to python and I am experiencing an issue when calling the function **gdal.RasterizeLayer**

I have a quite long script but, summarizing, I am calling the function like this:

    status = gdal.RasterizeLayer(dataset=out_raster_ds,  # output to our new dataset
                                 bands=[1],  # output to our new dataset's first band
                                 layer=ordered_watershed,  # rasterize this layer
                                 #pfnTransformer=None,
                                 #pTransformArg=None,
                                 burn_values=[0],
                                 options=[
                                     'ALL_TOUCHED=TRUE',  # rasterize all pixels touched by polygons
                                     'ATTRIBUTE=CatchID',  # put raster values according to the 'CatchID' field values
                                 ],
                                 callback=0,
                                 callback_data=None
                                 )
    print('rasterization 14')

    if status != 0:
        raise RuntimeError("Rasterization failed")

After running the whole script succesfully once (it is called several times), in the second (next) iteration I get the error when calling this function: 

**Process finished with exit code -1073741819 (0xC0000005)**

It is quite weird since I don't know exactly what is going wrong (there are no errors trace). 
Googling it brings up several solutions which I have tried but without success. 
Do you know this issue? How can it be solved?

Thanks in advance.

I am using Windows 10 64x 
Python 3.7.5
numpy           1.19.1+mkl
GDAL            3.1.2
Rtree           0.9.4

**Comment by rouault** [comment] 2020-08-19 13:44
Please provide a self contained reproducer (python script + input data)

**Comment by mwalvarenga** [comment] 2020-08-19 16:14
Hi @rouault, I extracted the part of my code that is failing and attach it here. I requires the `shp` and `tif` files which is also in the `zip`. To reproduce, unzip and run `rasterization_debug.py`. I also paste the same code which is in the python file below.

It turns out that running the code only ones works but as calling the functions multiple times (see for-loop at end of script) casuses the crash.

[mwe_files.zip](https://github.com/OSGeo/gdal/files/5097723/mwe_files.zip)

```python
import gdal
gdal.UseExceptions()
from osgeo import ogr
import os

path_watershed_shp = 'watersheds.shp'
path_filled = 'DEM_filled.tif'
path_watershed_dem = 'watershed_dem.tif'

def order_watershed():
    """
        This function sorts the features in the watershed.shp in a decreasing area order. In the rasterization,
        this step allows to not loose the small watersheds that could be overlappped by the biggest ones, as
        in the raterization process the last value at the corresponding pixel is taken into account.

        :param: None
        :return: ordered_watershed
    """

    # Open the data source file
    ogr.UseExceptions()  # if something goes wrong, we want to know about it
    driver = ogr.GetDriverByName('ESRI Shapefile')
    ds = driver.Open(path_watershed_shp, 0)  # 0--read-only

    layer = ds.GetLayer()
    layerName = layer.GetName()  # returns string 'three_points'
    ordered_watershed = ds.ExecuteSQL('select * from "%s" order by Area DESC' % layerName)


    return ordered_watershed


def rasterize_watershed(ordered_watershed):
    """
            This function rasterizes the watershed. In the rasterization process the last value at the corresponding
            pixel is taken into account (that is why the order_watershed is done before).

            :param: None
            :return:
    """
    print('rastarization starts')
    driver = ogr.GetDriverByName('ESRI Shapefile')
    print('rastarization 1')
    ds = driver.Open(path_watershed_shp, 0)  # 0--read-only
    print('rastarization 2')
    # First we will open our raster image, to understand how we will want to rasterize our vector
    raster_ds = gdal.Open(path_filled, gdal.GA_ReadOnly)
    print('rastarization 3')
    # Fetch number of rows and columns
    ncol = raster_ds.RasterXSize
    print('rastarization 4')
    nrow = raster_ds.RasterYSize
    print('rastarization 5')

    # Fetch projection and extent
    proj = raster_ds.GetProjectionRef()
    print('rastarization 6')
    ext = raster_ds.GetGeoTransform()
    print('rastarization 7')

    raster_ds = None

    # Create the raster dataset
    memory_driver = gdal.GetDriverByName('GTiff')
    print('rastarization 8')
    if os.path.exists(path_watershed_dem):
        os.remove(path_watershed_dem)
    out_raster_ds = memory_driver.Create(path_watershed_dem, ncol, nrow, 1, gdal.GDT_UInt32)
    print('rastarization 9')

    # Set the ROI image's projection and extent to our input raster's projection and extent
    out_raster_ds.SetProjection(proj)
    print('rastarization 10')
    out_raster_ds.SetGeoTransform(ext)
    print('rastarization 11')

    # Fill our output band with the 0 blank, no class label, value
    b = out_raster_ds.GetRasterBand(1)
    print('rastarization 12')
    b.Fill(0)
    print('rastarization 13')
    # Rasterize the shapefile layer to our new dataset

    status = gdal.RasterizeLayer(dataset=out_raster_ds,  # output to our new dataset
                                 bands=[1],  # output to our new dataset's first band
                                 layer=ordered_watershed,  # rasterize this layer
                                 #pfnTransformer=None,
                                 #pTransformArg=None,
                                 burn_values=[0],
                                 options=[
                                     'ALL_TOUCHED=TRUE',  # rasterize all pixels touched by polygons
                                     'ATTRIBUTE=CatchID',  # put raster values according to the 'CatchID' field values
                                 ],
                                 callback=0,
                                 callback_data=None
                                 )
    print('rastarization 14')
    if status != 0:
        raise RuntimeError("Rasterization failed")

for _ in range(10):
    ordered_watershed = order_watershed()
    rasterize_watershed(ordered_watershed)
```

**Comment by rouault** [comment] 2020-08-19 18:48
You've run into one of the https://gdal.org/api/python_gotchas.html of the Python API.
Once a dataset goes out of scope, its related C++ objects like layers are also destroyed, so ordered_watershed is no longer valid. Fix: return the dataset object itself. And a layer got with ExecuteSQL() must be released with ds.ReleaseResultSet(lyr)

Corrected script:
```python
import gdal
gdal.UseExceptions()
from osgeo import ogr
import os

path_watershed_shp = 'watersheds.shp'
path_filled = 'DEM_filled.tif'
path_watershed_dem = 'watershed_dem.tif'

def order_watershed():
    """
        This function sorts the features in the watershed.shp in a decreasing area order. In the rasterization,
        this step allows to not loose the small watersheds that could be overlappped by the biggest ones, as
        in the raterization process the last value at the corresponding pixel is taken into account.

        :param: None
        :return: ordered_watershed
    """

    # Open the data source file
    ogr.UseExceptions()  # if something goes wrong, we want to know about it
    driver = ogr.GetDriverByName('ESRI Shapefile')
    ds = driver.Open(path_watershed_shp, 0)  # 0--read-only

    layer = ds.GetLayer()
    layerName = layer.GetName()  # returns string 'three_points'
    ordered_watershed = ds.ExecuteSQL('select * from "%s" order by Area DESC' % layerName)


    return ds, ordered_watershed


def rasterize_watershed(ordered_watershed):
    """
            This function rasterizes the watershed. In the rasterization process the last value at the corresponding
            pixel is taken into account (that is why the order_watershed is done before).

            :param: None
            :return:
    """
    print('rastarization starts')
    driver = ogr.GetDriverByName('ESRI Shapefile')
    print('rastarization 1')
    ds = driver.Open(path_watershed_shp, 0)  # 0--read-only
    print('rastarization 2')
    # First we will open our raster image, to understand how we will want to rasterize our vector
    raster_ds = gdal.Open(path_filled, gdal.GA_ReadOnly)
    print('rastarization 3')
    # Fetch number of rows and columns
    ncol = raster_ds.RasterXSize
    print('rastarization 4')
    nrow = raster_ds.RasterYSize
    print('rastarization 5')

    # Fetch projection and extent
    proj = raster_ds.GetProjectionRef()
    print('rastarization 6')
    ext = raster_ds.GetGeoTransform()
    print('rastarization 7')

    raster_ds = None

    # Create the raster dataset
    memory_driver = gdal.GetDriverByName('GTiff')
    print('rastarization 8')
    if os.path.exists(path_watershed_dem):
        os.remove(path_watershed_dem)
    out_raster_ds = memory_driver.Create(path_watershed_dem, ncol, nrow, 1, gdal.GDT_UInt32)
    print('rastarization 9')

    # Set the ROI image's projection and extent to our input raster's projection and extent
    out_raster_ds.SetProjection(proj)
    print('rastarization 10')
    out_raster_ds.SetGeoTransform(ext)
    print('rastarization 11')

    # Fill our output band with the 0 blank, no class label, value
    b = out_raster_ds.GetRasterBand(1)
    print('rastarization 12')
    b.Fill(0)
    print('rastarization 13')
    # Rasterize the shapefile layer to our new dataset

    status = gdal.RasterizeLayer(dataset=out_raster_ds,  # output to our new dataset
                                 bands=[1],  # output to our new dataset's first band
                                 layer=ordered_watershed,  # rasterize this layer
                                 #pfnTransformer=None,
                                 #pTransformArg=None,
                                 burn_values=[0],
                                 options=[
                                     'ALL_TOUCHED=TRUE',  # rasterize all pixels touched by polygons
                                     'ATTRIBUTE=CatchID',  # put raster values according to the 'CatchID' field values
                                 ],
                                 callback=0,
                                 callback_data=None
                                 )
    print('rastarization 14')
    if status != 0:
        raise RuntimeError("Rasterization failed")

for _ in range(10):
    ds, ordered_watershed = order_watershed()
    rasterize_watershed(ordered_watershed)
    ds.ReleaseResultSet(ordered_watershed)
```

**Closed by rouault** 2020-08-19 18:48 UTC
Labels: awaiting_feedback

**Comment by AckslD** [comment] 2020-08-20 10:01
Nice work finding the issue @rouault :) I was wondering, why does not `gdal.UseExceptions` work in this case?

**Comment by rouault** [comment] 2020-08-20 10:12
> why does not `gdal.UseExceptions` work in this case?

The issue here is about not-so-ideal memory management between C++ and Python.
gdal.UseExceptions() is not a aware of that issue, and is only used when a GDAL C function returns an error code, to translate it into a Python exception. But here due to the misuse of the C++ code, the process just crashes in native code

**Comment by mwalvarenga** [comment] 2020-08-20 11:16
Hey @rouault ! Thanks a lot for debugging and finding a fix for it :)
