### ISSUE TITLE
3.1.3: build fails

### ISSUE THREAD

**Issue by kloczek** [OSGeo/gdal#3030] opened 2020-10-08 04:53 UTC
```
  C++14 support:             no

  LIBTOOL support:           yes

  LIBZ support:              external
  LIBLZMA support:           yes
  ZSTD support:              yes
  cryptopp support:          no
  crypto/openssl support:    yes
  GRASS support:             no
  CFITSIO support:           external
  PCRaster support:          internal
  LIBPNG support:            external
  DDS support:               no
  GTA support:               yes
  LIBTIFF support:           external (BigTIFF=yes)
  LIBGEOTIFF support:        external
  LIBJPEG support:           external
  12 bit JPEG:               no
  12 bit JPEG-in-TIFF:       no
  LIBGIF support:            external
  JPEG-Lossless/CharLS:      yes
  OGDI support:              yes
  HDF4 support:              no
  HDF5 support:              yes
  Kea support:               no
  NetCDF support:            no
  Kakadu support:            no
  JasPer support:            yes (GeoJP2=no)
  OpenJPEG support:          yes
  ECW support:               no
  MrSID support:             no
  MrSID/MG4 Lidar support:   no
  JP2Lura support:           no
  MSG support:               no
  EPSILON support:           no
  WebP support:              yes
  cURL support (wms/wcs/...):yes
  PostgreSQL support:        yes
  LERC support:              yes
  MySQL support:             yes
  Ingres support:            no
  Xerces-C support:          yes
  Expat support:             yes
  libxml2 support:           yes
  Google libkml support:     yes
  ODBC support:              yes
  FGDB support:              no
  MDB support:               no
  PCIDSK support:            internal
  OCI support:               no
  GEORASTER support:         no
  SDE support:               no
  Rasdaman support:          no
  RDB support:               no
  DODS support:              yes
  SQLite support:            yes
  PCRE support:              yes
  SpatiaLite support:        yes
  RasterLite2 support:       no
  Teigha (DWG and DGNv8):    no
  INFORMIX DataBlade support:no
  GEOS support:              yes
  SFCGAL support:            no
  QHull support:             external
  Poppler support:           yes
  Podofo support:            no
  PDFium support:            no
  OpenCL support:            no
  Armadillo support:         yes
  FreeXL support:            yes
  SOSI support:              no
  MongoDB support:           no
  MongoCXX v3 support:       no
  HDFS support:              no
  TileDB support:            no
  EXR support:               yes
  userfaultfd support:       yes
  misc. gdal formats:        aaigrid adrg aigrid airsar arg blx bmp bsb cals ceos ceos2 coasp cosar ctg dimap dted e00grid elas envisat ers fit gff gsg gxf hf2 idrisi ignfheightasciigrid ilwis ingr iris iso8211 jaxapalsar jdem kmlsuperoverlay l1b leveller map mrf msgn ngsgeoid nitf northwood pds prf r raw rmf rs2 safe saga sdts sentinel2 sgi sigdem srtmhgt terragen til tsx usgsdem xpm xyz zmap rik ozi grib eeda plmosaic rda wcs wms wmts daas rasterlite mbtiles pdf
  disabled gdal formats:
  misc. ogr formats:         aeronavfaa arcgen avc bna cad csv dgn dxf edigeo flatgeobuf geoconcept georss gml gmt gpsbabel gpx gtm htf jml mapml mvt ntf openair openfilegdb pgdump rec s57 segukooa segy selafin shape sua svg sxf tiger vdv wasp xplane idrisi pds sdts nas ili gmlas ods xlsx odbc pgeo mssqlspatial geomedia walk amigocloud carto cloudant couchdb csw elastic ngw plscenes wfs gpkg vfk osm
  disabled ogr formats:


  SWIG Bindings:             no

  PROJ >= 6:                 yes
  enable GNM building:       yes
  enable pthread support:    yes
  enable POSIX iconv support:yes
  hide internal symbols:     no
```
```
make[2]: Entering directory '/home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/frmts/jpeg2000'
/bin/sh /home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/libtool --mode=compile --silent --tag=CXX g++ -I/home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/port -I/home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/gcore -I/home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/alg -I/home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/ogr -I/home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/ogr/ogrsf_frmts -I/home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/gnm -I/home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/apps -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto=auto -flto-partition=none  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wduplicated-cond -Wextra-semi -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wsuggest-override -Wimplicit-fallthrough   -DGNM_ENABLED -I/home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/port -I/usr/include/openjpeg-2.3  -I/usr/include/cfitsio  -DGDAL_COMPILATION -DHAVE_XERCES -I/usr/include -I/usr/include/xercesc -I/home/tkloczko/rpmbuild/BUILD/gdal-3.1.3/port -I/usr/include/openjpeg-2.3  -I/usr/include/cfitsio  -DGDAL_COMPILATION -c -o ../o/jpeg2000_vsil_io.lo jpeg2000_vsil_io.cpp
jpeg2000_vsil_io.cpp:151:5: error: invalid conversion from ‘int (*)(jas_stream_obj_t*, char*, unsigned int)’ {aka ‘int (*)(void*, char*, unsigned int)’} to ‘int (*)(jas_stream_obj_t*, const char*, unsigned int)’ {aka ‘int (*)(void*, const char*, unsigned int)’} [-fpermissive]
  151 |     JPEG2000_VSIL_write,
      |     ^~~~~~~~~~~~~~~~~~~
      |     |
      |     int (*)(jas_stream_obj_t*, char*, unsigned int) {aka int (*)(void*, char*, unsigned int)}
make[2]: *** [../../GDALmake.opt:649: ../o/jpeg2000_vsil_io.lo] Error 1
```

**Comment by rouault** [comment] 2020-10-08 08:53
Duplicate of https://github.com/OSGeo/gdal/issues/3012

**Closed by rouault** 2020-10-08 08:53 UTC

**Comment by kloczek** [comment] 2020-10-08 10:24
BTW IMO it wold be good to split gdal and autotest into two repos or merge them pernmanently up to dist tar balls, or starting care to not commit sinhgle commits across those two directories because curretly it is really hard to pick exact subset of git patches to fix some issues which are already fixed in git repo.

Do you have any plans to make new 3.1.x release soon? (I see that more issues has been sorted out on 3.1 branch)

**Comment by rouault** [comment] 2020-10-08 12:09
> BTW IMO it wold be good to split gdal and autotest into two repos or merge them pernmanently up to dist tar balls, or starting care to not commit sinhgle commits across those two directories because curretly it is really hard to pick exact subset of git patches to fix some issues which are already fixed in git repo.

Every choice has trade offs, but having single commits with code change + related test is a major plus as a developer when investigating the impact of a code change.

> Do you have any plans to make new 3.1.x release soon?

Probably end of this month

**Comment by kloczek** [comment] 2020-10-08 12:13
> Every choice has trade offs, but having single commits with code change + related test is a major plus as a developer when investigating the impact of a code change.

Looking on the code I think that the best would be just move gdal/* level up to have autotest/ as subdirectory.
