### ISSUE TITLE
Fails to build with poppler 20.09.0

### ISSUE THREAD

**Issue by sebastic** [OSGeo/gdal#2921] opened 2020-09-04 09:54 UTC
The most recent package build in Debian unstable with poppler 20.09.0 failed.

The build log shows many errors like this:
```
<command-line>: error: invalid digit "9" in octal constant
pdfio.h:54:35: note: in expansion of macro ‘POPPLER_MINOR_VERSION’
   54 | #if POPPLER_MAJOR_VERSION >= 1 || POPPLER_MINOR_VERSION >= 69
      |                                   ^~~~~~~~~~~~~~~~~~~~~
```
[Full buildlog](https://buildd.debian.org/status/fetch.php?pkg=gdal&arch=amd64&ver=3.1.2%2Bdfsg-1%2Bb4&stamp=1599209863&file=log)

**Comment by rouault** [comment] 2020-09-04 10:07
Yes, you need 2b863dbabdc2a7d724f9fdf3e6ff20a142b619f6 that went 3.1.3
Closing as duplicate of #2823

**Closed by rouault** 2020-09-04 10:07 UTC
