### ISSUE TITLE
Shapefile throws an error in gdal.Warp()

### ISSUE THREAD

**Issue by mvanklink** [OSGeo/gdal#1659] opened 2019-06-19 08:31 UTC
## Expected behavior and actual behavior.

For a specific shapefile ``gdal.Warp()`` throws the following error in ``gdal`` version ``2.4.1`` but not in other ``gdal`` versions.

```
ERROR 1: IllegalArgumentException: Points of LinearRing do not form a closed linestring
ERROR 1: Cutline polygon is invalid.
```

## Steps to reproduce the problem.

Attached a zip file containing the shapefile and a small sample script with a sample input file
[error.zip](https://github.com/OSGeo/gdal/files/3305121/error.zip)

## Operating system
macOS Mojave 10.14.4 (also tested on Linux Debian)

## GDAL version and provenance
``2.4.1`` throws the error and ``2.4.0`` does not (``3.0.0`` also does not throw the error)

**Comment by rouault** [comment] 2019-06-19 09:08
This works now in the top of the 2.4 branch (future 2.4.2). So this is likely a duplicate of https://github.com/OSGeo/gdal/issues/1626#issuecomment-499869161

**Closed by rouault** 2019-06-19 09:08 UTC
Labels: duplicate
