### ISSUE TITLE
gdaladdo -r mode not working on large tif

### ISSUE THREAD

**Issue by radouxju** [OSGeo/gdal#7208] opened 2023-02-09 09:40 UTC
## Expected behavior and actual behavior.

I expected to build pyramids on my bigtiff raster (uint8) using the "mode" option. It works with gdal/2.2.4 but it fails with gdal/3.5.4 

The error message is : 

0ERROR 6: GDALRegenerateOverviewsMultiBand: pszResampling='mode' not supported
...10...20...30...40...50...60...70...80...90...100 - done.
Overview building failed.

but my file is a single band uint8 image. 

Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 2372200.000, 5416200.000) ( 36d 5'47.34"W, 65d42'37.55"N)
Lower Left  ( 2372200.000, 1425350.000) ( 10d58'55.30"W, 33d28' 5.99"N)
Upper Right ( 6061000.000, 5416200.000) ( 52d24'38.11"E, 66d50'19.82"N)
Lower Right ( 6061000.000, 1425350.000) ( 28d48' 8.48"E, 33d57'11.96"N)
Center      ( 4216600.000, 3420775.000) (  8d24'44.96"E, 53d53' 1.84"N)
Band 1 Block=256x256 Type=Byte, ColorInterp=Gray

## Steps to reproduce the problem.

gdaladdo myfile.tif -r mode

## Operating system

Open SUSE 15.4

## GDAL version and provenance

gdal/3.5.4

**Comment by jratike80** [comment] 2023-02-09 13:25
Works for me with bigger image as well. Normal and BigTIFF both tested:
`gdal_create -of GTiff -co tiled=yes -co compress=LZW -outsize 100000 100000 -co bigtiff=yes addotest.tif`
By the error message that you get gdaladdo wants to use GDALRegenerateOverviewsMultiBand(), and the current code should not give an error about "mode":

https://github.com/OSGeo/gdal/blob/master/gcore/overview.cpp#L4870

What is your GDAL version and exact gdaladdo command?

**Comment by rouault** [comment] 2023-02-09 17:32
This is a duplicate of #6587 that was fixed per https://github.com/OSGeo/gdal/pull/6589 in GDAL 3.6.0

**Closed by rouault** 2023-02-09 17:32 UTC
