### ISSUE TITLE
Polygon in dxf, after ogr2ogr, got lingstring in geojson

### ISSUE THREAD

**Issue by mumumi** [OSGeo/gdal#10153] opened 2024-06-07 09:39 UTC
### What is the bug?

[dxf.zip](https://github.com/user-attachments/files/15730961/dxf.zip)
There are two polygon shapes in the dxf attachment. The shape with more points calls shapeA, the other one calls shapeB.
Got linestrings after converting.

### Steps to reproduce the issue

Test a. With command "ogr2ogr -f GeoJSON test.json test.dxf -nlt POLYGON", shapeB output as polygon, shapeA output as linestring. The last point of the linestring has a different y from the first point.
Test b. using nuget gdal in c#, after getting geojson driver, creating data source, opening dxf data source, copying layer from the dxf, i got two linestrings. creating multilinestring geometries to containing each linestring, using function polygonize, shapeA got null and shapeB got an empty geometry collection

### Versions and provenance

nuget GDAL-3.8.5
binary 3.6.2

**Comment by atlight** [comment] 2024-06-07 10:22
> ### Steps to reproduce the issue
> Test a. With command "ogr2ogr -f GeoJSON test.json test.dxf -nlt POLYGON", shapeB output as polygon, shapeA output as linestring. The last point of the linestring has a different y from the first point. 

This sounds like correct, expected behaviour to me. What output were you expecting?

> Test b. using nuget gdal in c#, after getting geojson driver, creating data source, opening dxf data source, copying layer from the dxf, i got two linestrings. creating multilinestring geometries to containing each linestring, using function polygonize, shapeA got null and shapeB got an empty geometry collection

Can you please post a code sample and explain why you believe the output is incorrect?

**Comment by jratike80** [comment] 2024-06-07 10:30
In the DXF data both entities are closed polylines (AcDbPolyline). Therefore they could be converted into polygons (but I do not know if the `-nlt` option in ogr2ogr is supposed to be able to cast linestrings/linear rings into polygons).

This is the entity that remains as linestring when converted into GeoJSON

```
EntityHandle (String) = 215
  LINESTRING (40585366.7065058 3433935.53809098,40585329.9256486 3433998.44081707,40585329.9256486 3433998.44081707,40585328.5387678 3434000.63680805,40585327.0051198 3434002.73293274,40585325.3318693 3434004.71939884,40585323.526833 3434006.58692634,40585321.5984435 3434008.32679087,40585319.5557093 3434009.93086443,40585317.4081735 3434011.39165342,40585315.1658683 3434012.70233358,40585312.8392691 3434013.85678191,40585310.4392448 3434014.84960528,40585307.9770074 3434015.67616559,40585305.4640596 3434016.33260146,40585302.9121409 3434016.81584629,40585300.3331728 3434017.12364253,40585297.7392033 3434017.25455227,40585271.1313178 3434017.68678191,40585252.1698149 3433885.99037548,40585256.74147 3433885.9161116,40585256.74147 3433885.9161116,40585266.2920614 3433886.0916242,40585275.8076317 3433886.92740148,40585285.2425893 3433888.41943902,40585294.551729 3433890.56058809,40585303.6904483 3433893.34058991,40585312.6149614 3433896.74612477,40585321.2825086 3433900.76087591,40585329.6515615 3433905.36560764,40585364.2483736 3433925.99220872,40585364.2483736 3433925.99220872,40585364.6481964 3433926.24937651,40585365.0296424 3433926.53308859,40585365.3909523 3433926.84203644,40585365.7304596 3433927.17479516,40585366.0465985 3433927.52983003,40585366.337911 3433927.90550359,40585366.6030535 3433928.30008319,40585366.840803 3433928.71174899,40585367.0500632 3433929.13860232,40585367.2298688 3433929.5786745,40585367.3793906 3433930.02993587,40585367.4979389 3433930.49030515,40585367.5849671 3433930.95765907,40585367.6400736 3433931.42984214,40585367.6630045 3433931.9046766,40585367.6536538 3433932.37997246,40585367.6120647 3433932.85353759,40585367.5384291 3433933.32318787,40585367.4330866 3433933.7867572,40585367.2965229 3433934.24210757,40585367.129368 3433934.68713883,40585366.9323928 3433935.11979846,40585366.7065058 3433935.53809098)
```

**Comment by jratike80** [comment] 2024-06-07 10:54
I do not understand why the first polygon looks like not closed. Could there be some problem with closing the linestring, inaccurate floating point computing or something? If I understand right DXF does not contain the closing vertex, but the polyline flag 1 = Closed is telling that.

```
ogrinfo test.dxf -dialect sqlite -sql "select isclosed(geometry) as geometry from entities"
INFO: Open of `test.dxf'
      using driver `DXF' successful.

Layer name: SELECT
Geometry: None
Feature Count: 2
Layer SRS WKT:
(unknown)
geometry: Integer (0.0)
OGRFeature(SELECT):0
  geometry (Integer) = 0

OGRFeature(SELECT):1
  geometry (Integer) = 1
```

**Comment by jratike80** [comment] 2024-06-07 11:03
The coordinates in the DXF file do not match with the output of ogrinfo. Here is a starting point in the DXF


```
AcDbPolyline
 90
        8
 70
   129
 43
0.5
 10
40585366.70650577
 20
3433935.538090975
```
This is the starting point as ogrinfo shows it:

`LINESTRING (40585366.7065058 3433935.53809098,`

Something happens when converting text into double and back, or? Is it even possible to avoid this, if numbers have a precision of 10^-7?

**Comment by mumumi** [comment] 2024-06-11 01:02
> > ### Steps to reproduce the issue
> > Test a. With command "ogr2ogr -f GeoJSON test.json test.dxf -nlt POLYGON", shapeB output as polygon, shapeA output as linestring. The last point of the linestring has a different y from the first point.
> 
> This sounds like correct, expected behaviour to me. What output were you expecting?
the original file is a dwg, two polygons composed of straight lines and arcs. they are not lines. they have area properties. Converting to dxf, tried autocad 2025, libredwg, oda file converter, the outputs are the same, with the same value of the first and the last point. The decimal places of both points have increased after being converted by GDAL, and the increased decimal parts have inconsistent values.
> 
> > Test b. using nuget gdal in c#, after getting geojson driver, creating data source, opening dxf data source, copying layer from the dxf, i got two linestrings. creating multilinestring geometries to containing each linestring, using function polygonize, shapeA got null and shapeB got an empty geometry collection
> 
> Can you please post a code sample and explain why you believe the output is incorrect?
The DWG file mentioned earlier is part of a larger file, all of which contains arcs. In DXF, shapes with arcs are displayed as polylines rather than polygons, but when opened with software like AutoCAD, they still have areas. Other shapes in the large file can all be converted from LineString to Polygon by the code, except for the two mentioned above. One reason is that the values of the first and last points became inconsistent after being loaded into GDAL, and a non-closed polyline will not be converted to a polygon by the code. The other one is unclear as to why it output an empty GeometryCollection.
`
var geomType = geom?.GetGeometryType();
if (geom != null && geomType.ToString().StartsWith("wkbLineString"))
{
    var firstPoint = new double[4];
    var lastPoint = new double[4];
    geom.GetPoint(0, firstPoint);
    geom.GetPoint(geom.GetPointCount() - 1, lastPoint);
    if (firstPoint.SequenceEqual(lastPoint))
    {
        using Geometry multiLineString = new((wkbGeometryType)((int)geomType + 3));
        multiLineString.AddGeometry(geom);
        using var g = multiLineString.Polygonize();
        if (g != null && !g.IsEmpty())
        {
            return g.GetGeometryType().ToString().StartsWith("wkbGeometryCollection") &&
                   g.GetGeometryCount() == 1
                ? g.GetGeometryRef(0).Clone()
                : g.Clone();
        }
    }
}

return null;
`

**Comment by mumumi** [comment] 2024-06-11 01:53
> In the DXF data both entities are closed polylines (AcDbPolyline). Therefore they could be converted into polygons (but I do not know if the `-nlt` option in ogr2ogr is supposed to be able to cast linestrings/linear rings into polygons). The documentation does not say that it should do that, but maybe it is just not documented.
> 
> This is the entity that remains as linestring when converted into GeoJSON
> 
> ```
> EntityHandle (String) = 215
>   LINESTRING (40585366.7065058 3433935.53809098,40585329.9256486 3433998.44081707,40585329.9256486 3433998.44081707,40585328.5387678 3434000.63680805,40585327.0051198 3434002.73293274,40585325.3318693 3434004.71939884,40585323.526833 3434006.58692634,40585321.5984435 3434008.32679087,40585319.5557093 3434009.93086443,40585317.4081735 3434011.39165342,40585315.1658683 3434012.70233358,40585312.8392691 3434013.85678191,40585310.4392448 3434014.84960528,40585307.9770074 3434015.67616559,40585305.4640596 3434016.33260146,40585302.9121409 3434016.81584629,40585300.3331728 3434017.12364253,40585297.7392033 3434017.25455227,40585271.1313178 3434017.68678191,40585252.1698149 3433885.99037548,40585256.74147 3433885.9161116,40585256.74147 3433885.9161116,40585266.2920614 3433886.0916242,40585275.8076317 3433886.92740148,40585285.2425893 3433888.41943902,40585294.551729 3433890.56058809,40585303.6904483 3433893.34058991,40585312.6149614 3433896.74612477,40585321.2825086 3433900.76087591,40585329.6515615 3433905.36560764,40585364.2483736 3433925.99220872,40585364.2483736 3433925.99220872,40585364.6481964 3433926.24937651,40585365.0296424 3433926.53308859,40585365.3909523 3433926.84203644,40585365.7304596 3433927.17479516,40585366.0465985 3433927.52983003,40585366.337911 3433927.90550359,40585366.6030535 3433928.30008319,40585366.840803 3433928.71174899,40585367.0500632 3433929.13860232,40585367.2298688 3433929.5786745,40585367.3793906 3433930.02993587,40585367.4979389 3433930.49030515,40585367.5849671 3433930.95765907,40585367.6400736 3433931.42984214,40585367.6630045 3433931.9046766,40585367.6536538 3433932.37997246,40585367.6120647 3433932.85353759,40585367.5384291 3433933.32318787,40585367.4330866 3433933.7867572,40585367.2965229 3433934.24210757,40585367.129368 3433934.68713883,40585366.9323928 3433935.11979846,40585366.7065058 3433935.53809098)
> ```
> 
> The first and last points in my GeoJSON linestrings are the same:
> 
> first: 40585366.7065058 3433935.53809098 last; 40585366.7065058 3433935.53809098
[dxf-dwg.zip](https://github.com/user-attachments/files/15780975/dxf-dwg.zip)
Polygons composed of straight lines are normally displayed as 'polygon' when converted to DXF format. However, if the polygon contains arcs, it will be displayed as a 'polyline' after conversion to DXF, but the software will still treat it as a polygon with an area.

**Comment by mumumi** [comment] 2024-06-11 01:59
> The coordinates in the DXF file do not match with the output of ogrinfo. Here is a starting point in the DXF
> 
> ```
> AcDbPolyline
>  90
>         8
>  70
>    129
>  43
> 0.5
>  10
> 40585366.70650577
>  20
> 3433935.538090975
> ```
> 
> This is the starting point as ogrinfo shows it:
> 
> `LINESTRING (40585366.7065058 3433935.53809098,`
> 
> Something happens when converting text into double and back, or? Is it even possible to avoid this, if numbers have a precision of 10^-8?

This is the geojson output I got
```
{ "type": "Feature", "id": 3, "properties": { "Layer": "test", "SubClasses": "AcDbEntity:AcDbPolyline", "EntityHandle": "215" }, "geometry": { "type": "LineString", "coordinates": [ [ 40585366.70650576800108, 3433935.538090975023806 ], [ 40585329.925648629665375, 3433998.440817071124911 ], [ 40585329.925648629665375, 3433998.44081707065925 ], [ 40585328.538767799735069, 3434000.636808053590357 ], [ 40585327.005119815468788, 3434002.732932742219418 ], [ 40585325.331869304180145, 3434004.719398842193186 ], [ 40585323.526833049952984, 3434006.586926342453808 ], [ 40585321.598443500697613, 3434008.326790865976363 ], [ 40585319.555709339678288, 3434009.930864430963993 ], [ 40585317.408173456788063, 3434011.391653417143971 ], [ 40585315.165868312120438, 3434012.702333576511592 ], [ 40585312.83926910161972, 3434013.856781910639256 ], [ 40585310.439244814217091, 3434014.849605278111994 ], [ 40585307.977007433772087, 3434015.676165586803108 ], [ 40585305.464059606194496, 3434016.332601462490857 ], [ 40585302.912140861153603, 3434016.815846287179738 ], [ 40585300.333172790706158, 3434017.12364252563566 ], [ 40585297.739203348755836, 3434017.254552271217108 ], [ 40585271.131317831575871, 3434017.686781913042068 ], [ 40585252.169814921915531, 3433885.99037547595799 ], [ 40585256.741470001637936, 3433885.916111595928669 ], [ 40585256.741470001637936, 3433885.916111595928669 ], [ 40585266.292061425745487, 3433886.091624200809747 ], [ 40585275.807631693780422, 3433886.927401483524591 ], [ 40585285.242589309811592, 3433888.41943902336061 ], [ 40585294.551729008555412, 3433890.560588093008846 ], [ 40585303.690448343753815, 3433893.340589905157685 ], [ 40585312.614961408078671, 3433896.746124770026654 ], [ 40585321.282508611679077, 3433900.760875909589231 ], [ 40585329.651561543345451, 3433905.365607637912035 ], [ 40585364.248373560607433, 3433925.992208717856556 ], [ 40585364.248373560607433, 3433925.992208717390895 ], [ 40585364.648196414113045, 3433926.249376509804279 ], [ 40585365.029642403125763, 3433926.533088588155806 ], [ 40585365.390952251851559, 3433926.842036440037191 ], [ 40585365.730459570884705, 3433927.174795162398368 ], [ 40585366.046598501503468, 3433927.529830033890903 ], [ 40585366.337910987436771, 3433927.905503594316542 ], [ 40585366.603053450584412, 3433928.300083193462342 ], [ 40585366.840803027153015, 3433928.711748985107988 ], [ 40585367.050063192844391, 3433929.138602320104837 ], [ 40585367.229868806898594, 3433929.578674502205104 ], [ 40585367.379390597343445, 3433930.02993586845696 ], [ 40585367.497938938438892, 3433930.490305149927735 ], [ 40585367.584967084228992, 3433930.957659070380032 ], [ 40585367.640073649585247, 3433931.429842141456902 ], [ 40585367.663004472851753, 3433931.904676599893719 ], [ 40585367.653653793036938, 3433932.379972455557436 ], [ 40585367.612064741551876, 3433932.8535375893116 ], [ 40585367.538429126143456, 3433933.323187865782529 ], [ 40585367.433086566627026, 3433933.786757203284651 ], [ 40585367.296522915363312, 3433934.242107568308711 ], [ 40585367.129368022084236, 3433934.68713883170858 ], [ 40585366.932392813265324, 3433935.119798459578305 ], [ 40585366.70650576800108, 3433935.538090975955129 ] ] } }
```

**Closed** 2024-06-14 09:11 UTC

**Comment by mumumi** [comment] 2024-06-21 02:08
@rouault I saw the code you submitted, especially the unit test where you parse and output WKT from the DXF I provided. it is considered passed when the output is a polyline. This issue I submitted includes two reasons. First, there is a precision problem that causes the first and last points to be inconsistent, which should be resolved in your code. Second, what is actually drawn in CAD is a polygon. It is displayed as a polyline in DXF because of arcs. When this DXF is loaded into various CAD software, it is treated as a polygon. In other words, in CAD, if you draw a rectangle and export it as DXF, it will show as a polygon. As long as you replace one straight edge with an arc edge, the exported DXF will show as a polyline, but the program still knows it is a polygon, including the area attribute.

**Comment by rouault** [comment] 2024-06-21 12:13
> Second, what is actually drawn in CAD is a polygon.

see https://github.com/OSGeo/gdal/pull/10261

**Comment by mumumi** [comment] 2024-06-24 09:34
[shapes.zip](https://github.com/user-attachments/files/15953050/shapes.zip)

@rouault The use of the DXF_CLOSED_LINE_AS_POLYGON option may not be sufficient as a final solution. A dxf file is provided here, which includes four figures: a polygon with arcs, a polygon with only straight lines, a polyline with arcs, and a polyline with only straight lines. When opened in AutoCAD, all four figures have an area attribute, with the closed attribute for the two polygons being set to "yes," and the closed attribute for the two polylines being set to "no." When opened in Microstation, the two polygons have an area attribute, while the two polylines do not have an area attribute. When converting to GeoJSON using libredwg, it correctly distinguishes between polygons and polylines.

**Comment by jratike80** [comment] 2024-06-24 11:04
I tried to understand DXF. Is the meaning of the Closed flag for polylines really to close the linestring AND convert it into a polygon, or just to make a closed ring?

I had a closer look at the the straight versions in the source data. They differ by the "closed" flag

The linestring version:

```
AcDbPolyline
 90
        5
 70
   128
```

The polygon version:

```
AcDbPolyline
 90
        5
 70
   129
```

So the value for the linestring is "Plinegen" and for the polygon it is "Closed + Plinegen".

Both geometries have 5 vertices. I would have thought that the closed version should have only 4, and the Closed flag would perfect the ring automatically. But if the geometry comes from AutoCAD then it looks like a valid option to repeat the first vertex as the last vertex and still have the Closed flag.

LibreCAD people have also been pondering closed polylines. They do not discuss about making them into polygons https://forum.librecad.org/how-to-check-if-every-entity-polyline-on-your-drawing-is-closed-and-strange-behaviour-of-creating-pos-td5721401.html

> For explanation:
> When you create a new polyline using the Polyline tools, there is a button in the tool option bar to close the polyline. This button sets the closed property for the polyline and close it.
> On the other hand you can use snapping and finish the polyline on the starting vertex. This results also in a visually closed polyline, but the closed property is not set.
> You can check this with the List plugin too. Create two polyline rectangles, both cases as described.
> One U shaped with the close button and one with snap on starting point.
> Then look at them in the List plugin.
> The closed polyline has only 4 vertices, where the first and last one are not identical. These 4 vertices create 3 lines and the closed flag creates the 4th line between the first and last vertex.
> The other one has 5 vertices and the first and last one are the same. These 5 vertices create 4 lines and a closed shape too.
> 
> The DXF reference is not detailed about the closed flag, so it leaves room for interpretation.
> - The interpretation of LibreCAD is, that a polyline, with closed flag set, has to be drawn closed.
> - Without the closed flag set, the polyline is not modified.
> - There is no rule which says that the closed flag has to be set for polylines with identical first and last vertex.

By https://help.autodesk.com/view/MAP/2024/ENU/?guid=GUID-6129F222-C2C8-4340-AF13-51803B178EAB AutoCAD does not automatically recognize closed multilines as polygons.

> Each closed polyline in the selection set is converted. If the polyline belongs to a group, only the first (outermost) polyline is converted. Other polylines in the group are copied into the polygon as additional boundaries and the polygon is rebalanced.

**Comment by jratike80** [comment] 2024-06-25 08:56
If you read the polygon.dxf back to AutoCAD, does it make the closed polyline into a polygon automatically? If ezdxf can be used as an official reference, this seems to be the case

https://ezdxf.readthedocs.io/en/stable/addons/geo.html#proxy-from-dxf-entity

> Supported DXF entities are:
> 
> POINT as “Point”
> 
> LINE as “LineString”
> 
> LWPOLYLINE as “LineString” if open and “Polygon” if closed
> POLYLINE as “LineString” if open and “Polygon” if closed, supports only 2D and 3D polylines, POLYMESH and POLYFACE are not supported
> 
> SOLID, TRACE, 3DFACE as “Polygon”
> 
> CIRCLE, ARC, ELLIPSE and SPLINE by approximation as “LineString” if open and “Polygon” if closed
> HATCH and MPOLYGON as “Polygon”, holes are supported

There is also a warning:

> This module does no extensive validity checks for “Polygon” objects and because DXF has different requirements for HATCH boundary paths than the [GeoJSON](https://pypi.org/project/geojson/) Standard, it is possible to create invalid “Polygon” objects. It is recommended to check critical objects by a sophisticated geometry library like [Shapely](https://pypi.org/project/Shapely/).

**Comment by mumumi** [comment] 2024-06-25 10:09
@jratike80 Thank you for the prompt response. I completely agree with the essence of what you said; to overturn it, one needs to find a closed polyline that is not a polygon. Since none of us are experts in CAD, we are all making conjectures based on some phenomena. Just now, I drew three points in AutoCAD to form two segments of a polyline, copied it, and set the "closed" option to true. The interface added a line connecting the first and last points, forming a triangle. When exported to DXF, both shapes have 3 vertices, with the first shape having a flag 70 value of 0, and the second has a value of 1. When converted to GeoJSON using libredwg, both are linestrings with three vertices. When opened in Microstation, one is displayed as a polyline with the property of a line, and the other is displayed as a triangle with the property of a polygon. Let's first record these test cases.
