### ISSUE TITLE
OGRFeature SetField  UTF8  not working

### ISSUE THREAD

**Issue by sagido** [OSGeo/gdal#9235] opened 2024-02-15 15:17 UTC
I try to write UTF8 ( Windows UNICODE is UTF16)

code is in C++ 

#define CPL_ENC_UTF8   "UTF-8"
char *c;
poFeature->SetField(index,c);

tried to convert to UTF8 with  CPLRecodeFromWChar but it returned NULL. 
What to put in c ?

**Comment by rouault** [comment] 2024-02-18 18:44
Closing as much likely not a bug but a usage issue. cf https://github.com/search?q=repo%3AOSGeo%2Fgdal%20%20CPLRecodeFromWChar&type=code for various uses of  CPLRecodeFromWChar()

**Closed by rouault** 2024-02-18 18:44 UTC
