### ISSUE TITLE
Segfault with gdal.RasterizeLayer

### ISSUE THREAD

**Issue by remicres** [OSGeo/gdal#1229] opened 2019-01-23 10:28 UTC
## Expected behavior and actual behavior.

I encounter a "Segmentation fault" issue when using `gdal.RasterizeLayer` from python. Using the `gdal_rasterize` application plays fine, and I don't understand why I have this error from python.

Strangely, I can't reproduce bug everywhere, so I suspect that it is system dependent. On a Ubuntu 16.04, I've failed to reproduce the bug. On a Ubuntu 16.04.5 with the (quite) same environment, I can reproduce it. 

## Steps to reproduce the problem.

The following script reproduces the bug (or not, depending on system/environment!).
```
# -*- coding: utf-8 -*-
import os
import ogr, gdal
from gdalconst import *

if __name__ == "__main__":
  geotransform = (749016.0, 1.0, 0.0, 6295413.0, 0.0, -1.0)
  ncols = 155540
  nrows = 139864
  proj = 'PROJCS["RGF93 / Lambert-93",GEOGCS["RGF93",DATUM["Reseau_Geodesique_Francais_1993",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6171"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4171"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",49],PARAMETER["standard_parallel_2",44],PARAMETER["latitude_of_origin",46.5],PARAMETER["central_meridian",3],PARAMETER["false_easting",700000],PARAMETER["false_northing",6600000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["X",EAST],AXIS["Y",NORTH],AUTHORITY["EPSG","2154"]]'

  driver = gdal.GetDriverByName('GTiff')
  outDs = driver.Create("temp.tif", ncols, nrows, 1, GDT_Byte, ["COMPRESS=DEFLATE"])
  outDs.SetGeoTransform(geotransform)
  outDs.SetProjection(proj)	

  # Create a Polygon from the extent tuple
  resX = geotransform[1]
  resY = geotransform[5]
  minX = geotransform[0]
  maxY = geotransform[3]
  minY = maxY + nrows * resY
  maxX = minX + ncols * resX

  ring = ogr.Geometry(ogr.wkbLinearRing)
  ring.AddPoint(minX, maxY)
  ring.AddPoint(maxX, maxY)
  ring.AddPoint(maxX, minY)
  ring.AddPoint(minX, minY)
  ring.AddPoint(minX, maxY)

  poly = ogr.Geometry(ogr.wkbPolygon)
  poly.AddGeometry(ring)

  # Save extent to a new Shapefile
  outShapefile = "temp.shp"
  outDriver = ogr.GetDriverByName("ESRI Shapefile")

  # Remove output shapefile if it already exists
  if os.path.exists(outShapefile):
    outDriver.DeleteDataSource(outShapefile)

  # Create the output shapefile
  outDataSource = outDriver.CreateDataSource(outShapefile)
  outLayer = outDataSource.CreateLayer("states_extent", geom_type=ogr.wkbPolygon, srs=ogr.osr.SpatialReference(proj))

  # Add an ID field
  idField = ogr.FieldDefn("id", ogr.OFTInteger)
  outLayer.CreateField(idField)

  # Create the feature and set values
  featureDefn = outLayer.GetLayerDefn()
  feature = ogr.Feature(featureDefn)
  feature.SetGeometry(poly)
  feature.SetField("id", 1)
  outLayer.CreateFeature(feature)

  status = gdal.RasterizeLayer(outDs, [1], outLayer, burn_values=[1])
  
  # Close DataSource
  outDataSource.Destroy()
```

On my server where the bug happen:
```
python bug.py
Segmentation fault (core dumped)

```

## Operating system
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

```

## GDAL version and provenance

`GDAL 2.2.1, released 2017/06/23`
Compiled from sources (SuperBuild of Orfeo ToolBox 6.7.0, commit 5721fe001abc8bd8c3475dfc3c64fccb79357d3b)

**Comment by rouault** [comment] 2019-01-23 10:45
Perhaps try running under gdb to get a backtrace
```
$ gdb python
run bug.py
bt
```
And check with a newer GDAL release too

**Comment by remicres** [comment] 2019-01-23 13:31
backtrace:
```
(gdb) run bug.py
Starting program: /usr/bin/python bug.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7962a9e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff7962a9e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff5c36e92 in memset (__len=<optimized out>, __ch=<optimized out>, __dest=<optimized out>) at /usr/include/x86_64-linux-gnu/bits/string3.h:90
#2  gvBurnScanline (pCBData=0x7fffffffd3f0, nY=13807, nXStart=<optimized out>, nXEnd=<optimized out>, dfVariant=<optimized out>) at gdalrasterize.cpp:99
#3  0x00007ffff5c5e1a4 in GDALdllImageFilledPolygon (nRasterXSize=155540, nRasterYSize=<optimized out>, nPartCount=<optimized out>, panPartSize=0xd3e420, padfX=0xb4dfb0, padfY=0xbb2ff0, dfVariant=0x0, 
    pfnScanlineFunc=0x7ffff5c36d80 <gvBurnScanline(void*, int, int, int, double)>, pCBData=0x7fffffffd3f0) at llrasterize.cpp:245
#4  0x00007ffff5c37913 in gv_rasterize_one_shape (pabyChunkBuf=pabyChunkBuf@entry=0x7ffc02967010 '\001' <repeats 200 times>..., nYOff=nYOff@entry=0, nXSize=155540, nYSize=nYSize@entry=107864, 
    nBands=nBands@entry=1, eType=eType@entry=GDT_Byte, bAllTouched=0, poShape=0xae7910, padfBurnValue=0xbaf5c0, eBurnValueSrc=GBV_UserBurnValue, eMergeAlg=GRMA_Replace, pfnTransformer=
    0x7ffff5c3bab0 <GDALGenImgProjTransform(void*, int, int, double*, double*, double*, int*)>, pTransformArg=0xb1d500) at gdalrasterize.cpp:432
#5  0x00007ffff5c38610 in GDALRasterizeLayers (hDS=hDS@entry=0xaf0330, nBandCount=nBandCount@entry=1, panBandList=panBandList@entry=0xb4e0a0, nLayerCount=nLayerCount@entry=1, 
    pahLayers=pahLayers@entry=0x7fffffffd638, pfnTransformer=0x7ffff5c3bab0 <GDALGenImgProjTransform(void*, int, int, double*, double*, double*, int*)>, pfnTransformer@entry=0x0, pTransformArg=0xb1d500, 
    padfLayerBurnValues=0xbaf5c0, papszOptions=0x0, pfnProgress=0x7ffff635dbf0 <GDALDummyProgress(double, char const*, void*)>, pProgressArg=0xae7e70) at gdalrasterize.cpp:1081
#6  0x00007ffff69bb299 in RasterizeLayer (dataset=0xaf0330, bands=1, band_list=0xb4e0a0, layer=0xa2f010, pfnTransformer=0x0, pTransformArg=0x0, burn_values=1, burn_values_list=0xbaf5c0, options=0x0, 
    callback=0x0, callback_data=0xae7e70) at extensions/gdal_wrap.cpp:5599
#7  0x00007ffff69bbb89 in _wrap_RasterizeLayer (args=<optimized out>, kwargs=<optimized out>) at extensions/gdal_wrap.cpp:24169
#8  0x00000000004c30ce in PyEval_EvalFrameEx ()
#9  0x00000000004b9ab6 in PyEval_EvalCodeEx ()
#10 0x00000000004c1e6f in PyEval_EvalFrameEx ()
#11 0x00000000004b9ab6 in PyEval_EvalCodeEx ()
#12 0x00000000004eb30f in ?? ()
#13 0x00000000004e5422 in PyRun_FileExFlags ()
#14 0x00000000004e3cd6 in PyRun_SimpleFileExFlags ()
#15 0x0000000000493ae2 in Py_Main ()
#16 0x00007ffff7810830 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#17 0x00000000004933e9 in _start ()
```
I'll check with a newer version of GDAL

**Comment by rouault** [comment] 2019-03-20 22:17
Likely a duplicate of #1338

**Closed by rouault** 2019-03-20 22:17 UTC
